
package fr.iamacat.dangerzone_iamacatfr.entities.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;

public class AlicornSword extends ModelBase {

    ModelRenderer Wield;
    ModelRenderer WieldBottom;
    ModelRenderer Spike1;
    ModelRenderer Spike2;
    ModelRenderer GuardMiddle;
    ModelRenderer GuardL;
    ModelRenderer GuardR;
    ModelRenderer AlicornGem;
    ModelRenderer GuardCentre;
    ModelRenderer BladeC;
    ModelRenderer BladeL;
    ModelRenderer BladeR;
    ModelRenderer CrystalTopCentre;
    ModelRenderer CrystalTopRight;
    ModelRenderer CrystalTopLeft;
    ModelRenderer CrystalL;
    ModelRenderer CrystalR;
    ModelRenderer Slice1;
    ModelRenderer Slice4;
    ModelRenderer BladeLM;
    ModelRenderer BladeRM;
    ModelRenderer BladeC3;
    ModelRenderer BladeC2;
    ModelRenderer BladeC4;
    ModelRenderer BladeLB;
    ModelRenderer BladeRB;
    ModelRenderer BladeLT;
    ModelRenderer BladeRT;
    ModelRenderer Slice2;
    ModelRenderer Slice3;
    ModelRenderer Slice5;
    ModelRenderer Slice6;
    ModelRenderer GuardL2;
    ModelRenderer GuardR2;
    ModelRenderer CrystalL2;
    ModelRenderer CrystalR2;

    public AlicornSword() {
        this.textureWidth = 256;
        this.textureHeight = 256;
        (this.Wield = new ModelRenderer((ModelBase) this, 0, 100)).addBox(0.0f, 0.0f, 0.0f, 2, 6, 2);
        this.Wield.setRotationPoint(-1.0f, 15.0f, -1.0f);
        this.Wield.setTextureSize(256, 256);
        this.Wield.mirror = true;
        this.setRotation(this.Wield, 0.0f, 0.0f, 0.0f);
        (this.WieldBottom = new ModelRenderer((ModelBase) this, 0, 114)).addBox(0.0f, 0.0f, 0.0f, 3, 2, 3);
        this.WieldBottom.setRotationPoint(-1.5f, 20.0f, -1.5f);
        this.WieldBottom.setTextureSize(256, 256);
        this.WieldBottom.mirror = true;
        this.setRotation(this.WieldBottom, 0.0f, 0.0f, 0.0f);
        (this.Spike1 = new ModelRenderer((ModelBase) this, 0, 155)).addBox(0.0f, 0.0f, 0.0f, 1, 1, 4);
        this.Spike1.setRotationPoint(-0.5f, 20.5f, -2.0f);
        this.Spike1.setTextureSize(256, 256);
        this.Spike1.mirror = true;
        this.setRotation(this.Spike1, 0.0f, 0.0f, 0.0f);
        (this.Spike2 = new ModelRenderer((ModelBase) this, 0, 155)).addBox(0.0f, 0.0f, 0.0f, 4, 1, 1);
        this.Spike2.setRotationPoint(-2.0f, 20.5f, -0.5f);
        this.Spike2.setTextureSize(256, 256);
        this.Spike2.mirror = true;
        this.setRotation(this.Spike2, 0.0f, 0.0f, 0.0f);
        (this.GuardMiddle = new ModelRenderer((ModelBase) this, 16, 32)).addBox(0.0f, 0.0f, 0.0f, 5, 3, 2);
        this.GuardMiddle.setRotationPoint(-2.5f, 12.0f, -1.0f);
        this.GuardMiddle.setTextureSize(256, 256);
        this.GuardMiddle.mirror = true;
        this.setRotation(this.GuardMiddle, 0.0f, 0.0f, 0.0f);
        (this.GuardL = new ModelRenderer((ModelBase) this, 16, 25)).addBox(-1.0f, 0.0f, -0.5f, 4, 2, 1);
        this.GuardL.setRotationPoint(2.0f, 12.0f, 0.0f);
        this.GuardL.setTextureSize(256, 256);
        this.GuardL.mirror = true;
        this.setRotation(this.GuardL, 0.0f, 0.0f, -0.3717861f);
        (this.GuardR = new ModelRenderer((ModelBase) this, 16, 17)).addBox(-2.0f, -0.5f, -0.5f, 4, 2, 1);
        this.GuardR.setRotationPoint(-3.0f, 12.0f, 0.0f);
        this.GuardR.setTextureSize(256, 256);
        this.GuardR.mirror = true;
        this.setRotation(this.GuardR, 0.0f, 0.0f, 0.37179f);
        (this.AlicornGem = new ModelRenderer((ModelBase) this, 16, 52)).addBox(0.0f, 0.0f, 0.0f, 1, 1, 4);
        this.AlicornGem.setRotationPoint(-0.5f, 13.0f, -2.0f);
        this.AlicornGem.setTextureSize(256, 256);
        this.AlicornGem.mirror = true;
        this.setRotation(this.AlicornGem, 0.0f, 0.0f, 0.0f);
        (this.GuardCentre = new ModelRenderer((ModelBase) this, 16, 41)).addBox(0.0f, 0.0f, 0.0f, 3, 3, 3);
        this.GuardCentre.setRotationPoint(-1.5f, 12.0f, -1.5f);
        this.GuardCentre.setTextureSize(256, 256);
        this.GuardCentre.mirror = true;
        this.setRotation(this.GuardCentre, 0.0f, 0.0f, 0.0f);
        (this.BladeC = new ModelRenderer((ModelBase) this, 0, 20)).addBox(0.0f, 0.0f, -0.1f, 2, 14, 1);
        this.BladeC.setRotationPoint(-1.0f, -2.0f, -0.5f);
        this.BladeC.setTextureSize(256, 256);
        this.BladeC.mirror = true;
        this.setRotation(this.BladeC, 0.0f, 0.0f, 0.0f);
        (this.BladeL = new ModelRenderer((ModelBase) this, 0, 38)).addBox(0.0f, 0.0f, 0.0f, 2, 14, 1);
        this.BladeL.setRotationPoint(0.0f, -2.0f, -0.5f);
        this.BladeL.setTextureSize(256, 256);
        this.BladeL.mirror = true;
        this.setRotation(this.BladeL, 0.0f, 0.0f, 0.0698132f);
        (this.BladeR = new ModelRenderer((ModelBase) this, 0, 58)).addBox(0.0f, 0.0f, 0.0f, 2, 14, 1);
        this.BladeR.setRotationPoint(-2.0f, -1.8f, -0.5f);
        this.BladeR.setTextureSize(256, 256);
        this.BladeR.mirror = true;
        this.setRotation(this.BladeR, 0.0f, 0.0f, -0.0698132f);
        (this.CrystalTopCentre = new ModelRenderer((ModelBase) this, 67, 0)).addBox(0.0f, 0.0f, 0.0f, 1, 7, 1);
        this.CrystalTopCentre.setRotationPoint(-0.5f, -23.0f, -0.5f);
        this.CrystalTopCentre.setTextureSize(256, 256);
        this.CrystalTopCentre.mirror = true;
        this.setRotation(this.CrystalTopCentre, 0.0f, 0.0f, 0.0f);
        (this.CrystalTopRight = new ModelRenderer((ModelBase) this, 54, 0)).addBox(0.0f, 0.0f, 0.0f, 1, 6, 1);
        this.CrystalTopRight.setRotationPoint(1.5f, -21.0f, -0.5f);
        this.CrystalTopRight.setTextureSize(256, 256);
        this.CrystalTopRight.mirror = true;
        this.setRotation(this.CrystalTopRight, 0.0f, 0.0f, 0.3490659f);
        (this.CrystalTopLeft = new ModelRenderer((ModelBase) this, 43, 0)).addBox(0.0f, 0.0f, 0.0f, 1, 6, 1);
        this.CrystalTopLeft.setRotationPoint(-2.5f, -21.0f, -0.5f);
        this.CrystalTopLeft.setTextureSize(256, 256);
        this.CrystalTopLeft.mirror = true;
        this.setRotation(this.CrystalTopLeft, 0.0f, 0.0f, -0.3490659f);
        (this.CrystalL = new ModelRenderer((ModelBase) this, 29, 0)).addBox(0.0f, 0.0f, 0.0f, 1, 6, 1);
        this.CrystalL.setRotationPoint(3.0f, 7.0f, -0.5f);
        this.CrystalL.setTextureSize(256, 256);
        this.CrystalL.mirror = true;
        this.setRotation(this.CrystalL, 0.0f, 0.0f, 0.3490659f);
        (this.CrystalR = new ModelRenderer((ModelBase) this, 19, 0)).addBox(0.0f, 0.0f, 0.0f, 1, 6, 1);
        this.CrystalR.setRotationPoint(-4.0f, 7.0f, -0.5f);
        this.CrystalR.setTextureSize(256, 256);
        this.CrystalR.mirror = true;
        this.setRotation(this.CrystalR, 0.0f, 0.0f, -0.3490659f);
        (this.Slice1 = new ModelRenderer((ModelBase) this, 0, 78)).addBox(0.0f, 0.0f, 0.0f, 1, 13, 1);
        this.Slice1.setRotationPoint(-0.5f, -1.0f, -0.7f);
        this.Slice1.setTextureSize(256, 256);
        this.Slice1.mirror = true;
        this.setRotation(this.Slice1, 0.0f, 0.0f, 0.0f);
        (this.Slice4 = new ModelRenderer((ModelBase) this, 0, 0)).addBox(0.0f, 0.0f, 0.0f, 1, 13, 1);
        this.Slice4.setRotationPoint(-0.5f, -1.0f, -0.2f);
        this.Slice4.setTextureSize(256, 256);
        this.Slice4.mirror = true;
        this.setRotation(this.Slice4, 0.0f, 0.0f, 0.0f);
        (this.BladeLM = new ModelRenderer((ModelBase) this, 0, 38)).addBox(0.0f, 0.0f, 0.0f, 2, 14, 1);
        this.BladeLM.setRotationPoint(-1.0f, -15.0f, -0.5f);
        this.BladeLM.setTextureSize(256, 256);
        this.BladeLM.mirror = true;
        this.setRotation(this.BladeLM, 0.0f, 0.0f, -0.0698132f);
        (this.BladeRM = new ModelRenderer((ModelBase) this, 0, 58)).addBox(0.0f, 0.0f, 0.0f, 2, 14, 1);
        this.BladeRM.setRotationPoint(-1.0f, -15.8f, -0.5f);
        this.BladeRM.setTextureSize(256, 256);
        this.BladeRM.mirror = true;
        this.setRotation(this.BladeRM, 0.0f, 0.0f, 0.0698132f);
        (this.BladeC3 = new ModelRenderer((ModelBase) this, 0, 20)).addBox(0.0f, 0.0f, 0.1f, 2, 14, 1);
        this.BladeC3.setRotationPoint(-1.0f, -2.0f, -0.5f);
        this.BladeC3.setTextureSize(256, 256);
        this.BladeC3.mirror = true;
        this.setRotation(this.BladeC3, 0.0f, 0.0f, 0.0f);
        (this.BladeC2 = new ModelRenderer((ModelBase) this, 0, 20)).addBox(0.0f, 0.0f, -0.1f, 2, 14, 1);
        this.BladeC2.setRotationPoint(-1.0f, -16.0f, -0.5f);
        this.BladeC2.setTextureSize(256, 256);
        this.BladeC2.mirror = true;
        this.setRotation(this.BladeC2, 0.0f, 0.0f, 0.0f);
        (this.BladeC4 = new ModelRenderer((ModelBase) this, 0, 20)).addBox(0.0f, 0.0f, 0.1f, 2, 14, 1);
        this.BladeC4.setRotationPoint(-1.0f, -16.0f, -0.5f);
        this.BladeC4.setTextureSize(256, 256);
        this.BladeC4.mirror = true;
        this.setRotation(this.BladeC4, 0.0f, 0.0f, 0.0f);
        (this.BladeLB = new ModelRenderer((ModelBase) this, 0, 38)).addBox(1.2f, 0.0f, 0.0f, 1, 6, 1);
        this.BladeLB.setRotationPoint(-1.0f, 7.0f, -0.5f);
        this.BladeLB.setTextureSize(256, 256);
        this.BladeLB.mirror = true;
        this.setRotation(this.BladeLB, 0.0f, 0.0f, -0.0698132f);
        (this.BladeRB = new ModelRenderer((ModelBase) this, 0, 58)).addBox(-1.2f, 0.0f, 0.0f, 2, 6, 1);
        this.BladeRB.setRotationPoint(0.0f, 6.2f, -0.5f);
        this.BladeRB.setTextureSize(256, 256);
        this.BladeRB.mirror = true;
        this.setRotation(this.BladeRB, 0.0f, 0.0f, 0.0698132f);
        (this.BladeLT = new ModelRenderer((ModelBase) this, 0, 38)).addBox(0.8f, 0.0f, 0.0f, 2, 6, 1);
        this.BladeLT.setRotationPoint(-1.0f, -16.0f, -0.5f);
        this.BladeLT.setTextureSize(256, 256);
        this.BladeLT.mirror = true;
        this.setRotation(this.BladeLT, 0.0f, 0.0f, 0.0698132f);
        (this.BladeRT = new ModelRenderer((ModelBase) this, 0, 58)).addBox(-0.8f, 0.0f, 0.0f, 2, 8, 1);
        this.BladeRT.setRotationPoint(-1.0f, -15.8f, -0.5f);
        this.BladeRT.setTextureSize(256, 256);
        this.BladeRT.mirror = true;
        this.setRotation(this.BladeRT, 0.0f, 0.0f, -0.0698132f);
        (this.Slice2 = new ModelRenderer((ModelBase) this, 0, 78)).addBox(0.0f, 0.0f, 0.0f, 1, 13, 1);
        this.Slice2.setRotationPoint(-0.5f, -14.0f, -0.7f);
        this.Slice2.setTextureSize(256, 256);
        this.Slice2.mirror = true;
        this.setRotation(this.Slice2, 0.0f, 0.0f, 0.0f);
        (this.Slice3 = new ModelRenderer((ModelBase) this, 0, 78)).addBox(0.0f, 0.0f, 0.0f, 1, 3, 1);
        this.Slice3.setRotationPoint(-0.5f, -16.0f, -0.7f);
        this.Slice3.setTextureSize(256, 256);
        this.Slice3.mirror = true;
        this.setRotation(this.Slice3, 0.0f, 0.0f, 0.0f);
        (this.Slice5 = new ModelRenderer((ModelBase) this, 0, 0)).addBox(0.0f, 0.0f, 0.0f, 1, 13, 1);
        this.Slice5.setRotationPoint(-0.5f, -14.0f, -0.2f);
        this.Slice5.setTextureSize(256, 256);
        this.Slice5.mirror = true;
        this.setRotation(this.Slice5, 0.0f, 0.0f, 0.0f);
        (this.Slice6 = new ModelRenderer((ModelBase) this, 0, 0)).addBox(0.0f, 0.0f, 0.0f, 1, 3, 1);
        this.Slice6.setRotationPoint(-0.5f, -16.0f, -0.2f);
        this.Slice6.setTextureSize(256, 256);
        this.Slice6.mirror = true;
        this.setRotation(this.Slice6, 0.0f, 0.0f, 0.0f);
        (this.GuardL2 = new ModelRenderer((ModelBase) this, 16, 25)).addBox(3.0f, -0.3f, -0.5f, 4, 1, 1);
        this.GuardL2.setRotationPoint(2.0f, 13.0f, 0.0f);
        this.GuardL2.setTextureSize(256, 256);
        this.GuardL2.mirror = true;
        this.setRotation(this.GuardL2, 0.0f, 0.0f, -0.5585054f);
        (this.GuardR2 = new ModelRenderer((ModelBase) this, 16, 17)).addBox(-6.0f, -1.0f, -0.5f, 4, 1, 1);
        this.GuardR2.setRotationPoint(-3.0f, 13.0f, 0.0f);
        this.GuardR2.setTextureSize(256, 256);
        this.GuardR2.mirror = true;
        this.setRotation(this.GuardR2, 0.0f, 0.0f, 0.5585054f);
        (this.CrystalL2 = new ModelRenderer((ModelBase) this, 29, 0)).addBox(0.0f, 0.0f, 0.0f, 1, 6, 1);
        this.CrystalL2.setRotationPoint(3.8f, 2.0f, -0.5f);
        this.CrystalL2.setTextureSize(256, 256);
        this.CrystalL2.mirror = true;
        this.setRotation(this.CrystalL2, 0.0f, 0.0f, 0.1745329f);
        (this.CrystalR2 = new ModelRenderer((ModelBase) this, 19, 0)).addBox(0.0f, 0.0f, 0.0f, 1, 6, 1);
        this.CrystalR2.setRotationPoint(-4.8f, 2.0f, -0.5f);
        this.CrystalR2.setTextureSize(256, 256);
        this.CrystalR2.mirror = true;
        this.setRotation(this.CrystalR2, 0.0f, 0.0f, -0.1745329f);
    }

    public void render() {
        final float f5 = 1.0f;
        this.Wield.render(f5);
        this.WieldBottom.render(f5);
        this.Spike1.render(f5);
        this.Spike2.render(f5);
        this.GuardMiddle.render(f5);
        this.GuardL.render(f5);
        this.GuardR.render(f5);
        this.AlicornGem.render(f5);
        this.GuardCentre.render(f5);
        this.BladeC.render(f5);
        this.BladeL.render(f5);
        this.BladeR.render(f5);
        this.CrystalTopCentre.render(f5);
        this.CrystalTopRight.render(f5);
        this.CrystalTopLeft.render(f5);
        this.CrystalL.render(f5);
        this.CrystalR.render(f5);
        this.Slice1.render(f5);
        this.Slice4.render(f5);
        this.BladeLM.render(f5);
        this.BladeRM.render(f5);
        this.BladeC3.render(f5);
        this.BladeC2.render(f5);
        this.BladeC4.render(f5);
        this.BladeLB.render(f5);
        this.BladeRB.render(f5);
        this.BladeLT.render(f5);
        this.BladeRT.render(f5);
        this.Slice2.render(f5);
        this.Slice3.render(f5);
        this.Slice5.render(f5);
        this.Slice6.render(f5);
        this.GuardL2.render(f5);
        this.GuardR2.render(f5);
        this.CrystalL2.render(f5);
        this.CrystalR2.render(f5);
    }

    private void setRotation(final ModelRenderer model, final float x, final float y, final float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }
}
