
package fr.iamacat.dangerzone_iamacatfr.entities.model;


import fr.iamacat.dangerzone_iamacatfr.entities.entity.PitchBlack;
import fr.iamacat.dangerzone_iamacatfr.entities.render.RenderInfo;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelPitchBlack extends ModelBase {

    private float wingspeed;
    ModelRenderer lclaw1;
    ModelRenderer body;
    ModelRenderer leftleg1;
    ModelRenderer tail1;
    ModelRenderer leftleg2;
    ModelRenderer body2;
    ModelRenderer leftleg3;
    ModelRenderer tail2;
    ModelRenderer tail3;
    ModelRenderer lclaw2;
    ModelRenderer lclaw3;
    ModelRenderer lclaw4;
    ModelRenderer lclaw5;
    ModelRenderer lclaw6;
    ModelRenderer lclaw7;
    ModelRenderer tail4;
    ModelRenderer tail5;
    ModelRenderer tail6;
    ModelRenderer tail7;
    ModelRenderer tail8;
    ModelRenderer tail9;
    ModelRenderer tailpoint1;
    ModelRenderer tailpoint2;
    ModelRenderer llegspike;
    ModelRenderer tailspike1;
    ModelRenderer tailspike2;
    ModelRenderer tailspike3;
    ModelRenderer tailspike4;
    ModelRenderer tailspike5;
    ModelRenderer tailspike6;
    ModelRenderer neck1;
    ModelRenderer neck2;
    ModelRenderer neck3;
    ModelRenderer head1;
    ModelRenderer leye;
    ModelRenderer reye;
    ModelRenderer head2;
    ModelRenderer head3;
    ModelRenderer head4;
    ModelRenderer head5;
    ModelRenderer head6;
    ModelRenderer jaw1;
    ModelRenderer jaw2;
    ModelRenderer jaw3;
    ModelRenderer jaw4;
    ModelRenderer tooth1;
    ModelRenderer tooth2;
    ModelRenderer tooth3;
    ModelRenderer tooth4;
    ModelRenderer tooth5;
    ModelRenderer jaw5;
    ModelRenderer head7;
    ModelRenderer tooth6;
    ModelRenderer tooth7;
    ModelRenderer tooth8;
    ModelRenderer tooth9;
    ModelRenderer tooth10;
    ModelRenderer tooth11;
    ModelRenderer tooth12;
    ModelRenderer tooth13;
    ModelRenderer rightleg1;
    ModelRenderer rightleg2;
    ModelRenderer tooth14;
    ModelRenderer tooth15;
    ModelRenderer tooth16;
    ModelRenderer tooth17;
    ModelRenderer tooth18;
    ModelRenderer tooth19;
    ModelRenderer tooth20;
    ModelRenderer tooth21;
    ModelRenderer tooth22;
    ModelRenderer tooth23;
    ModelRenderer rightleg3;
    ModelRenderer llegspike2;
    ModelRenderer rclaw2;
    ModelRenderer rclaw4;
    ModelRenderer rclaw1;
    ModelRenderer rclaw5;
    ModelRenderer rclaw7;
    ModelRenderer rclaw3;
    ModelRenderer rclaw6;
    ModelRenderer wing1;
    ModelRenderer wing2;
    ModelRenderer wing3;
    ModelRenderer mem1;
    ModelRenderer mem2;
    ModelRenderer mem3;
    ModelRenderer wingclaw1;
    ModelRenderer wingclaw2;
    ModelRenderer wingclaw3;
    ModelRenderer lshoulder;
    ModelRenderer rshoulder;
    ModelRenderer rwing1;
    ModelRenderer rmem1;
    ModelRenderer rwing2;
    ModelRenderer rmem2;
    ModelRenderer rwing3;
    ModelRenderer rmem3;
    ModelRenderer rwingclaw1;
    ModelRenderer rwingclaw2;
    ModelRenderer rwingclaw3;

    public ModelPitchBlack(final float f1) {
        this.wingspeed = 1.0f;
        this.wingspeed = f1;
        this.textureWidth = 512;
        this.textureHeight = 256;
        (this.lclaw1 = new ModelRenderer((ModelBase) this, 300, 111)).addBox(-3.0f, 0.0f, -3.0f, 2, 3, 6);
        this.lclaw1.setRotationPoint(7.0f, 21.0f, 11.0f);
        this.lclaw1.setTextureSize(512, 256);
        this.lclaw1.mirror = true;
        this.setRotation(this.lclaw1, 0.0f, 0.6632251f, 0.0f);
        (this.body = new ModelRenderer((ModelBase) this, 400, 26)).addBox(-6.0f, -12.0f, -9.0f, 12, 12, 9);
        this.body.setRotationPoint(0.0f, 0.0f, 9.0f);
        this.body.setTextureSize(512, 256);
        this.body.mirror = true;
        this.setRotation(this.body, 0.0698132f, 0.0f, 0.0f);
        (this.leftleg1 = new ModelRenderer((ModelBase) this, 300, 10)).addBox(-1.0f, -5.0f, -20.0f, 5, 10, 10);
        this.leftleg1.setRotationPoint(7.0f, 5.0f, 23.0f);
        this.leftleg1.setTextureSize(512, 256);
        this.leftleg1.mirror = true;
        this.setRotation(this.leftleg1, -0.5759587f, 0.0f, 0.0f);
        (this.tail1 = new ModelRenderer((ModelBase) this, 400, 82)).addBox(-5.0f, -6.0f, 0.0f, 8, 10, 12);
        this.tail1.setRotationPoint(1.0f, -3.0f, 22.0f);
        this.tail1.setTextureSize(512, 256);
        this.tail1.mirror = true;
        this.setRotation(this.tail1, -0.1745329f, 0.0f, 0.0f);
        (this.leftleg2 = new ModelRenderer((ModelBase) this, 300, 31)).addBox(-1.0f, -10.0f, -4.0f, 4, 12, 5);
        this.leftleg2.setRotationPoint(7.0f, 5.0f, 23.0f);
        this.leftleg2.setTextureSize(512, 256);
        this.leftleg2.mirror = true;
        this.setRotation(this.leftleg2, 0.9773844f, 0.0f, 0.0f);
        (this.body2 = new ModelRenderer((ModelBase) this, 400, 50)).addBox(0.0f, -3.0f, -3.0f, 12, 14, 16);
        this.body2.setRotationPoint(-6.0f, -9.0f, 10.0f);
        this.body2.setTextureSize(512, 256);
        this.body2.mirror = true;
        this.setRotation(this.body2, -0.1047198f, 0.0f, 0.0f);
        (this.leftleg3 = new ModelRenderer((ModelBase) this, 300, 51)).addBox(-1.0f, -19.0f, 1.0f, 3, 18, 4);
        this.leftleg3.setRotationPoint(7.0f, 21.0f, 11.0f);
        this.leftleg3.setTextureSize(512, 256);
        this.leftleg3.mirror = true;
        this.setRotation(this.leftleg3, -0.5235988f, 0.0f, 0.0f);
        (this.tail2 = new ModelRenderer((ModelBase) this, 400, 106)).addBox(-3.0f, -4.0f, 0.0f, 6, 8, 10);
        this.tail2.setRotationPoint(0.0f, -2.0f, 33.0f);
        this.tail2.setTextureSize(512, 256);
        this.tail2.mirror = true;
        this.setRotation(this.tail2, -0.1396263f, 0.0f, 0.0f);
        (this.tail3 = new ModelRenderer((ModelBase) this, 400, 126)).addBox(-2.0f, -2.0f, 0.0f, 4, 5, 10);
        this.tail3.setRotationPoint(0.0f, -1.0f, 42.0f);
        this.tail3.setTextureSize(512, 256);
        this.tail3.mirror = true;
        this.setRotation(this.tail3, -0.1396263f, 0.0f, 0.0f);
        (this.lclaw2 = new ModelRenderer((ModelBase) this, 300, 76)).addBox(-1.0f, -1.0f, -6.0f, 3, 4, 13);
        this.lclaw2.setRotationPoint(7.0f, 21.0f, 11.0f);
        this.lclaw2.setTextureSize(512, 256);
        this.lclaw2.mirror = true;
        this.setRotation(this.lclaw2, 0.0f, 0.0f, 0.0f);
        (this.lclaw3 = new ModelRenderer((ModelBase) this, 300, 95)).addBox(2.0f, 0.0f, -6.0f, 2, 3, 10);
        this.lclaw3.setRotationPoint(7.0f, 21.0f, 11.0f);
        this.lclaw3.setTextureSize(512, 256);
        this.lclaw3.mirror = true;
        this.setRotation(this.lclaw3, 0.0f, -0.6632251f, 0.0f);
        (this.lclaw4 = new ModelRenderer((ModelBase) this, 310, 123)).addBox(0.0f, 1.0f, -9.0f, 1, 2, 3);
        this.lclaw4.setRotationPoint(7.0f, 21.0f, 11.0f);
        this.lclaw4.setTextureSize(512, 256);
        this.lclaw4.mirror = true;
        this.setRotation(this.lclaw4, 0.0f, 0.0f, 0.0f);
        (this.lclaw5 = new ModelRenderer((ModelBase) this, 300, 123)).addBox(-2.5f, 1.0f, -5.0f, 1, 2, 2);
        this.lclaw5.setRotationPoint(7.0f, 21.0f, 11.0f);
        this.lclaw5.setTextureSize(512, 256);
        this.lclaw5.mirror = true;
        this.setRotation(this.lclaw5, 0.0f, 0.6632251f, 0.0f);
        (this.lclaw6 = new ModelRenderer((ModelBase) this, 322, 123)).addBox(2.5f, 1.0f, -9.0f, 1, 2, 3);
        this.lclaw6.setRotationPoint(7.0f, 21.0f, 11.0f);
        this.lclaw6.setTextureSize(512, 256);
        this.lclaw6.mirror = true;
        this.setRotation(this.lclaw6, 0.0f, -0.6632251f, 0.0f);
        (this.lclaw7 = new ModelRenderer((ModelBase) this, 333, 123)).addBox(0.0f, 1.0f, 7.0f, 1, 2, 3);
        this.lclaw7.setRotationPoint(7.0f, 21.0f, 11.0f);
        this.lclaw7.setTextureSize(512, 256);
        this.lclaw7.mirror = true;
        this.setRotation(this.lclaw7, 0.0f, 0.0f, 0.0f);
        (this.tail4 = new ModelRenderer((ModelBase) this, 400, 143)).addBox(-2.0f, -2.0f, 0.0f, 4, 4, 10);
        this.tail4.setRotationPoint(0.0f, 0.0f, 51.0f);
        this.tail4.setTextureSize(512, 256);
        this.tail4.mirror = true;
        this.setRotation(this.tail4, -0.1396263f, 0.0f, 0.0f);
        (this.tail5 = new ModelRenderer((ModelBase) this, 400, 159)).addBox(-1.5f, -2.0f, 0.0f, 3, 3, 10);
        this.tail5.setRotationPoint(0.0f, 1.0f, 59.0f);
        this.tail5.setTextureSize(512, 256);
        this.tail5.mirror = true;
        this.setRotation(this.tail5, -0.1396263f, 0.0f, 0.0f);
        (this.tail6 = new ModelRenderer((ModelBase) this, 400, 180)).addBox(0.0f, 0.0f, 0.0f, 2, 2, 10);
        this.tail6.setRotationPoint(0.0f, 0.0f, 68.0f);
        this.tail6.setTextureSize(512, 256);
        this.tail6.mirror = true;
        this.setRotation(this.tail6, -0.1396263f, 0.1745329f, 0.0f);
        (this.tail7 = new ModelRenderer((ModelBase) this, 400, 180)).addBox(-2.0f, 0.0f, 0.0f, 2, 2, 10);
        this.tail7.setRotationPoint(0.0f, 0.0f, 68.0f);
        this.tail7.setTextureSize(512, 256);
        this.tail7.mirror = true;
        this.setRotation(this.tail7, -0.1396263f, -0.1745329f, 0.0f);
        (this.tail8 = new ModelRenderer((ModelBase) this, 400, 180)).addBox(0.0f, 0.0f, 0.0f, 2, 2, 10);
        this.tail8.setRotationPoint(-4.0f, 1.0f, 77.0f);
        this.tail8.setTextureSize(512, 256);
        this.tail8.mirror = true;
        this.setRotation(this.tail8, -0.1396263f, -0.1745329f, 0.0f);
        (this.tail9 = new ModelRenderer((ModelBase) this, 400, 180)).addBox(0.0f, 0.0f, 0.0f, 2, 2, 10);
        this.tail9.setRotationPoint(2.0f, 1.0f, 77.0f);
        this.tail9.setTextureSize(512, 256);
        this.tail9.mirror = true;
        this.setRotation(this.tail9, -0.1396263f, 0.1745329f, 0.0f);
        (this.tailpoint1 = new ModelRenderer((ModelBase) this, 400, 200)).addBox(-1.0f, -1.0f, 0.0f, 1, 1, 22);
        this.tailpoint1.setRotationPoint(5.0f, 3.0f, 85.0f);
        this.tailpoint1.setTextureSize(512, 256);
        this.tailpoint1.mirror = true;
        this.setRotation(this.tailpoint1, -0.1919862f, 0.1745329f, 0.0f);
        (this.tailpoint2 = new ModelRenderer((ModelBase) this, 400, 200)).addBox(-1.0f, -1.0f, 0.0f, 1, 1, 22);
        this.tailpoint2.setRotationPoint(-4.0f, 3.0f, 86.0f);
        this.tailpoint2.setTextureSize(512, 256);
        this.tailpoint2.mirror = true;
        this.setRotation(this.tailpoint2, -0.1919862f, -0.1745329f, 0.0f);
        (this.llegspike = new ModelRenderer((ModelBase) this, 300, 131)).addBox(0.0f, -28.0f, 1.0f, 1, 12, 1);
        this.llegspike.setRotationPoint(7.0f, 21.0f, 11.0f);
        this.llegspike.setTextureSize(512, 256);
        this.llegspike.mirror = true;
        this.setRotation(this.llegspike, -0.6981317f, 0.0f, 0.0f);
        (this.tailspike1 = new ModelRenderer((ModelBase) this, 400, 230)).addBox(1.0f, -1.0f, 0.0f, 1, 1, 1);
        this.tailspike1.setRotationPoint(2.0f, 1.0f, 77.0f);
        this.tailspike1.setTextureSize(512, 256);
        this.tailspike1.mirror = true;
        this.setRotation(this.tailspike1, -0.1396263f, 0.1745329f, 0.0f);
        (this.tailspike2 = new ModelRenderer((ModelBase) this, 400, 230)).addBox(1.0f, -1.0f, 6.0f, 1, 1, 1);
        this.tailspike2.setRotationPoint(0.0f, 0.0f, 68.0f);
        this.tailspike2.setTextureSize(512, 256);
        this.tailspike2.mirror = true;
        this.setRotation(this.tailspike2, -0.1396263f, 0.1745329f, 0.0f);
        (this.tailspike3 = new ModelRenderer((ModelBase) this, 400, 230)).addBox(1.0f, -1.0f, 2.0f, 1, 1, 1);
        this.tailspike3.setRotationPoint(0.0f, 0.0f, 68.0f);
        this.tailspike3.setTextureSize(512, 256);
        this.tailspike3.mirror = true;
        this.setRotation(this.tailspike3, -0.1396263f, 0.1745329f, 0.0f);
        (this.tailspike4 = new ModelRenderer((ModelBase) this, 400, 230)).addBox(0.0f, -1.0f, 0.0f, 1, 1, 1);
        this.tailspike4.setRotationPoint(-4.0f, 1.0f, 77.0f);
        this.tailspike4.setTextureSize(512, 256);
        this.tailspike4.mirror = true;
        this.setRotation(this.tailspike4, -0.1396263f, -0.1745329f, 0.0f);
        (this.tailspike5 = new ModelRenderer((ModelBase) this, 400, 230)).addBox(-2.0f, -1.0f, 6.0f, 1, 1, 1);
        this.tailspike5.setRotationPoint(0.0f, 0.0f, 68.0f);
        this.tailspike5.setTextureSize(512, 256);
        this.tailspike5.mirror = true;
        this.setRotation(this.tailspike5, -0.1396263f, -0.1745329f, 0.0f);
        (this.tailspike6 = new ModelRenderer((ModelBase) this, 400, 230)).addBox(-2.0f, -1.0f, 2.0f, 1, 1, 1);
        this.tailspike6.setRotationPoint(0.0f, 0.0f, 68.0f);
        this.tailspike6.setTextureSize(512, 256);
        this.tailspike6.mirror = true;
        this.setRotation(this.tailspike6, -0.1396263f, -0.1745329f, 0.0f);
        (this.neck1 = new ModelRenderer((ModelBase) this, 400, 7)).addBox(-4.0f, -4.0f, 0.0f, 8, 8, 8);
        this.neck1.setRotationPoint(0.0f, -4.0f, -5.0f);
        this.neck1.setTextureSize(512, 256);
        this.neck1.mirror = true;
        this.setRotation(this.neck1, 0.0872665f, 0.0f, 0.0f);
        (this.neck2 = new ModelRenderer((ModelBase) this, 375, 10)).addBox(-3.0f, -3.0f, -3.0f, 6, 6, 4);
        this.neck2.setRotationPoint(0.0f, -4.0f, -5.0f);
        this.neck2.setTextureSize(512, 256);
        this.neck2.mirror = true;
        this.setRotation(this.neck2, -0.0523599f, 0.0f, 0.0f);
        (this.neck3 = new ModelRenderer((ModelBase) this, 375, 23)).addBox(-2.0f, -2.0f, -6.0f, 4, 4, 8);
        this.neck3.setRotationPoint(0.0f, -4.0f, -9.0f);
        this.neck3.setTextureSize(512, 256);
        this.neck3.mirror = true;
        this.setRotation(this.neck3, -0.2443461f, 0.0f, 0.0f);
        (this.head1 = new ModelRenderer((ModelBase) this, 123, 3)).addBox(-18.0f, -1.0f, -12.0f, 36, 1, 12);
        this.head1.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.head1.setTextureSize(512, 256);
        this.head1.mirror = true;
        this.setRotation(this.head1, -0.2443461f, 0.0f, 0.0f);
        (this.leye = new ModelRenderer((ModelBase) this, 76, 2)).addBox(18.0f, -1.0f, -13.0f, 3, 3, 15);
        this.leye.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.leye.setTextureSize(512, 256);
        this.leye.mirror = true;
        this.setRotation(this.leye, -0.2443461f, 0.0f, 0.0f);
        (this.reye = new ModelRenderer((ModelBase) this, 32, 2)).addBox(-21.0f, -1.0f, -13.0f, 3, 3, 15);
        this.reye.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.reye.setTextureSize(512, 256);
        this.reye.mirror = true;
        this.setRotation(this.reye, -0.2443461f, 0.0f, 0.0f);
        (this.head2 = new ModelRenderer((ModelBase) this, 140, 18)).addBox(-8.0f, -2.0f, -11.0f, 16, 1, 11);
        this.head2.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.head2.setTextureSize(512, 256);
        this.head2.mirror = true;
        this.setRotation(this.head2, -0.2443461f, 0.0f, 0.0f);
        (this.head3 = new ModelRenderer((ModelBase) this, 143, 32)).addBox(-2.0f, -4.0f, -14.0f, 4, 4, 16);
        this.head3.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.head3.setTextureSize(512, 256);
        this.head3.mirror = true;
        this.setRotation(this.head3, -0.2443461f, 0.0f, 0.0f);
        (this.head4 = new ModelRenderer((ModelBase) this, 152, 55)).addBox(-1.0f, -10.0f, -13.0f, 2, 8, 12);
        this.head4.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.head4.setTextureSize(512, 256);
        this.head4.mirror = true;
        this.setRotation(this.head4, -0.3665191f, 0.0f, 0.0f);
        (this.head5 = new ModelRenderer((ModelBase) this, 154, 77)).addBox(-0.5f, -18.0f, -11.0f, 1, 9, 9);
        this.head5.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.head5.setTextureSize(512, 256);
        this.head5.mirror = true;
        this.setRotation(this.head5, -0.4363323f, 0.0f, 0.0f);
        (this.head6 = new ModelRenderer((ModelBase) this, 160, 97)).addBox(-0.5f, -24.0f, -10.0f, 1, 8, 4);
        this.head6.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.head6.setTextureSize(512, 256);
        this.head6.mirror = true;
        this.setRotation(this.head6, -0.6632251f, 0.0f, 0.0f);
        (this.jaw1 = new ModelRenderer((ModelBase) this, 143, 114)).addBox(-2.0f, 1.0f, -14.0f, 4, 4, 15);
        this.jaw1.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.jaw1.setTextureSize(512, 256);
        this.jaw1.mirror = true;
        this.setRotation(this.jaw1, 0.1919862f, 0.0f, 0.0f);
        (this.jaw2 = new ModelRenderer((ModelBase) this, 150, 149)).addBox(-1.0f, 4.0f, -12.0f, 2, 5, 11);
        this.jaw2.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.jaw2.setTextureSize(512, 256);
        this.jaw2.mirror = true;
        this.setRotation(this.jaw2, 0.2617994f, 0.0f, 0.0f);
        (this.jaw3 = new ModelRenderer((ModelBase) this, 154, 168)).addBox(-0.5f, 8.0f, -10.0f, 1, 4, 8);
        this.jaw3.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.jaw3.setTextureSize(512, 256);
        this.jaw3.mirror = true;
        this.setRotation(this.jaw3, 0.3316126f, 0.0f, 0.0f);
        (this.jaw4 = new ModelRenderer((ModelBase) this, 158, 182)).addBox(-0.5f, 11.0f, -7.0f, 1, 4, 4);
        this.jaw4.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.jaw4.setTextureSize(512, 256);
        this.jaw4.mirror = true;
        this.setRotation(this.jaw4, 0.4014257f, 0.0f, 0.0f);
        (this.tooth1 = new ModelRenderer((ModelBase) this, 0, 0)).addBox(-2.0f, 0.0f, -14.0f, 1, 3, 1);
        this.tooth1.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.tooth1.setTextureSize(512, 256);
        this.tooth1.mirror = true;
        this.setRotation(this.tooth1, -0.2443461f, 0.0f, 0.0f);
        (this.tooth2 = new ModelRenderer((ModelBase) this, 0, 0)).addBox(-0.5f, 0.0f, -14.0f, 1, 2, 1);
        this.tooth2.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.tooth2.setTextureSize(512, 256);
        this.tooth2.mirror = true;
        this.setRotation(this.tooth2, -0.2443461f, 0.0f, 0.0f);
        (this.tooth3 = new ModelRenderer((ModelBase) this, 0, 0)).addBox(1.0f, 0.0f, -14.0f, 1, 3, 1);
        this.tooth3.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.tooth3.setTextureSize(512, 256);
        this.tooth3.mirror = true;
        this.setRotation(this.tooth3, -0.2443461f, 0.0f, 0.0f);
        (this.tooth4 = new ModelRenderer((ModelBase) this, 0, 0)).addBox(-2.0f, 0.0f, -12.0f, 1, 3, 1);
        this.tooth4.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.tooth4.setTextureSize(512, 256);
        this.tooth4.mirror = true;
        this.setRotation(this.tooth4, -0.2443461f, 0.0f, 0.0f);
        (this.tooth5 = new ModelRenderer((ModelBase) this, 0, 0)).addBox(1.0f, 0.0f, -12.0f, 1, 3, 1);
        this.tooth5.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.tooth5.setTextureSize(512, 256);
        this.tooth5.mirror = true;
        this.setRotation(this.tooth5, -0.2443461f, 0.0f, 0.0f);
        (this.jaw5 = new ModelRenderer((ModelBase) this, 151, 135)).addBox(-3.0f, 1.0f, -4.0f, 6, 5, 7);
        this.jaw5.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.jaw5.setTextureSize(512, 256);
        this.jaw5.mirror = true;
        this.setRotation(this.jaw5, 0.1919862f, 0.0f, 0.0f);
        (this.head7 = new ModelRenderer((ModelBase) this, 185, 34)).addBox(-3.0f, -5.0f, -3.0f, 6, 5, 7);
        this.head7.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.head7.setTextureSize(512, 256);
        this.head7.mirror = true;
        this.setRotation(this.head7, -0.2443461f, 0.0f, 0.0f);
        (this.tooth6 = new ModelRenderer((ModelBase) this, 0, 0)).addBox(-2.0f, 0.0f, -10.0f, 1, 2, 1);
        this.tooth6.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.tooth6.setTextureSize(512, 256);
        this.tooth6.mirror = true;
        this.setRotation(this.tooth6, -0.2443461f, 0.0f, 0.0f);
        (this.tooth7 = new ModelRenderer((ModelBase) this, 0, 0)).addBox(1.0f, 0.0f, -10.0f, 1, 2, 1);
        this.tooth7.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.tooth7.setTextureSize(512, 256);
        this.tooth7.mirror = true;
        this.setRotation(this.tooth7, -0.2443461f, 0.0f, 0.0f);
        (this.tooth8 = new ModelRenderer((ModelBase) this, 0, 0)).addBox(-2.0f, 0.0f, -8.0f, 1, 2, 1);
        this.tooth8.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.tooth8.setTextureSize(512, 256);
        this.tooth8.mirror = true;
        this.setRotation(this.tooth8, -0.2443461f, 0.0f, 0.0f);
        (this.tooth9 = new ModelRenderer((ModelBase) this, 0, 0)).addBox(1.0f, 0.0f, -8.0f, 1, 2, 1);
        this.tooth9.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.tooth9.setTextureSize(512, 256);
        this.tooth9.mirror = true;
        this.setRotation(this.tooth9, -0.2443461f, 0.0f, 0.0f);
        (this.tooth10 = new ModelRenderer((ModelBase) this, 0, 0)).addBox(-2.0f, 0.0f, -6.0f, 1, 2, 1);
        this.tooth10.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.tooth10.setTextureSize(512, 256);
        this.tooth10.mirror = true;
        this.setRotation(this.tooth10, -0.2443461f, 0.0f, 0.0f);
        (this.tooth11 = new ModelRenderer((ModelBase) this, 0, 0)).addBox(1.0f, 0.0f, -6.0f, 1, 2, 1);
        this.tooth11.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.tooth11.setTextureSize(512, 256);
        this.tooth11.mirror = true;
        this.setRotation(this.tooth11, -0.2443461f, 0.0f, 0.0f);
        (this.tooth12 = new ModelRenderer((ModelBase) this, 0, 0)).addBox(-2.0f, 0.0f, -4.0f, 1, 1, 1);
        this.tooth12.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.tooth12.setTextureSize(512, 256);
        this.tooth12.mirror = true;
        this.setRotation(this.tooth12, -0.2443461f, 0.0f, 0.0f);
        (this.tooth13 = new ModelRenderer((ModelBase) this, -1, 0)).addBox(1.0f, 0.0f, -4.0f, 1, 1, 1);
        this.tooth13.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.tooth13.setTextureSize(512, 256);
        this.tooth13.mirror = true;
        this.setRotation(this.tooth13, -0.2443461f, 0.0f, 0.0f);
        (this.rightleg1 = new ModelRenderer((ModelBase) this, 250, 10)).addBox(-1.0f, -5.0f, -20.0f, 5, 10, 10);
        this.rightleg1.setRotationPoint(-10.0f, 5.0f, 23.0f);
        this.rightleg1.setTextureSize(512, 256);
        this.rightleg1.mirror = true;
        this.setRotation(this.rightleg1, -0.5934119f, 0.0f, 0.0f);
        (this.rightleg2 = new ModelRenderer((ModelBase) this, 250, 32)).addBox(0.0f, -10.0f, -4.0f, 4, 12, 5);
        this.rightleg2.setRotationPoint(-10.0f, 5.0f, 23.0f);
        this.rightleg2.setTextureSize(512, 256);
        this.rightleg2.mirror = true;
        this.setRotation(this.rightleg2, 0.9773844f, 0.0f, 0.0f);
        (this.tooth14 = new ModelRenderer((ModelBase) this, 0, 0)).addBox(0.5f, -2.0f, -14.0f, 1, 3, 1);
        this.tooth14.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.tooth14.setTextureSize(512, 256);
        this.tooth14.mirror = true;
        this.setRotation(this.tooth14, 0.1919862f, 0.0f, 0.0f);
        (this.tooth15 = new ModelRenderer((ModelBase) this, 0, 0)).addBox(-1.5f, -2.0f, -14.0f, 1, 3, 1);
        this.tooth15.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.tooth15.setTextureSize(512, 256);
        this.tooth15.mirror = true;
        this.setRotation(this.tooth15, 0.1919862f, 0.0f, 0.0f);
        (this.tooth16 = new ModelRenderer((ModelBase) this, 0, 0)).addBox(1.0f, -1.0f, -12.0f, 1, 2, 1);
        this.tooth16.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.tooth16.setTextureSize(512, 256);
        this.tooth16.mirror = true;
        this.setRotation(this.tooth16, 0.1919862f, 0.0f, 0.0f);
        (this.tooth17 = new ModelRenderer((ModelBase) this, 0, 0)).addBox(-2.0f, -1.0f, -12.0f, 1, 2, 1);
        this.tooth17.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.tooth17.setTextureSize(512, 256);
        this.tooth17.mirror = true;
        this.setRotation(this.tooth17, 0.1919862f, 0.0f, 0.0f);
        (this.tooth18 = new ModelRenderer((ModelBase) this, 0, 0)).addBox(1.0f, -1.0f, -10.0f, 1, 2, 1);
        this.tooth18.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.tooth18.setTextureSize(512, 256);
        this.tooth18.mirror = true;
        this.setRotation(this.tooth18, 0.1919862f, 0.0f, 0.0f);
        (this.tooth19 = new ModelRenderer((ModelBase) this, 0, 0)).addBox(-2.0f, -1.0f, -10.0f, 1, 2, 1);
        this.tooth19.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.tooth19.setTextureSize(512, 256);
        this.tooth19.mirror = true;
        this.setRotation(this.tooth19, 0.1919862f, 0.0f, 0.0f);
        (this.tooth20 = new ModelRenderer((ModelBase) this, 0, 0)).addBox(-2.0f, -1.0f, -8.0f, 1, 2, 1);
        this.tooth20.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.tooth20.setTextureSize(512, 256);
        this.tooth20.mirror = true;
        this.setRotation(this.tooth20, 0.1919862f, 0.0f, 0.0f);
        (this.tooth21 = new ModelRenderer((ModelBase) this, 0, 0)).addBox(1.0f, -1.0f, -8.0f, 1, 2, 1);
        this.tooth21.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.tooth21.setTextureSize(512, 256);
        this.tooth21.mirror = true;
        this.setRotation(this.tooth21, 0.1919862f, 0.0f, 0.0f);
        (this.tooth22 = new ModelRenderer((ModelBase) this, 0, 0)).addBox(1.0f, 0.0f, -6.0f, 1, 1, 1);
        this.tooth22.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.tooth22.setTextureSize(512, 256);
        this.tooth22.mirror = true;
        this.setRotation(this.tooth22, 0.1919862f, 0.0f, 0.0f);
        (this.tooth23 = new ModelRenderer((ModelBase) this, 0, 0)).addBox(-2.0f, 0.0f, -6.0f, 1, 1, 1);
        this.tooth23.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.tooth23.setTextureSize(512, 256);
        this.tooth23.mirror = true;
        this.setRotation(this.tooth23, 0.1919862f, 0.0f, 0.0f);
        (this.rightleg3 = new ModelRenderer((ModelBase) this, 250, 52)).addBox(-1.0f, -19.0f, 1.0f, 3, 18, 4);
        this.rightleg3.setRotationPoint(-8.0f, 21.0f, 11.0f);
        this.rightleg3.setTextureSize(512, 256);
        this.rightleg3.mirror = true;
        this.setRotation(this.rightleg3, -0.5235988f, 0.0f, 0.0f);
        (this.llegspike2 = new ModelRenderer((ModelBase) this, 250, 130)).addBox(0.0f, -28.0f, 1.0f, 1, 12, 1);
        this.llegspike2.setRotationPoint(-8.0f, 21.0f, 11.0f);
        this.llegspike2.setTextureSize(512, 256);
        this.llegspike2.mirror = true;
        this.setRotation(this.llegspike2, -0.6981317f, 0.0f, 0.0f);
        (this.rclaw2 = new ModelRenderer((ModelBase) this, 250, 76)).addBox(-1.0f, -1.0f, -6.0f, 3, 4, 13);
        this.rclaw2.setRotationPoint(-8.0f, 21.0f, 11.0f);
        this.rclaw2.setTextureSize(512, 256);
        this.rclaw2.mirror = true;
        this.setRotation(this.rclaw2, 0.0f, 0.0f, 0.0f);
        (this.rclaw4 = new ModelRenderer((ModelBase) this, 250, 123)).addBox(0.0f, 1.0f, -9.0f, 1, 2, 3);
        this.rclaw4.setRotationPoint(-8.0f, 21.0f, 11.0f);
        this.rclaw4.setTextureSize(512, 256);
        this.rclaw4.mirror = true;
        this.setRotation(this.rclaw4, 0.0f, 0.0f, 0.0f);
        (this.rclaw1 = new ModelRenderer((ModelBase) this, 250, 111)).addBox(2.0f, 0.0f, -4.0f, 2, 3, 6);
        this.rclaw1.setRotationPoint(-8.0f, 21.0f, 11.0f);
        this.rclaw1.setTextureSize(512, 256);
        this.rclaw1.mirror = true;
        this.setRotation(this.rclaw1, 0.0f, -0.6632251f, 0.0f);
        (this.rclaw5 = new ModelRenderer((ModelBase) this, 261, 123)).addBox(2.5f, 1.0f, -6.0f, 1, 2, 2);
        this.rclaw5.setRotationPoint(-8.0f, 21.0f, 11.0f);
        this.rclaw5.setTextureSize(512, 256);
        this.rclaw5.mirror = true;
        this.setRotation(this.rclaw5, 0.0f, -0.6632251f, 0.0f);
        (this.rclaw7 = new ModelRenderer((ModelBase) this, 283, 123)).addBox(0.0f, 1.0f, 7.0f, 1, 2, 3);
        this.rclaw7.setRotationPoint(-8.0f, 21.0f, 11.0f);
        this.rclaw7.setTextureSize(512, 256);
        this.rclaw7.mirror = true;
        this.setRotation(this.rclaw7, 0.0f, 0.0f, 0.0f);
        (this.rclaw3 = new ModelRenderer((ModelBase) this, 250, 95)).addBox(-3.0f, 0.0f, -6.0f, 2, 3, 10);
        this.rclaw3.setRotationPoint(-8.0f, 21.0f, 11.0f);
        this.rclaw3.setTextureSize(512, 256);
        this.rclaw3.mirror = true;
        this.setRotation(this.rclaw3, 0.0f, 0.6632251f, 0.0f);
        (this.rclaw6 = new ModelRenderer((ModelBase) this, 270, 123)).addBox(-2.5f, 1.0f, -9.0f, 1, 2, 3);
        this.rclaw6.setRotationPoint(-8.0f, 21.0f, 11.0f);
        this.rclaw6.setTextureSize(512, 256);
        this.rclaw6.mirror = true;
        this.setRotation(this.rclaw6, 0.0f, 0.6632251f, 0.0f);
        (this.wing1 = new ModelRenderer((ModelBase) this, 10, 30)).addBox(-1.0f, -1.0f, -1.0f, 23, 3, 3);
        this.wing1.setRotationPoint(6.0f, -12.0f, 3.0f);
        this.wing1.setTextureSize(512, 256);
        this.wing1.mirror = true;
        this.setRotation(this.wing1, 0.0f, 0.0872665f, -0.1396263f);
        (this.wing2 = new ModelRenderer((ModelBase) this, 10, 40)).addBox(-1.0f, -1.0f, -1.0f, 44, 2, 2);
        this.wing2.setRotationPoint(27.0f, -15.0f, 1.0f);
        this.wing2.setTextureSize(512, 256);
        this.wing2.mirror = true;
        this.setRotation(this.wing2, 0.0f, 0.0f, 0.0f);
        (this.wing3 = new ModelRenderer((ModelBase) this, 10, 50)).addBox(-1.0f, -1.0f, -1.0f, 23, 2, 2);
        this.wing3.setRotationPoint(70.0f, -15.0f, 1.0f);
        this.wing3.setTextureSize(512, 256);
        this.wing3.mirror = true;
        this.setRotation(this.wing3, 0.0f, -0.0872665f, 0.1745329f);
        (this.mem1 = new ModelRenderer((ModelBase) this, 10, 60)).addBox(-2.0f, 0.0f, 0.0f, 24, 1, 21);
        this.mem1.setRotationPoint(6.0f, -12.0f, 3.0f);
        this.mem1.setTextureSize(512, 256);
        this.mem1.mirror = true;
        this.setRotation(this.mem1, 0.0f, 0.0872665f, -0.1396263f);
        (this.mem2 = new ModelRenderer((ModelBase) this, 10, 85)).addBox(0.0f, 0.0f, 0.0f, 43, 1, 21);
        this.mem2.setRotationPoint(27.0f, -15.0f, 1.0f);
        this.mem2.setTextureSize(512, 256);
        this.mem2.mirror = true;
        this.setRotation(this.mem2, 0.0f, 0.0f, 0.0f);
        (this.mem3 = new ModelRenderer((ModelBase) this, 10, 110)).addBox(0.0f, 0.0f, 0.0f, 23, 1, 21);
        this.mem3.setRotationPoint(70.0f, -15.0f, 1.0f);
        this.mem3.setTextureSize(512, 256);
        this.mem3.mirror = true;
        this.setRotation(this.mem3, 0.0f, -0.0872665f, 0.1745329f);
        (this.wingclaw1 = new ModelRenderer((ModelBase) this, 85, 49)).addBox(0.0f, 0.0f, -9.0f, 1, 1, 8);
        this.wingclaw1.setRotationPoint(70.0f, -15.0f, 1.0f);
        this.wingclaw1.setTextureSize(512, 256);
        this.wingclaw1.mirror = true;
        this.setRotation(this.wingclaw1, 0.0f, 0.0f, 0.0f);
        (this.wingclaw2 = new ModelRenderer((ModelBase) this, 67, 50)).addBox(0.0f, 0.0f, -7.0f, 1, 1, 6);
        this.wingclaw2.setRotationPoint(70.0f, -15.0f, 1.0f);
        this.wingclaw2.setTextureSize(512, 256);
        this.wingclaw2.mirror = true;
        this.setRotation(this.wingclaw2, 0.0f, 0.6108652f, 0.0f);
        (this.wingclaw3 = new ModelRenderer((ModelBase) this, 106, 50)).addBox(1.0f, 0.0f, -7.0f, 1, 1, 5);
        this.wingclaw3.setRotationPoint(69.0f, -15.0f, 1.0f);
        this.wingclaw3.setTextureSize(512, 256);
        this.wingclaw3.mirror = true;
        this.setRotation(this.wingclaw3, 0.0f, -0.6108652f, 0.0f);
        (this.lshoulder = new ModelRenderer((ModelBase) this, 370, 40)).addBox(0.0f, 0.0f, 0.0f, 3, 2, 6);
        this.lshoulder.setRotationPoint(3.0f, -13.0f, 1.0f);
        this.lshoulder.setTextureSize(512, 256);
        this.lshoulder.mirror = true;
        this.setRotation(this.lshoulder, 0.0698132f, 0.0f, 0.0f);
        (this.rshoulder = new ModelRenderer((ModelBase) this, 370, 50)).addBox(0.0f, 0.0f, 0.0f, 3, 2, 6);
        this.rshoulder.setRotationPoint(-6.0f, -13.0f, 1.0f);
        this.rshoulder.setTextureSize(512, 256);
        this.rshoulder.mirror = true;
        this.setRotation(this.rshoulder, 0.0698132f, 0.0f, 0.0f);
        (this.rwing1 = new ModelRenderer((ModelBase) this, 10, 140)).addBox(-22.0f, -1.0f, -1.0f, 23, 3, 3);
        this.rwing1.setRotationPoint(-6.0f, -12.0f, 3.0f);
        this.rwing1.setTextureSize(512, 256);
        this.rwing1.mirror = true;
        this.setRotation(this.rwing1, 0.0f, -0.0872665f, 0.1396263f);
        (this.rmem1 = new ModelRenderer((ModelBase) this, 10, 170)).addBox(-22.0f, 0.0f, 0.0f, 24, 1, 21);
        this.rmem1.setRotationPoint(-6.0f, -12.0f, 3.0f);
        this.rmem1.setTextureSize(512, 256);
        this.rmem1.mirror = true;
        this.setRotation(this.rmem1, 0.0f, -0.0872665f, 0.1396263f);
        (this.rwing2 = new ModelRenderer((ModelBase) this, 10, 150)).addBox(-43.0f, -1.0f, -1.0f, 44, 2, 2);
        this.rwing2.setRotationPoint(-27.0f, -15.0f, 1.0f);
        this.rwing2.setTextureSize(512, 256);
        this.rwing2.mirror = true;
        this.setRotation(this.rwing2, 0.0f, 0.0f, 0.0f);
        (this.rmem2 = new ModelRenderer((ModelBase) this, 10, 195)).addBox(-43.0f, 0.0f, 0.0f, 43, 1, 21);
        this.rmem2.setRotationPoint(-27.0f, -15.0f, 1.0f);
        this.rmem2.setTextureSize(512, 256);
        this.rmem2.mirror = true;
        this.setRotation(this.rmem2, 0.0f, 0.0f, 0.0f);
        (this.rwing3 = new ModelRenderer((ModelBase) this, 10, 160)).addBox(-22.0f, -1.0f, -1.0f, 23, 2, 2);
        this.rwing3.setRotationPoint(-70.0f, -15.0f, 1.0f);
        this.rwing3.setTextureSize(512, 256);
        this.rwing3.mirror = true;
        this.setRotation(this.rwing3, 0.0f, 0.0872665f, -0.1745329f);
        (this.rmem3 = new ModelRenderer((ModelBase) this, 10, 220)).addBox(-23.0f, 0.0f, 0.0f, 23, 1, 21);
        this.rmem3.setRotationPoint(-70.0f, -15.0f, 1.0f);
        this.rmem3.setTextureSize(512, 256);
        this.rmem3.mirror = true;
        this.setRotation(this.rmem3, 0.0f, 0.0872665f, -0.1745329f);
        (this.rwingclaw1 = new ModelRenderer((ModelBase) this, 81, 157)).addBox(0.0f, 0.0f, -9.0f, 1, 1, 8);
        this.rwingclaw1.setRotationPoint(-70.0f, -15.0f, 1.0f);
        this.rwingclaw1.setTextureSize(512, 256);
        this.rwingclaw1.mirror = true;
        this.setRotation(this.rwingclaw1, 0.0f, 0.0f, 0.0f);
        (this.rwingclaw2 = new ModelRenderer((ModelBase) this, 64, 160)).addBox(0.0f, 0.0f, -7.0f, 1, 1, 6);
        this.rwingclaw2.setRotationPoint(-70.0f, -15.0f, 1.0f);
        this.rwingclaw2.setTextureSize(512, 256);
        this.rwingclaw2.mirror = true;
        this.setRotation(this.rwingclaw2, 0.0f, -0.6108652f, 0.0f);
        (this.rwingclaw3 = new ModelRenderer((ModelBase) this, 103, 159)).addBox(0.0f, 0.0f, -6.0f, 1, 1, 5);
        this.rwingclaw3.setRotationPoint(-70.0f, -15.0f, 1.0f);
        this.rwingclaw3.setTextureSize(512, 256);
        this.rwingclaw3.mirror = true;
        this.setRotation(this.rwingclaw3, 0.0f, 0.6108652f, 0.0f);
    }

    public void render(final Entity entity, final float f, final float f1, final float f2, float f3, final float f4,
        final float f5) {
        final PitchBlack e = (PitchBlack) entity;
        float newangle = 0.0f;
        final float lspeed = 0.0f;
        RenderInfo r = null;
        float tailspeed = 0.76f;
        float tailamp = 0.25f;
        final float pi4 = 0.7853982f;
        final float pscale = e.getPitchBlackScale();
        super.render(entity, f, f1, f2, f3, f4, f5);
        this.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        r = e.getRenderInfo();
        if (e.getActivity() != 0) {
            newangle = MathHelper.cos(f2 * 0.45f * this.wingspeed / pscale) * 3.1415927f * 0.24f;
        } else {
            newangle = -pi4 + MathHelper.cos(f2 * 0.05f * this.wingspeed / pscale) * 3.1415927f * 0.02f;
        }
        this.wing1.rotateAngleZ = newangle;
        this.mem1.rotateAngleZ = newangle;
        this.wing2.rotateAngleZ = newangle * 5.0f / 3.0f;
        this.wing2.rotationPointY = this.wing1.rotationPointY + (float) Math.sin(this.wing1.rotateAngleZ) * 21.0f;
        this.wing2.rotationPointX = this.wing1.rotationPointX + (float) Math.cos(this.wing1.rotateAngleZ) * 21.0f;
        this.mem2.rotateAngleZ = newangle * 5.0f / 3.0f;
        this.mem2.rotationPointY = this.wing2.rotationPointY;
        this.mem2.rotationPointX = this.wing2.rotationPointX;
        this.wing3.rotateAngleZ = newangle * 2.0f;
        this.wing3.rotationPointY = this.wing2.rotationPointY + (float) Math.sin(this.wing2.rotateAngleZ) * 43.0f;
        this.wing3.rotationPointX = this.wing2.rotationPointX + (float) Math.cos(this.wing2.rotateAngleZ) * 43.0f;
        this.mem3.rotateAngleZ = newangle * 2.0f;
        this.mem3.rotationPointY = this.wing3.rotationPointY;
        this.mem3.rotationPointX = this.wing3.rotationPointX;
        final ModelRenderer wingclaw1 = this.wingclaw1;
        final ModelRenderer wingclaw2 = this.wingclaw2;
        final ModelRenderer wingclaw3 = this.wingclaw3;
        final float rotateAngleZ = newangle * 3.0f / 2.0f;
        wingclaw3.rotateAngleZ = rotateAngleZ;
        wingclaw2.rotateAngleZ = rotateAngleZ;
        wingclaw1.rotateAngleZ = rotateAngleZ;
        final ModelRenderer wingclaw4 = this.wingclaw1;
        final ModelRenderer wingclaw5 = this.wingclaw2;
        final ModelRenderer wingclaw6 = this.wingclaw3;
        final float rotationPointY = this.wing3.rotationPointY;
        wingclaw6.rotationPointY = rotationPointY;
        wingclaw5.rotationPointY = rotationPointY;
        wingclaw4.rotationPointY = rotationPointY;
        final ModelRenderer wingclaw7 = this.wingclaw1;
        final ModelRenderer wingclaw8 = this.wingclaw2;
        final ModelRenderer wingclaw9 = this.wingclaw3;
        final float rotationPointX = this.wing3.rotationPointX;
        wingclaw9.rotationPointX = rotationPointX;
        wingclaw8.rotationPointX = rotationPointX;
        wingclaw7.rotationPointX = rotationPointX;
        this.rwing1.rotateAngleZ = -newangle;
        this.rmem1.rotateAngleZ = -newangle;
        this.rwing2.rotateAngleZ = -newangle * 5.0f / 3.0f;
        this.rwing2.rotationPointY = this.rwing1.rotationPointY - (float) Math.sin(this.rwing1.rotateAngleZ) * 21.0f;
        this.rwing2.rotationPointX = this.rwing1.rotationPointX - (float) Math.cos(this.rwing1.rotateAngleZ) * 21.0f;
        this.rmem2.rotateAngleZ = -newangle * 5.0f / 3.0f;
        this.rmem2.rotationPointY = this.rwing2.rotationPointY;
        this.rmem2.rotationPointX = this.rwing2.rotationPointX;
        this.rwing3.rotateAngleZ = -newangle * 2.0f;
        this.rwing3.rotationPointY = this.rwing2.rotationPointY - (float) Math.sin(this.rwing2.rotateAngleZ) * 43.0f;
        this.rwing3.rotationPointX = this.rwing2.rotationPointX - (float) Math.cos(this.rwing2.rotateAngleZ) * 43.0f;
        this.rmem3.rotateAngleZ = -newangle * 2.0f;
        this.rmem3.rotationPointY = this.rwing3.rotationPointY;
        this.rmem3.rotationPointX = this.rwing3.rotationPointX;
        final ModelRenderer rwingclaw1 = this.rwingclaw1;
        final ModelRenderer rwingclaw2 = this.rwingclaw2;
        final ModelRenderer rwingclaw3 = this.rwingclaw3;
        final float rotateAngleZ2 = -newangle * 3.0f / 2.0f;
        rwingclaw3.rotateAngleZ = rotateAngleZ2;
        rwingclaw2.rotateAngleZ = rotateAngleZ2;
        rwingclaw1.rotateAngleZ = rotateAngleZ2;
        final ModelRenderer rwingclaw4 = this.rwingclaw1;
        final ModelRenderer rwingclaw5 = this.rwingclaw2;
        final ModelRenderer rwingclaw6 = this.rwingclaw3;
        final float rotationPointY2 = this.rwing3.rotationPointY;
        rwingclaw6.rotationPointY = rotationPointY2;
        rwingclaw5.rotationPointY = rotationPointY2;
        rwingclaw4.rotationPointY = rotationPointY2;
        final ModelRenderer rwingclaw7 = this.rwingclaw1;
        final ModelRenderer rwingclaw8 = this.rwingclaw2;
        final ModelRenderer rwingclaw9 = this.rwingclaw3;
        final float rotationPointX2 = this.rwing3.rotationPointX;
        rwingclaw9.rotationPointX = rotationPointX2;
        rwingclaw8.rotationPointX = rotationPointX2;
        rwingclaw7.rotationPointX = rotationPointX2;
        f3 %= 360.0f;
        if (e.getActivity() != 0) {
            f3 = (f3 *= 0.2f);
        } else {
            f3 = (f3 *= 0.55f);
        }
        this.neck3.rotateAngleY = (float) Math.toRadians(f3) * 0.5f;
        final ModelRenderer head1 = this.head1;
        final ModelRenderer head2 = this.head2;
        final ModelRenderer head3 = this.head3;
        final ModelRenderer head4 = this.head4;
        final float n = (float) Math.toRadians(f3);
        head4.rotateAngleY = n;
        head3.rotateAngleY = n;
        head2.rotateAngleY = n;
        head1.rotateAngleY = n;
        final ModelRenderer head5 = this.head5;
        final ModelRenderer head6 = this.head6;
        final ModelRenderer head7 = this.head7;
        final float rotateAngleY = this.head1.rotateAngleY;
        head7.rotateAngleY = rotateAngleY;
        head6.rotateAngleY = rotateAngleY;
        head5.rotateAngleY = rotateAngleY;
        final ModelRenderer jaw1 = this.jaw1;
        final ModelRenderer jaw2 = this.jaw2;
        final ModelRenderer jaw3 = this.jaw3;
        final ModelRenderer jaw4 = this.jaw4;
        final ModelRenderer jaw5 = this.jaw5;
        final float rotateAngleY2 = this.head1.rotateAngleY;
        jaw5.rotateAngleY = rotateAngleY2;
        jaw4.rotateAngleY = rotateAngleY2;
        jaw3.rotateAngleY = rotateAngleY2;
        jaw2.rotateAngleY = rotateAngleY2;
        jaw1.rotateAngleY = rotateAngleY2;
        final ModelRenderer tooth1 = this.tooth1;
        final ModelRenderer tooth2 = this.tooth2;
        final ModelRenderer tooth3 = this.tooth3;
        final ModelRenderer tooth4 = this.tooth4;
        final ModelRenderer tooth5 = this.tooth5;
        final float rotateAngleY3 = this.head1.rotateAngleY;
        tooth5.rotateAngleY = rotateAngleY3;
        tooth4.rotateAngleY = rotateAngleY3;
        tooth3.rotateAngleY = rotateAngleY3;
        tooth2.rotateAngleY = rotateAngleY3;
        tooth1.rotateAngleY = rotateAngleY3;
        final ModelRenderer tooth6 = this.tooth6;
        final ModelRenderer tooth7 = this.tooth7;
        final ModelRenderer tooth8 = this.tooth8;
        final ModelRenderer tooth9 = this.tooth9;
        final ModelRenderer tooth10 = this.tooth10;
        final float rotateAngleY4 = this.head1.rotateAngleY;
        tooth10.rotateAngleY = rotateAngleY4;
        tooth9.rotateAngleY = rotateAngleY4;
        tooth8.rotateAngleY = rotateAngleY4;
        tooth7.rotateAngleY = rotateAngleY4;
        tooth6.rotateAngleY = rotateAngleY4;
        final ModelRenderer tooth11 = this.tooth11;
        final ModelRenderer tooth12 = this.tooth12;
        final ModelRenderer tooth13 = this.tooth13;
        final ModelRenderer tooth14 = this.tooth14;
        final ModelRenderer tooth15 = this.tooth15;
        final float rotateAngleY5 = this.head1.rotateAngleY;
        tooth15.rotateAngleY = rotateAngleY5;
        tooth14.rotateAngleY = rotateAngleY5;
        tooth13.rotateAngleY = rotateAngleY5;
        tooth12.rotateAngleY = rotateAngleY5;
        tooth11.rotateAngleY = rotateAngleY5;
        final ModelRenderer tooth16 = this.tooth16;
        final ModelRenderer tooth17 = this.tooth17;
        final ModelRenderer tooth18 = this.tooth18;
        final ModelRenderer tooth19 = this.tooth19;
        final ModelRenderer tooth20 = this.tooth20;
        final float rotateAngleY6 = this.head1.rotateAngleY;
        tooth20.rotateAngleY = rotateAngleY6;
        tooth19.rotateAngleY = rotateAngleY6;
        tooth18.rotateAngleY = rotateAngleY6;
        tooth17.rotateAngleY = rotateAngleY6;
        tooth16.rotateAngleY = rotateAngleY6;
        final ModelRenderer tooth21 = this.tooth21;
        final ModelRenderer tooth22 = this.tooth22;
        final ModelRenderer tooth23 = this.tooth23;
        final float rotateAngleY7 = this.head1.rotateAngleY;
        tooth23.rotateAngleY = rotateAngleY7;
        tooth22.rotateAngleY = rotateAngleY7;
        tooth21.rotateAngleY = rotateAngleY7;
        final ModelRenderer reye = this.reye;
        final ModelRenderer leye = this.leye;
        final float rotateAngleY8 = this.head1.rotateAngleY;
        leye.rotateAngleY = rotateAngleY8;
        reye.rotateAngleY = rotateAngleY8;
        if (e.getAttacking() != 0) {
            newangle = MathHelper.cos(f2 * 0.85f * this.wingspeed) * 3.1415927f * 0.16f;
            newangle += 0.5f;
        } else {
            newangle = f2 * 0.7f * this.wingspeed % 6.2831855f;
            newangle = Math.abs(newangle);
            if (newangle < r.rf1) {
                r.ri1 = 0;
                if (e.worldObj.rand.nextInt(20) == 1) {
                    final RenderInfo renderInfo = r;
                    renderInfo.ri1 |= 0x1;
                }
            }
            r.rf1 = newangle;
            if (r.ri1 != 0) {
                newangle = MathHelper.sin(f2 * 0.85f * this.wingspeed) * 3.1415927f * 0.16f;
                newangle += 0.5f;
            } else {
                newangle = pi4 / 4.0f;
            }
        }
        final ModelRenderer jaw6 = this.jaw1;
        final ModelRenderer jaw7 = this.jaw2;
        final ModelRenderer jaw8 = this.jaw3;
        final ModelRenderer jaw9 = this.jaw4;
        final ModelRenderer jaw10 = this.jaw5;
        final float rotateAngleX = newangle;
        jaw10.rotateAngleX = rotateAngleX;
        jaw9.rotateAngleX = rotateAngleX;
        jaw8.rotateAngleX = rotateAngleX;
        jaw7.rotateAngleX = rotateAngleX;
        jaw6.rotateAngleX = rotateAngleX;
        final ModelRenderer tooth24 = this.tooth14;
        final ModelRenderer tooth25 = this.tooth15;
        final float n2 = newangle;
        tooth25.rotateAngleX = n2;
        tooth24.rotateAngleX = n2;
        final ModelRenderer tooth26 = this.tooth16;
        final ModelRenderer tooth27 = this.tooth17;
        final ModelRenderer tooth28 = this.tooth18;
        final ModelRenderer tooth29 = this.tooth19;
        final ModelRenderer tooth30 = this.tooth20;
        final float rotateAngleX2 = newangle;
        tooth30.rotateAngleX = rotateAngleX2;
        tooth29.rotateAngleX = rotateAngleX2;
        tooth28.rotateAngleX = rotateAngleX2;
        tooth27.rotateAngleX = rotateAngleX2;
        tooth26.rotateAngleX = rotateAngleX2;
        final ModelRenderer tooth31 = this.tooth21;
        final ModelRenderer tooth32 = this.tooth22;
        final ModelRenderer tooth33 = this.tooth23;
        final float rotateAngleX3 = newangle;
        tooth33.rotateAngleX = rotateAngleX3;
        tooth32.rotateAngleX = rotateAngleX3;
        tooth31.rotateAngleX = rotateAngleX3;
        float clawZ = 7.0f;
        float clawY = 21.0f;
        final float clawZamp = 12.0f * pscale;
        final float clawYamp = 6.0f * pscale;
        if (e.getActivity() == 0) {
            float t1 = 0.0f;
            float t2 = 0.0f;
            if (f1 > 0.001) {
                newangle = MathHelper.cos(f2 * 0.75f * this.wingspeed / pscale);
                t1 = MathHelper.sin(f2 * 0.75f * this.wingspeed / pscale);
            } else {
                newangle = 0.0f;
                t1 = 0.0f;
                t2 = 0.0f;
            }
            if (t1 > 0.0f) {
                t2 = t1 * clawYamp * f1;
                this.lclaw1.rotationPointY = clawY - t2;
            } else {
                this.lclaw1.rotationPointY = clawY;
            }
            this.lclaw1.rotationPointZ = clawZ + clawZamp * newangle * f1;
            final ModelRenderer lclaw2 = this.lclaw2;
            final ModelRenderer lclaw3 = this.lclaw3;
            final ModelRenderer lclaw4 = this.lclaw4;
            final ModelRenderer lclaw5 = this.lclaw5;
            final ModelRenderer lclaw6 = this.lclaw6;
            final ModelRenderer lclaw7 = this.lclaw7;
            final float rotationPointZ = this.lclaw1.rotationPointZ;
            lclaw7.rotationPointZ = rotationPointZ;
            lclaw6.rotationPointZ = rotationPointZ;
            lclaw5.rotationPointZ = rotationPointZ;
            lclaw4.rotationPointZ = rotationPointZ;
            lclaw3.rotationPointZ = rotationPointZ;
            lclaw2.rotationPointZ = rotationPointZ;
            final ModelRenderer lclaw8 = this.lclaw2;
            final ModelRenderer lclaw9 = this.lclaw3;
            final ModelRenderer lclaw10 = this.lclaw4;
            final ModelRenderer lclaw11 = this.lclaw5;
            final ModelRenderer lclaw12 = this.lclaw6;
            final ModelRenderer lclaw13 = this.lclaw7;
            final float rotationPointY3 = this.lclaw1.rotationPointY;
            lclaw13.rotationPointY = rotationPointY3;
            lclaw12.rotationPointY = rotationPointY3;
            lclaw11.rotationPointY = rotationPointY3;
            lclaw10.rotationPointY = rotationPointY3;
            lclaw9.rotationPointY = rotationPointY3;
            lclaw8.rotationPointY = rotationPointY3;
            final ModelRenderer llegspike = this.llegspike;
            final ModelRenderer leftleg3 = this.leftleg3;
            final float rotationPointZ2 = this.lclaw1.rotationPointZ;
            leftleg3.rotationPointZ = rotationPointZ2;
            llegspike.rotationPointZ = rotationPointZ2;
            final ModelRenderer llegspike2 = this.llegspike;
            final ModelRenderer leftleg4 = this.leftleg3;
            final float rotationPointY4 = this.lclaw1.rotationPointY;
            leftleg4.rotationPointY = rotationPointY4;
            llegspike2.rotationPointY = rotationPointY4;
            this.leftleg3.rotateAngleX = -0.61f + newangle * 3.1415927f * 0.18f * f1;
            this.llegspike.rotateAngleX = -0.785f + newangle * 3.1415927f * 0.18f * f1;
            this.leftleg1.rotateAngleX = -0.576f + newangle * 3.1415927f * 0.18f * f1;
            this.leftleg2.rotateAngleX = 0.977f + newangle * 3.1415927f * 0.18f * f1;
            final ModelRenderer leftleg5 = this.leftleg1;
            final ModelRenderer leftleg6 = this.leftleg2;
            final float n3 = this.leftleg3.rotationPointY - (float) Math.cos(this.leftleg3.rotateAngleX) * 17.0f
                + t2 / 2.0f;
            leftleg6.rotationPointY = n3;
            leftleg5.rotationPointY = n3;
            final ModelRenderer leftleg7 = this.leftleg1;
            final ModelRenderer leftleg8 = this.leftleg2;
            final float n4 = this.leftleg3.rotationPointZ - (float) Math.sin(this.leftleg3.rotateAngleX) * 17.0f;
            leftleg8.rotationPointZ = n4;
            leftleg7.rotationPointZ = n4;
            t1 = 0.0f;
            t2 = 0.0f;
            if (f1 > 0.001) {
                newangle = MathHelper.cos(f2 * 0.75f * this.wingspeed / pscale + pi4 * 4.0f);
                t1 = MathHelper.sin(f2 * 0.75f * this.wingspeed / pscale + pi4 * 4.0f);
            } else {
                newangle = 0.0f;
                t1 = 0.0f;
                t2 = 0.0f;
            }
            if (t1 > 0.0f) {
                t2 = t1 * clawYamp * f1;
                this.rclaw1.rotationPointY = clawY - t2;
            } else {
                this.rclaw1.rotationPointY = clawY;
            }
            this.rclaw1.rotationPointZ = clawZ + clawZamp * newangle * f1;
            final ModelRenderer rclaw2 = this.rclaw2;
            final ModelRenderer rclaw3 = this.rclaw3;
            final ModelRenderer rclaw4 = this.rclaw4;
            final ModelRenderer rclaw5 = this.rclaw5;
            final ModelRenderer rclaw6 = this.rclaw6;
            final ModelRenderer rclaw7 = this.rclaw7;
            final float rotationPointZ3 = this.rclaw1.rotationPointZ;
            rclaw7.rotationPointZ = rotationPointZ3;
            rclaw6.rotationPointZ = rotationPointZ3;
            rclaw5.rotationPointZ = rotationPointZ3;
            rclaw4.rotationPointZ = rotationPointZ3;
            rclaw3.rotationPointZ = rotationPointZ3;
            rclaw2.rotationPointZ = rotationPointZ3;
            final ModelRenderer rclaw8 = this.rclaw2;
            final ModelRenderer rclaw9 = this.rclaw3;
            final ModelRenderer rclaw10 = this.rclaw4;
            final ModelRenderer rclaw11 = this.rclaw5;
            final ModelRenderer rclaw12 = this.rclaw6;
            final ModelRenderer rclaw13 = this.rclaw7;
            final float rotationPointY5 = this.rclaw1.rotationPointY;
            rclaw13.rotationPointY = rotationPointY5;
            rclaw12.rotationPointY = rotationPointY5;
            rclaw11.rotationPointY = rotationPointY5;
            rclaw10.rotationPointY = rotationPointY5;
            rclaw9.rotationPointY = rotationPointY5;
            rclaw8.rotationPointY = rotationPointY5;
            final ModelRenderer llegspike3 = this.llegspike2;
            final ModelRenderer rightleg3 = this.rightleg3;
            final float rotationPointZ4 = this.rclaw1.rotationPointZ;
            rightleg3.rotationPointZ = rotationPointZ4;
            llegspike3.rotationPointZ = rotationPointZ4;
            final ModelRenderer llegspike4 = this.llegspike2;
            final ModelRenderer rightleg4 = this.rightleg3;
            final float rotationPointY6 = this.rclaw1.rotationPointY;
            rightleg4.rotationPointY = rotationPointY6;
            llegspike4.rotationPointY = rotationPointY6;
            this.rightleg3.rotateAngleX = -0.61f + newangle * 3.1415927f * 0.18f * f1;
            this.llegspike2.rotateAngleX = -0.785f + newangle * 3.1415927f * 0.18f * f1;
            this.rightleg1.rotateAngleX = -0.576f + newangle * 3.1415927f * 0.18f * f1;
            this.rightleg2.rotateAngleX = 0.977f + newangle * 3.1415927f * 0.18f * f1;
            final ModelRenderer rightleg5 = this.rightleg1;
            final ModelRenderer rightleg6 = this.rightleg2;
            final float n5 = this.rightleg3.rotationPointY - (float) Math.cos(this.rightleg3.rotateAngleX) * 17.0f
                + t2 / 2.0f;
            rightleg6.rotationPointY = n5;
            rightleg5.rotationPointY = n5;
            final ModelRenderer rightleg7 = this.rightleg1;
            final ModelRenderer rightleg8 = this.rightleg2;
            final float n6 = this.rightleg3.rotationPointZ - (float) Math.sin(this.rightleg3.rotateAngleX) * 17.0f;
            rightleg8.rotationPointZ = n6;
            rightleg7.rotationPointZ = n6;
            final ModelRenderer lclaw14 = this.lclaw2;
            final ModelRenderer lclaw15 = this.lclaw3;
            final ModelRenderer lclaw16 = this.lclaw4;
            final ModelRenderer lclaw17 = this.lclaw5;
            final ModelRenderer lclaw18 = this.lclaw6;
            final ModelRenderer lclaw19 = this.lclaw7;
            final ModelRenderer lclaw20 = this.lclaw1;
            final float rotateAngleX4 = 0.0f;
            lclaw20.rotateAngleX = rotateAngleX4;
            lclaw19.rotateAngleX = rotateAngleX4;
            lclaw18.rotateAngleX = rotateAngleX4;
            lclaw17.rotateAngleX = rotateAngleX4;
            lclaw16.rotateAngleX = rotateAngleX4;
            lclaw15.rotateAngleX = rotateAngleX4;
            lclaw14.rotateAngleX = rotateAngleX4;
            final ModelRenderer rclaw14 = this.rclaw2;
            final ModelRenderer rclaw15 = this.rclaw3;
            final ModelRenderer rclaw16 = this.rclaw4;
            final ModelRenderer rclaw17 = this.rclaw5;
            final ModelRenderer rclaw18 = this.rclaw6;
            final ModelRenderer rclaw19 = this.rclaw7;
            final ModelRenderer rclaw20 = this.rclaw1;
            final float rotateAngleX5 = 0.0f;
            rclaw20.rotateAngleX = rotateAngleX5;
            rclaw19.rotateAngleX = rotateAngleX5;
            rclaw18.rotateAngleX = rotateAngleX5;
            rclaw17.rotateAngleX = rotateAngleX5;
            rclaw16.rotateAngleX = rotateAngleX5;
            rclaw15.rotateAngleX = rotateAngleX5;
            rclaw14.rotateAngleX = rotateAngleX5;
        } else {
            clawZ = 7.0f;
            clawY = 9.0f;
            if (e.getAttacking() != 0) {
                newangle = MathHelper.cos(f2 * 0.85f * this.wingspeed / pscale) * 0.2f;
            } else {
                newangle = 0.0f;
            }
            this.lclaw1.rotationPointZ = clawZ;
            this.lclaw1.rotationPointY = clawY + newangle * 30.0f;
            this.lclaw1.rotateAngleX = -0.7f + newangle;
            final ModelRenderer lclaw21 = this.lclaw2;
            final ModelRenderer lclaw22 = this.lclaw3;
            final ModelRenderer lclaw23 = this.lclaw4;
            final ModelRenderer lclaw24 = this.lclaw5;
            final ModelRenderer lclaw25 = this.lclaw6;
            final ModelRenderer lclaw26 = this.lclaw7;
            final float rotationPointZ5 = this.lclaw1.rotationPointZ;
            lclaw26.rotationPointZ = rotationPointZ5;
            lclaw25.rotationPointZ = rotationPointZ5;
            lclaw24.rotationPointZ = rotationPointZ5;
            lclaw23.rotationPointZ = rotationPointZ5;
            lclaw22.rotationPointZ = rotationPointZ5;
            lclaw21.rotationPointZ = rotationPointZ5;
            final ModelRenderer lclaw27 = this.lclaw2;
            final ModelRenderer lclaw28 = this.lclaw3;
            final ModelRenderer lclaw29 = this.lclaw4;
            final ModelRenderer lclaw30 = this.lclaw5;
            final ModelRenderer lclaw31 = this.lclaw6;
            final ModelRenderer lclaw32 = this.lclaw7;
            final float rotationPointY7 = this.lclaw1.rotationPointY;
            lclaw32.rotationPointY = rotationPointY7;
            lclaw31.rotationPointY = rotationPointY7;
            lclaw30.rotationPointY = rotationPointY7;
            lclaw29.rotationPointY = rotationPointY7;
            lclaw28.rotationPointY = rotationPointY7;
            lclaw27.rotationPointY = rotationPointY7;
            final ModelRenderer lclaw33 = this.lclaw2;
            final ModelRenderer lclaw34 = this.lclaw3;
            final ModelRenderer lclaw35 = this.lclaw4;
            final ModelRenderer lclaw36 = this.lclaw5;
            final ModelRenderer lclaw37 = this.lclaw6;
            final ModelRenderer lclaw38 = this.lclaw7;
            final float rotateAngleX6 = this.lclaw1.rotateAngleX;
            lclaw38.rotateAngleX = rotateAngleX6;
            lclaw37.rotateAngleX = rotateAngleX6;
            lclaw36.rotateAngleX = rotateAngleX6;
            lclaw35.rotateAngleX = rotateAngleX6;
            lclaw34.rotateAngleX = rotateAngleX6;
            lclaw33.rotateAngleX = rotateAngleX6;
            final ModelRenderer llegspike5 = this.llegspike;
            final ModelRenderer leftleg9 = this.leftleg3;
            final float rotationPointZ6 = this.lclaw1.rotationPointZ;
            leftleg9.rotationPointZ = rotationPointZ6;
            llegspike5.rotationPointZ = rotationPointZ6;
            final ModelRenderer llegspike6 = this.llegspike;
            final ModelRenderer leftleg10 = this.leftleg3;
            final float rotationPointY8 = this.lclaw1.rotationPointY;
            leftleg10.rotationPointY = rotationPointY8;
            llegspike6.rotationPointY = rotationPointY8;
            this.leftleg3.rotateAngleX = -0.61f + this.lclaw1.rotateAngleX;
            this.llegspike.rotateAngleX = -0.785f + this.lclaw1.rotateAngleX;
            this.leftleg1.rotateAngleX = -0.576f - this.lclaw1.rotateAngleX / 4.0f;
            this.leftleg2.rotateAngleX = 0.977f - this.lclaw1.rotateAngleX / 4.0f;
            final ModelRenderer leftleg11 = this.leftleg1;
            final ModelRenderer leftleg12 = this.leftleg2;
            final float n7 = this.leftleg3.rotationPointY - (float) Math.cos(this.leftleg3.rotateAngleX) * 17.0f;
            leftleg12.rotationPointY = n7;
            leftleg11.rotationPointY = n7;
            final ModelRenderer leftleg13 = this.leftleg1;
            final ModelRenderer leftleg14 = this.leftleg2;
            final float n8 = this.leftleg3.rotationPointZ - (float) Math.sin(this.leftleg3.rotateAngleX) * 17.0f;
            leftleg14.rotationPointZ = n8;
            leftleg13.rotationPointZ = n8;
            this.rclaw1.rotationPointZ = clawZ;
            this.rclaw1.rotationPointY = clawY - newangle * 30.0f;
            this.rclaw1.rotateAngleX = -0.7f - newangle;
            final ModelRenderer rclaw21 = this.rclaw2;
            final ModelRenderer rclaw22 = this.rclaw3;
            final ModelRenderer rclaw23 = this.rclaw4;
            final ModelRenderer rclaw24 = this.rclaw5;
            final ModelRenderer rclaw25 = this.rclaw6;
            final ModelRenderer rclaw26 = this.rclaw7;
            final float rotationPointZ7 = this.rclaw1.rotationPointZ;
            rclaw26.rotationPointZ = rotationPointZ7;
            rclaw25.rotationPointZ = rotationPointZ7;
            rclaw24.rotationPointZ = rotationPointZ7;
            rclaw23.rotationPointZ = rotationPointZ7;
            rclaw22.rotationPointZ = rotationPointZ7;
            rclaw21.rotationPointZ = rotationPointZ7;
            final ModelRenderer rclaw27 = this.rclaw2;
            final ModelRenderer rclaw28 = this.rclaw3;
            final ModelRenderer rclaw29 = this.rclaw4;
            final ModelRenderer rclaw30 = this.rclaw5;
            final ModelRenderer rclaw31 = this.rclaw6;
            final ModelRenderer rclaw32 = this.rclaw7;
            final float rotationPointY9 = this.rclaw1.rotationPointY;
            rclaw32.rotationPointY = rotationPointY9;
            rclaw31.rotationPointY = rotationPointY9;
            rclaw30.rotationPointY = rotationPointY9;
            rclaw29.rotationPointY = rotationPointY9;
            rclaw28.rotationPointY = rotationPointY9;
            rclaw27.rotationPointY = rotationPointY9;
            final ModelRenderer rclaw33 = this.rclaw2;
            final ModelRenderer rclaw34 = this.rclaw3;
            final ModelRenderer rclaw35 = this.rclaw4;
            final ModelRenderer rclaw36 = this.rclaw5;
            final ModelRenderer rclaw37 = this.rclaw6;
            final ModelRenderer rclaw38 = this.rclaw7;
            final float rotateAngleX7 = this.rclaw1.rotateAngleX;
            rclaw38.rotateAngleX = rotateAngleX7;
            rclaw37.rotateAngleX = rotateAngleX7;
            rclaw36.rotateAngleX = rotateAngleX7;
            rclaw35.rotateAngleX = rotateAngleX7;
            rclaw34.rotateAngleX = rotateAngleX7;
            rclaw33.rotateAngleX = rotateAngleX7;
            final ModelRenderer llegspike7 = this.llegspike2;
            final ModelRenderer rightleg9 = this.rightleg3;
            final float rotationPointZ8 = this.rclaw1.rotationPointZ;
            rightleg9.rotationPointZ = rotationPointZ8;
            llegspike7.rotationPointZ = rotationPointZ8;
            final ModelRenderer llegspike8 = this.llegspike2;
            final ModelRenderer rightleg10 = this.rightleg3;
            final float rotationPointY10 = this.rclaw1.rotationPointY;
            rightleg10.rotationPointY = rotationPointY10;
            llegspike8.rotationPointY = rotationPointY10;
            this.rightleg3.rotateAngleX = -0.61f + this.rclaw1.rotateAngleX;
            this.llegspike2.rotateAngleX = -0.785f + this.rclaw1.rotateAngleX;
            this.rightleg1.rotateAngleX = -0.576f - this.rclaw1.rotateAngleX / 4.0f;
            this.rightleg2.rotateAngleX = 0.977f - this.rclaw1.rotateAngleX / 4.0f;
            final ModelRenderer rightleg11 = this.rightleg1;
            final ModelRenderer rightleg12 = this.rightleg2;
            final float n9 = this.rightleg3.rotationPointY - (float) Math.cos(this.rightleg3.rotateAngleX) * 17.0f;
            rightleg12.rotationPointY = n9;
            rightleg11.rotationPointY = n9;
            final ModelRenderer rightleg13 = this.rightleg1;
            final ModelRenderer rightleg14 = this.rightleg2;
            final float n10 = this.rightleg3.rotationPointZ - (float) Math.sin(this.rightleg3.rotateAngleX) * 17.0f;
            rightleg14.rotationPointZ = n10;
            rightleg13.rotationPointZ = n10;
        }
        if (e.getAttacking() != 0) {
            tailspeed = 0.76f / pscale;
            tailamp = 0.25f;
        } else {
            tailspeed = 0.26f / pscale;
            tailamp = 0.08f;
        }
        this.tail1.rotateAngleY = MathHelper.cos(f2 * tailspeed * this.wingspeed) * 3.1415927f * tailamp / 2.0f;
        this.tail2.rotationPointZ = this.tail1.rotationPointZ + (float) Math.cos(this.tail1.rotateAngleY) * 11.0f;
        this.tail2.rotationPointX = this.tail1.rotationPointX - 1.0f
            + (float) Math.sin(this.tail1.rotateAngleY) * 11.0f;
        this.tail2.rotateAngleY = MathHelper.cos(f2 * tailspeed * this.wingspeed - pi4) * 3.1415927f * tailamp;
        this.tail3.rotationPointZ = this.tail2.rotationPointZ + (float) Math.cos(this.tail2.rotateAngleY) * 9.0f;
        this.tail3.rotationPointX = this.tail2.rotationPointX + (float) Math.sin(this.tail2.rotateAngleY) * 9.0f;
        this.tail3.rotateAngleY = MathHelper.cos(f2 * tailspeed * this.wingspeed - 2.0f * pi4) * 3.1415927f * tailamp;
        this.tail4.rotationPointZ = this.tail3.rotationPointZ + (float) Math.cos(this.tail3.rotateAngleY) * 9.0f;
        this.tail4.rotationPointX = this.tail3.rotationPointX + (float) Math.sin(this.tail3.rotateAngleY) * 9.0f;
        this.tail4.rotateAngleY = MathHelper.cos(f2 * tailspeed * this.wingspeed - 3.0f * pi4) * 3.1415927f * tailamp;
        this.tail5.rotationPointZ = this.tail4.rotationPointZ + (float) Math.cos(this.tail4.rotateAngleY) * 9.0f;
        this.tail5.rotationPointX = this.tail4.rotationPointX + (float) Math.sin(this.tail4.rotateAngleY) * 9.0f;
        newangle = MathHelper.cos(f2 * tailspeed * this.wingspeed - 3.0f * pi4) * 3.1415927f * tailamp;
        newangle /= 2.0f;
        this.tail5.rotateAngleY = this.tail4.rotateAngleY + newangle;
        this.tail6.rotationPointZ = this.tail5.rotationPointZ + (float) Math.cos(this.tail5.rotateAngleY) * 9.0f;
        this.tail6.rotationPointX = this.tail5.rotationPointX + (float) Math.sin(this.tail5.rotateAngleY) * 9.0f;
        this.tail6.rotateAngleY = 0.174f + this.tail5.rotateAngleY + newangle;
        final ModelRenderer tailspike2 = this.tailspike2;
        final ModelRenderer tailspike3 = this.tailspike3;
        final float rotationPointZ9 = this.tail6.rotationPointZ;
        tailspike3.rotationPointZ = rotationPointZ9;
        tailspike2.rotationPointZ = rotationPointZ9;
        final ModelRenderer tailspike4 = this.tailspike2;
        final ModelRenderer tailspike5 = this.tailspike3;
        final float rotationPointX3 = this.tail6.rotationPointX;
        tailspike5.rotationPointX = rotationPointX3;
        tailspike4.rotationPointX = rotationPointX3;
        final ModelRenderer tailspike6 = this.tailspike2;
        final ModelRenderer tailspike7 = this.tailspike3;
        final float rotateAngleY9 = this.tail6.rotateAngleY;
        tailspike7.rotateAngleY = rotateAngleY9;
        tailspike6.rotateAngleY = rotateAngleY9;
        this.tail9.rotationPointZ = this.tail6.rotationPointZ + (float) Math.cos(this.tail6.rotateAngleY) * 9.0f;
        this.tail9.rotationPointX = this.tail6.rotationPointX + (float) Math.sin(this.tail6.rotateAngleY) * 9.0f;
        this.tail9.rotateAngleY = this.tail6.rotateAngleY + newangle;
        this.tailspike1.rotationPointZ = this.tail9.rotationPointZ;
        this.tailspike1.rotationPointX = this.tail9.rotationPointX;
        this.tailspike1.rotateAngleY = this.tail9.rotateAngleY;
        this.tailpoint1.rotationPointZ = this.tail9.rotationPointZ + (float) Math.cos(this.tail9.rotateAngleY) * 9.0f;
        this.tailpoint1.rotationPointX = this.tail9.rotationPointX + (float) Math.sin(this.tail9.rotateAngleY) * 9.0f;
        this.tailpoint1.rotateAngleY = this.tail9.rotateAngleY + newangle;
        this.tail7.rotationPointZ = this.tail5.rotationPointZ + (float) Math.cos(this.tail5.rotateAngleY) * 9.0f;
        this.tail7.rotationPointX = this.tail5.rotationPointX + (float) Math.sin(this.tail5.rotateAngleY) * 9.0f;
        this.tail7.rotateAngleY = -0.174f + this.tail5.rotateAngleY + newangle;
        final ModelRenderer tailspike8 = this.tailspike5;
        final ModelRenderer tailspike9 = this.tailspike6;
        final float rotationPointZ10 = this.tail7.rotationPointZ;
        tailspike9.rotationPointZ = rotationPointZ10;
        tailspike8.rotationPointZ = rotationPointZ10;
        final ModelRenderer tailspike10 = this.tailspike5;
        final ModelRenderer tailspike11 = this.tailspike6;
        final float rotationPointX4 = this.tail7.rotationPointX;
        tailspike11.rotationPointX = rotationPointX4;
        tailspike10.rotationPointX = rotationPointX4;
        final ModelRenderer tailspike12 = this.tailspike5;
        final ModelRenderer tailspike13 = this.tailspike6;
        final float rotateAngleY10 = this.tail7.rotateAngleY;
        tailspike13.rotateAngleY = rotateAngleY10;
        tailspike12.rotateAngleY = rotateAngleY10;
        this.tail8.rotationPointZ = this.tail7.rotationPointZ + (float) Math.cos(this.tail7.rotateAngleY) * 9.0f;
        this.tail8.rotationPointX = this.tail7.rotationPointX + (float) Math.sin(this.tail7.rotateAngleY) * 9.0f;
        this.tail8.rotateAngleY = this.tail7.rotateAngleY + newangle;
        this.tailspike4.rotationPointZ = this.tail8.rotationPointZ;
        this.tailspike4.rotationPointX = this.tail8.rotationPointX;
        this.tailspike4.rotateAngleY = this.tail8.rotateAngleY;
        this.tailpoint2.rotationPointZ = this.tail8.rotationPointZ + (float) Math.cos(this.tail8.rotateAngleY) * 9.0f;
        this.tailpoint2.rotationPointX = this.tail8.rotationPointX + (float) Math.sin(this.tail8.rotateAngleY) * 9.0f;
        this.tailpoint2.rotateAngleY = this.tail8.rotateAngleY + newangle;
        e.setRenderInfo(r);
        this.lclaw1.render(f5);
        this.body.render(f5);
        this.leftleg1.render(f5);
        this.tail1.render(f5);
        this.leftleg2.render(f5);
        this.body2.render(f5);
        this.leftleg3.render(f5);
        this.tail2.render(f5);
        this.tail3.render(f5);
        this.lclaw2.render(f5);
        this.lclaw3.render(f5);
        this.lclaw4.render(f5);
        this.lclaw5.render(f5);
        this.lclaw6.render(f5);
        this.lclaw7.render(f5);
        this.tail4.render(f5);
        this.tail5.render(f5);
        this.tail6.render(f5);
        this.tail7.render(f5);
        this.tail8.render(f5);
        this.tail9.render(f5);
        this.tailpoint1.render(f5);
        this.tailpoint2.render(f5);
        this.llegspike.render(f5);
        this.tailspike1.render(f5);
        this.tailspike2.render(f5);
        this.tailspike3.render(f5);
        this.tailspike4.render(f5);
        this.tailspike5.render(f5);
        this.tailspike6.render(f5);
        this.neck1.render(f5);
        this.neck2.render(f5);
        this.neck3.render(f5);
        this.head1.render(f5);
        this.leye.render(f5);
        this.reye.render(f5);
        this.head2.render(f5);
        this.head3.render(f5);
        this.head4.render(f5);
        this.head5.render(f5);
        this.head6.render(f5);
        this.jaw1.render(f5);
        this.jaw2.render(f5);
        this.jaw3.render(f5);
        this.jaw4.render(f5);
        this.tooth1.render(f5);
        this.tooth2.render(f5);
        this.tooth3.render(f5);
        this.tooth4.render(f5);
        this.tooth5.render(f5);
        this.jaw5.render(f5);
        this.head7.render(f5);
        this.tooth6.render(f5);
        this.tooth7.render(f5);
        this.tooth8.render(f5);
        this.tooth9.render(f5);
        this.tooth10.render(f5);
        this.tooth11.render(f5);
        this.tooth12.render(f5);
        this.tooth13.render(f5);
        this.rightleg1.render(f5);
        this.rightleg2.render(f5);
        this.tooth14.render(f5);
        this.tooth15.render(f5);
        this.tooth16.render(f5);
        this.tooth17.render(f5);
        this.tooth18.render(f5);
        this.tooth19.render(f5);
        this.tooth20.render(f5);
        this.tooth21.render(f5);
        this.tooth22.render(f5);
        this.tooth23.render(f5);
        this.rightleg3.render(f5);
        this.llegspike2.render(f5);
        this.rclaw2.render(f5);
        this.rclaw4.render(f5);
        this.rclaw1.render(f5);
        this.rclaw5.render(f5);
        this.rclaw7.render(f5);
        this.rclaw3.render(f5);
        this.rclaw6.render(f5);
        this.wing1.render(f5);
        this.wing2.render(f5);
        this.wing3.render(f5);
        this.mem1.render(f5);
        this.mem2.render(f5);
        this.mem3.render(f5);
        this.wingclaw1.render(f5);
        this.wingclaw2.render(f5);
        this.wingclaw3.render(f5);
        this.lshoulder.render(f5);
        this.rshoulder.render(f5);
        this.rwing1.render(f5);
        this.rmem1.render(f5);
        this.rwing2.render(f5);
        this.rmem2.render(f5);
        this.rwing3.render(f5);
        this.rmem3.render(f5);
        this.rwingclaw1.render(f5);
        this.rwingclaw2.render(f5);
        this.rwingclaw3.render(f5);
    }

    private void setRotation(final ModelRenderer model, final float x, final float y, final float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(final float par1, final float par2, final float par3, final float par4,
        final float par5, final float par6, final Entity par7Entity) {
        super.setRotationAngles(par1, par2, par3, par4, par5, par6, par7Entity);
    }
}
