
package fr.iamacat.dangerzone_iamacatfr.entities.model;

import fr.iamacat.dangerzone_iamacatfr.entities.entity.Godzilla;
import fr.iamacat.dangerzone_iamacatfr.entities.render.RenderInfo;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;


public class ModelGodzilla extends ModelBase {

    private float wingspeed;
    ModelRenderer LToe1;
    ModelRenderer LToe3;
    ModelRenderer LToe2;
    ModelRenderer LToe9;
    ModelRenderer LToe8;
    ModelRenderer LToe7;
    ModelRenderer LToe6;
    ModelRenderer LToe5;
    ModelRenderer LToe4;
    ModelRenderer RToe9;
    ModelRenderer RToe6;
    ModelRenderer RToe5;
    ModelRenderer RToe2;
    ModelRenderer RToe1;
    ModelRenderer RToe4;
    ModelRenderer RToe7;
    ModelRenderer RToe8;
    ModelRenderer RToe3;
    ModelRenderer LThigh;
    ModelRenderer LLowerLeg;
    ModelRenderer LUpperLeg;
    ModelRenderer TailTip;
    ModelRenderer RLegLower;
    ModelRenderer RLegUpper;
    ModelRenderer RThigh;
    ModelRenderer LowerJaw;
    ModelRenderer TailBase;
    ModelRenderer Tail2;
    ModelRenderer Tail3;
    ModelRenderer Tail4;
    ModelRenderer Tail5;
    ModelRenderer Tail6;
    ModelRenderer Tail7;
    ModelRenderer BodyBottom;
    ModelRenderer RLowerArm;
    ModelRenderer BodyCenter;
    ModelRenderer Neck;
    ModelRenderer TopJaw;
    ModelRenderer Head;
    ModelRenderer BodyTop;
    ModelRenderer RShoulder;
    ModelRenderer RThumbTip;
    ModelRenderer RUpperArm;
    ModelRenderer RHand;
    ModelRenderer RThumbBase;
    ModelRenderer R3rdFingerTip;
    ModelRenderer R3rdFingerBase;
    ModelRenderer RIndexTip;
    ModelRenderer RIndexBase;
    ModelRenderer LShoulder;
    ModelRenderer LUpperArm;
    ModelRenderer LLowerArm;
    ModelRenderer LIndexBase;
    ModelRenderer LIndexTip;
    ModelRenderer LHand;
    ModelRenderer LThumbBase;
    ModelRenderer LThumbTip;
    ModelRenderer L3rdFingerTip;
    ModelRenderer L3rdFingerBase;
    ModelRenderer Lspikes1;
    ModelRenderer Rspikes1;
    ModelRenderer Lspike2;
    ModelRenderer Rspike2;
    ModelRenderer Lspike3;
    ModelRenderer Rspike3;
    ModelRenderer Lspike4;
    ModelRenderer Rspike4;
    ModelRenderer Lspike5;
    ModelRenderer Rspike5;
    ModelRenderer Spike6;
    ModelRenderer Spikes7;

    public ModelGodzilla(final float f1) {
        this.wingspeed = 1.0f;
        this.wingspeed = f1;
        this.textureWidth = 1024;
        this.textureHeight = 1024;
        (this.LToe1 = new ModelRenderer((ModelBase) this, 45, 1002)).addBox(-5.0f, -2.0f, -40.0f, 10, 10, 6);
        this.LToe1.setRotationPoint(54.0f, 16.0f, 6.0f);
        this.LToe1.setTextureSize(1024, 1024);
        this.LToe1.mirror = true;
        this.setRotation(this.LToe1, 0.0f, 0.7853982f, 0.0f);
        (this.LToe3 = new ModelRenderer((ModelBase) this, 0, 955)).addBox(-8.0f, -8.0f, -26.0f, 16, 16, 30);
        this.LToe3.setRotationPoint(54.0f, 16.0f, 6.0f);
        this.LToe3.setTextureSize(1024, 1024);
        this.LToe3.mirror = true;
        this.setRotation(this.LToe3, 0.0f, 0.7853982f, 0.0f);
        (this.LToe2 = new ModelRenderer((ModelBase) this, 0, 1002)).addBox(-7.0f, -6.0f, -34.0f, 14, 14, 8);
        this.LToe2.setRotationPoint(54.0f, 16.0f, 6.0f);
        this.LToe2.setTextureSize(1024, 1024);
        this.LToe2.mirror = true;
        this.setRotation(this.LToe2, 0.0f, 0.7853982f, 0.0f);
        (this.LToe9 = new ModelRenderer((ModelBase) this, 0, 955)).addBox(-8.0f, -8.0f, -26.0f, 16, 16, 30);
        this.LToe9.setRotationPoint(54.0f, 16.0f, 6.0f);
        this.LToe9.setTextureSize(1024, 1024);
        this.LToe9.mirror = true;
        this.setRotation(this.LToe9, 0.0f, -0.7853982f, 0.0f);
        (this.LToe8 = new ModelRenderer((ModelBase) this, 0, 1002)).addBox(-7.0f, -6.0f, -34.0f, 14, 14, 8);
        this.LToe8.setRotationPoint(54.0f, 16.0f, 6.0f);
        this.LToe8.setTextureSize(1024, 1024);
        this.LToe8.mirror = true;
        this.setRotation(this.LToe8, 0.0f, -0.7853982f, 0.0f);
        (this.LToe7 = new ModelRenderer((ModelBase) this, 45, 1002)).addBox(-5.0f, -2.0f, -40.0f, 10, 10, 6);
        this.LToe7.setRotationPoint(54.0f, 16.0f, 6.0f);
        this.LToe7.setTextureSize(1024, 1024);
        this.LToe7.mirror = true;
        this.setRotation(this.LToe7, 0.0f, -0.7853982f, 0.0f);
        (this.LToe6 = new ModelRenderer((ModelBase) this, 92, 955)).addBox(-8.0f, -8.0f, -26.0f, 16, 16, 36);
        this.LToe6.setRotationPoint(54.0f, 16.0f, 6.0f);
        this.LToe6.setTextureSize(1024, 1024);
        this.LToe6.mirror = true;
        this.setRotation(this.LToe6, 0.0f, 0.0f, 0.0f);
        (this.LToe5 = new ModelRenderer((ModelBase) this, 0, 1002)).addBox(-7.0f, -6.0f, -34.0f, 14, 14, 8);
        this.LToe5.setRotationPoint(54.0f, 16.0f, 6.0f);
        this.LToe5.setTextureSize(1024, 1024);
        this.LToe5.mirror = true;
        this.setRotation(this.LToe5, 0.0f, 0.0f, 0.0f);
        (this.LToe4 = new ModelRenderer((ModelBase) this, 45, 1002)).addBox(-5.0f, -2.0f, -40.0f, 10, 10, 6);
        this.LToe4.setRotationPoint(54.0f, 16.0f, 6.0f);
        this.LToe4.setTextureSize(1024, 1024);
        this.LToe4.mirror = true;
        this.setRotation(this.LToe4, 0.0f, 0.0f, 0.0f);
        (this.RToe9 = new ModelRenderer((ModelBase) this, 0, 955)).addBox(-8.0f, -8.0f, -26.0f, 16, 16, 30);
        this.RToe9.setRotationPoint(-54.0f, 16.0f, 6.0f);
        this.RToe9.setTextureSize(1024, 1024);
        this.RToe9.mirror = true;
        this.setRotation(this.RToe9, 0.0f, 0.7853982f, 0.0f);
        (this.RToe6 = new ModelRenderer((ModelBase) this, 92, 955)).addBox(-8.0f, -8.0f, -26.0f, 16, 16, 36);
        this.RToe6.setRotationPoint(-54.0f, 16.0f, 6.0f);
        this.RToe6.setTextureSize(1024, 1024);
        this.RToe6.mirror = true;
        this.setRotation(this.RToe6, 0.0f, 0.0f, 0.0f);
        (this.RToe5 = new ModelRenderer((ModelBase) this, 0, 1002)).addBox(-7.0f, -6.0f, -34.0f, 14, 14, 8);
        this.RToe5.setRotationPoint(-54.0f, 16.0f, 6.0f);
        this.RToe5.setTextureSize(1024, 1024);
        this.RToe5.mirror = true;
        this.setRotation(this.RToe5, 0.0f, 0.0f, 0.0f);
        (this.RToe2 = new ModelRenderer((ModelBase) this, 0, 1002)).addBox(-7.0f, -6.0f, -34.0f, 14, 14, 8);
        this.RToe2.setRotationPoint(-54.0f, 16.0f, 6.0f);
        this.RToe2.setTextureSize(1024, 1024);
        this.RToe2.mirror = true;
        this.setRotation(this.RToe2, 0.0f, -0.7853982f, 0.0f);
        (this.RToe1 = new ModelRenderer((ModelBase) this, 45, 1002)).addBox(-5.0f, -2.0f, -40.0f, 10, 10, 6);
        this.RToe1.setRotationPoint(-54.0f, 16.0f, 6.0f);
        this.RToe1.setTextureSize(1024, 1024);
        this.RToe1.mirror = true;
        this.setRotation(this.RToe1, 0.0f, -0.7853982f, 0.0f);
        (this.RToe4 = new ModelRenderer((ModelBase) this, 45, 1002)).addBox(-5.0f, -2.0f, -40.0f, 10, 10, 6);
        this.RToe4.setRotationPoint(-54.0f, 16.0f, 6.0f);
        this.RToe4.setTextureSize(1024, 1024);
        this.RToe4.mirror = true;
        this.setRotation(this.RToe4, 0.0f, 0.0f, 0.0f);
        (this.RToe7 = new ModelRenderer((ModelBase) this, 45, 1002)).addBox(-5.0f, -2.0f, -40.0f, 10, 10, 6);
        this.RToe7.setRotationPoint(-54.0f, 16.0f, 6.0f);
        this.RToe7.setTextureSize(1024, 1024);
        this.RToe7.mirror = true;
        this.setRotation(this.RToe7, 0.0f, 0.7853982f, 0.0f);
        (this.RToe8 = new ModelRenderer((ModelBase) this, 0, 1002)).addBox(-7.0f, -6.0f, -34.0f, 14, 14, 8);
        this.RToe8.setRotationPoint(-54.0f, 16.0f, 6.0f);
        this.RToe8.setTextureSize(1024, 1024);
        this.RToe8.mirror = true;
        this.setRotation(this.RToe8, 0.0f, 0.7853982f, 0.0f);
        (this.RToe3 = new ModelRenderer((ModelBase) this, 0, 955)).addBox(-8.0f, -8.0f, -26.0f, 16, 16, 30);
        this.RToe3.setRotationPoint(-54.0f, 16.0f, 6.0f);
        this.RToe3.setTextureSize(1024, 1024);
        this.RToe3.mirror = true;
        this.setRotation(this.RToe3, 0.0f, -0.7853982f, 0.0f);
        (this.LThigh = new ModelRenderer((ModelBase) this, 192, 350)).addBox(0.0f, -14.0f, -21.0f, 28, 28, 42);
        this.LThigh.setRotationPoint(40.0f, -91.0f, 2.0f);
        this.LThigh.setTextureSize(1024, 1024);
        this.LThigh.mirror = true;
        this.setRotation(this.LThigh, -0.5585054f, 0.0f, 0.0f);
        (this.LLowerLeg = new ModelRenderer((ModelBase) this, 202, 556)).addBox(-15.0f, -62.0f, -15.0f, 30, 62, 30);
        this.LLowerLeg.setRotationPoint(54.0f, 14.0f, 6.0f);
        this.LLowerLeg.setTextureSize(1024, 1024);
        this.LLowerLeg.mirror = true;
        this.setRotation(this.LLowerLeg, 0.1745329f, -0.1308997f, 0.0f);
        (this.LUpperLeg = new ModelRenderer((ModelBase) this, 152, 420)).addBox(-16.0f, -52.0f, -16.0f, 32, 52, 32);
        this.LUpperLeg.setRotationPoint(56.0f, -36.0f, -5.0f);
        this.LUpperLeg.setTextureSize(1024, 1024);
        this.LUpperLeg.mirror = true;
        this.setRotation(this.LUpperLeg, -0.1745329f, -0.3926991f, -0.0872665f);
        (this.TailTip = new ModelRenderer((ModelBase) this, 0, 694)).addBox(-6.0f, 0.0f, -5.0f, 12, 21, 10);
        this.TailTip.setRotationPoint(0.0f, 18.0f, 203.0f);
        this.TailTip.setTextureSize(1024, 1024);
        this.TailTip.mirror = true;
        this.setRotation(this.TailTip, 1.53589f, 0.0f, 0.0f);
        (this.RLegLower = new ModelRenderer((ModelBase) this, 200, 646)).addBox(-15.0f, -62.0f, -15.0f, 30, 62, 30);
        this.RLegLower.setRotationPoint(-54.0f, 16.0f, 6.0f);
        this.RLegLower.setTextureSize(1024, 1024);
        this.RLegLower.mirror = true;
        this.setRotation(this.RLegLower, 0.1745329f, 0.1308997f, 0.0f);
        (this.RLegUpper = new ModelRenderer((ModelBase) this, 152, 420)).addBox(-16.0f, -52.0f, -16.0f, 32, 52, 32);
        this.RLegUpper.setRotationPoint(-56.0f, -36.0f, -5.0f);
        this.RLegUpper.setTextureSize(1024, 1024);
        this.RLegUpper.mirror = true;
        this.setRotation(this.RLegUpper, -0.1745329f, 0.3926991f, 0.0872665f);
        (this.RThigh = new ModelRenderer((ModelBase) this, 192, 350)).addBox(-28.0f, -14.0f, -21.0f, 28, 28, 42);
        this.RThigh.setRotationPoint(-40.0f, -91.0f, 2.0f);
        this.RThigh.setTextureSize(1024, 1024);
        this.RThigh.mirror = true;
        this.setRotation(this.RThigh, -0.5585054f, 0.0f, 0.0f);
        (this.LowerJaw = new ModelRenderer((ModelBase) this, 272, 0)).addBox(-13.0f, -5.0f, -50.0f, 26, 11, 50);
        this.LowerJaw.setRotationPoint(0.0f, -142.0f, -109.0f);
        this.LowerJaw.setTextureSize(1024, 1024);
        this.LowerJaw.mirror = true;
        this.setRotation(this.LowerJaw, 0.5235988f, 0.0f, 0.0f);
        (this.TailBase = new ModelRenderer((ModelBase) this, 0, 240)).addBox(-32.0f, 0.0f, -29.0f, 64, 40, 58);
        this.TailBase.setRotationPoint(0.0f, -73.0f, 26.0f);
        this.TailBase.setTextureSize(1024, 1024);
        this.TailBase.mirror = true;
        this.setRotation(this.TailBase, 0.7853982f, 0.0f, 0.0f);
        (this.Tail2 = new ModelRenderer((ModelBase) this, 0, 338)).addBox(-25.0f, 0.0f, -23.0f, 50, 36, 46);
        this.Tail2.setRotationPoint(0.0f, -48.0f, 48.0f);
        this.Tail2.setTextureSize(1024, 1024);
        this.Tail2.mirror = true;
        this.setRotation(this.Tail2, 0.6981317f, 0.0f, 0.0f);
        (this.Tail3 = new ModelRenderer((ModelBase) this, 0, 420)).addBox(-20.0f, 0.0f, -18.0f, 40, 36, 36);
        this.Tail3.setRotationPoint(0.0f, -24.0f, 66.0f);
        this.Tail3.setTextureSize(1024, 1024);
        this.Tail3.mirror = true;
        this.setRotation(this.Tail3, 0.8726646f, 0.0f, 0.0f);
        (this.Tail4 = new ModelRenderer((ModelBase) this, 0, 492)).addBox(-16.0f, 0.0f, -14.0f, 32, 42, 28);
        this.Tail4.setRotationPoint(0.0f, -3.0f, 87.0f);
        this.Tail4.setTextureSize(1024, 1024);
        this.Tail4.mirror = true;
        this.setRotation(this.Tail4, 1.134464f, 0.0f, 0.0f);
        (this.Tail5 = new ModelRenderer((ModelBase) this, 0, 556)).addBox(-13.0f, 0.0f, -11.0f, 26, 42, 22);
        this.Tail5.setRotationPoint(0.0f, 12.0f, 116.0f);
        this.Tail5.setTextureSize(1024, 1024);
        this.Tail5.mirror = true;
        this.setRotation(this.Tail5, 1.53589f, 0.0f, 0.0f);
        (this.Tail6 = new ModelRenderer((ModelBase) this, 0, 614)).addBox(-10.0f, 0.0f, -9.0f, 20, 32, 18);
        this.Tail6.setRotationPoint(0.0f, 14.0f, 154.0f);
        this.Tail6.setTextureSize(1024, 1024);
        this.Tail6.mirror = true;
        this.setRotation(this.Tail6, 1.53589f, 0.0f, 0.0f);
        (this.Tail7 = new ModelRenderer((ModelBase) this, 0, 658)).addBox(-8.0f, 0.0f, -7.0f, 16, 22, 14);
        this.Tail7.setRotationPoint(0.0f, 16.0f, 185.0f);
        this.Tail7.setTextureSize(1024, 1024);
        this.Tail7.mirror = true;
        this.setRotation(this.Tail7, 1.53589f, 0.0f, 0.0f);
        (this.BodyBottom = new ModelRenderer((ModelBase) this, 0, 104)).addBox(-40.0f, 0.0f, -36.0f, 80, 64, 72);
        this.BodyBottom.setRotationPoint(0.0f, -112.0f, -20.0f);
        this.BodyBottom.setTextureSize(1024, 1024);
        this.BodyBottom.mirror = true;
        this.setRotation(this.BodyBottom, 0.8726646f, 0.0f, 0.0f);
        (this.RLowerArm = new ModelRenderer((ModelBase) this, 245, 240)).addBox(-48.0f, -11.0f, -11.0f, 48, 22, 22);
        this.RLowerArm.setRotationPoint(-80.0f, -115.0f, -61.0f);
        this.RLowerArm.setTextureSize(1024, 1024);
        this.RLowerArm.mirror = true;
        this.setRotation(this.RLowerArm, 0.0f, -0.7853982f, -0.2617994f);
        (this.BodyCenter = new ModelRenderer((ModelBase) this, 0, 0)).addBox(-36.0f, -32.0f, -32.0f, 72, 40, 64);
        this.BodyCenter.setRotationPoint(0.0f, -112.0f, -20.0f);
        this.BodyCenter.setTextureSize(1024, 1024);
        this.BodyCenter.mirror = true;
        this.setRotation(this.BodyCenter, 1.134464f, 0.0f, 0.0f);
        (this.Neck = new ModelRenderer((ModelBase) this, 0, 720)).addBox(-23.0f, -23.0f, -32.0f, 46, 46, 32);
        this.Neck.setRotationPoint(0.0f, -144.0f, -71.0f);
        this.Neck.setTextureSize(1024, 1024);
        this.Neck.mirror = true;
        this.setRotation(this.Neck, -0.0698132f, 0.0f, 0.0f);
        (this.TopJaw = new ModelRenderer((ModelBase) this, 0, 892)).addBox(-14.0f, -8.0f, -73.0f, 28, 26, 33);
        this.TopJaw.setRotationPoint(0.0f, -156.0f, -98.0f);
        this.TopJaw.setTextureSize(1024, 1024);
        this.TopJaw.mirror = true;
        this.setRotation(this.TopJaw, 0.0872665f, 0.0f, 0.0f);
        (this.Head = new ModelRenderer((ModelBase) this, 0, 808)).addBox(-17.0f, -18.0f, -40.0f, 34, 36, 40);
        this.Head.setRotationPoint(0.0f, -156.0f, -98.0f);
        this.Head.setTextureSize(1024, 1024);
        this.Head.mirror = true;
        this.setRotation(this.Head, 0.0872665f, 0.0f, 0.0f);
        (this.BodyTop = new ModelRenderer((ModelBase) this, 0, 0)).addBox(-36.0f, -32.0f, -32.0f, 72, 40, 64);
        this.BodyTop.setRotationPoint(0.0f, -126.0f, -50.0f);
        this.BodyTop.setTextureSize(1024, 1024);
        this.BodyTop.mirror = true;
        this.setRotation(this.BodyTop, 1.308997f, 0.0f, 0.0f);
        (this.RShoulder = new ModelRenderer((ModelBase) this, 304, 96)).addBox(-16.0f, -32.0f, -32.0f, 16, 42, 46);
        this.RShoulder.setRotationPoint(-36.0f, -130.0f, -42.0f);
        this.RShoulder.setTextureSize(1024, 1024);
        this.RShoulder.mirror = true;
        this.setRotation(this.RShoulder, 1.308997f, 0.0f, 0.0f);
        (this.RThumbTip = new ModelRenderer((ModelBase) this, 422, 18)).addBox(5.0f, 1.0f, -43.0f, 8, 8, 12);
        this.RThumbTip.setRotationPoint(-115.0f, -100.0f, -99.0f);
        this.RThumbTip.setTextureSize(1024, 1024);
        this.RThumbTip.mirror = true;
        this.setRotation(this.RThumbTip, 0.0f, 0.0f, 0.0f);
        (this.RUpperArm = new ModelRenderer((ModelBase) this, 304, 184)).addBox(-54.0f, -13.0f, -13.0f, 54, 26, 26);
        this.RUpperArm.setRotationPoint(-38.0f, -130.0f, -52.0f);
        this.RUpperArm.setTextureSize(1024, 1024);
        this.RUpperArm.mirror = true;
        this.setRotation(this.RUpperArm, 0.0f, -0.2617994f, -0.3490659f);
        (this.RHand = new ModelRenderer((ModelBase) this, 245, 292)).addBox(-13.0f, -13.0f, -13.0f, 26, 26, 26);
        this.RHand.setRotationPoint(-115.0f, -100.0f, -99.0f);
        this.RHand.setTextureSize(1024, 1024);
        this.RHand.mirror = true;
        this.setRotation(this.RHand, -1.071467f, 2.007129f, 0.1745329f);
        (this.RThumbBase = new ModelRenderer((ModelBase) this, 424, 57)).addBox(2.0f, 1.0f, -32.0f, 8, 8, 20);
        this.RThumbBase.setRotationPoint(-115.0f, -100.0f, -99.0f);
        this.RThumbBase.setTextureSize(1024, 1024);
        this.RThumbBase.mirror = true;
        this.setRotation(this.RThumbBase, 0.0f, -0.1047198f, 0.0f);
        (this.R3rdFingerTip = new ModelRenderer((ModelBase) this, 422, 18)).addBox(-10.0f, 0.0f, -41.0f, 8, 8, 12);
        this.R3rdFingerTip.setRotationPoint(-115.0f, -100.0f, -99.0f);
        this.R3rdFingerTip.setTextureSize(1024, 1024);
        this.R3rdFingerTip.mirror = true;
        this.setRotation(this.R3rdFingerTip, 0.0f, 0.6806784f, 0.0f);
        (this.R3rdFingerBase = new ModelRenderer((ModelBase) this, 424, 57)).addBox(-11.0f, -3.0f, -30.0f, 8, 8, 20);
        this.R3rdFingerBase.setRotationPoint(-115.0f, -100.0f, -99.0f);
        this.R3rdFingerBase.setTextureSize(1024, 1024);
        this.R3rdFingerBase.mirror = true;
        this.setRotation(this.R3rdFingerBase, 0.122173f, 0.6457718f, 0.0f);
        (this.RIndexTip = new ModelRenderer((ModelBase) this, 422, 18)).addBox(-4.0f, -12.0f, -43.0f, 8, 8, 12);
        this.RIndexTip.setRotationPoint(-115.0f, -100.0f, -99.0f);
        this.RIndexTip.setTextureSize(1024, 1024);
        this.RIndexTip.mirror = true;
        this.setRotation(this.RIndexTip, -0.2094395f, 0.1745329f, 0.0f);
        (this.RIndexBase = new ModelRenderer((ModelBase) this, 424, 57)).addBox(-4.0f, -9.0f, -34.0f, 8, 8, 20);
        this.RIndexBase.setRotationPoint(-115.0f, -100.0f, -99.0f);
        this.RIndexBase.setTextureSize(1024, 1024);
        this.RIndexBase.mirror = true;
        this.setRotation(this.RIndexBase, -0.2792527f, 0.1570796f, 0.0f);
        (this.LShoulder = new ModelRenderer((ModelBase) this, 304, 96)).addBox(0.0f, -32.0f, -32.0f, 16, 42, 46);
        this.LShoulder.setRotationPoint(36.0f, -130.0f, -42.0f);
        this.LShoulder.setTextureSize(1024, 1024);
        this.LShoulder.mirror = true;
        this.setRotation(this.LShoulder, 1.308997f, 0.0f, 0.0f);
        (this.LUpperArm = new ModelRenderer((ModelBase) this, 304, 184)).addBox(0.0f, -13.0f, -13.0f, 54, 26, 26);
        this.LUpperArm.setRotationPoint(38.0f, -130.0f, -52.0f);
        this.LUpperArm.setTextureSize(1024, 1024);
        this.LUpperArm.mirror = true;
        this.setRotation(this.LUpperArm, 0.0f, 0.296706f, 0.3490659f);
        (this.LLowerArm = new ModelRenderer((ModelBase) this, 245, 240)).addBox(0.0f, -11.0f, -11.0f, 48, 22, 22);
        this.LLowerArm.setRotationPoint(80.0f, -115.0f, -61.0f);
        this.LLowerArm.setTextureSize(1024, 1024);
        this.LLowerArm.mirror = true;
        this.setRotation(this.LLowerArm, 0.0f, 0.7853982f, 0.2617994f);
        (this.LIndexBase = new ModelRenderer((ModelBase) this, 424, 57)).addBox(-4.0f, -13.0f, -32.0f, 8, 8, 20);
        this.LIndexBase.setRotationPoint(115.0f, -100.0f, -99.0f);
        this.LIndexBase.setTextureSize(1024, 1024);
        this.LIndexBase.mirror = true;
        this.setRotation(this.LIndexBase, -0.1570796f, -0.1396263f, 0.0f);
        (this.LIndexTip = new ModelRenderer((ModelBase) this, 422, 18)).addBox(-1.0f, -18.0f, -41.0f, 8, 8, 12);
        this.LIndexTip.setRotationPoint(115.0f, -100.0f, -99.0f);
        this.LIndexTip.setTextureSize(1024, 1024);
        this.LIndexTip.mirror = true;
        this.setRotation(this.LIndexTip, 0.0f, -0.0349066f, 0.0f);
        (this.LHand = new ModelRenderer((ModelBase) this, 245, 292)).addBox(-13.0f, -13.0f, -13.0f, 26, 26, 26);
        this.LHand.setRotationPoint(115.0f, -100.0f, -99.0f);
        this.LHand.setTextureSize(1024, 1024);
        this.LHand.mirror = true;
        this.setRotation(this.LHand, 0.9599311f, 1.308997f, 0.1745329f);
        (this.LThumbBase = new ModelRenderer((ModelBase) this, 424, 57)).addBox(-8.0f, -2.0f, -32.0f, 8, 8, 20);
        this.LThumbBase.setRotationPoint(115.0f, -100.0f, -98.0f);
        this.LThumbBase.setTextureSize(1024, 1024);
        this.LThumbBase.mirror = true;
        this.setRotation(this.LThumbBase, 0.1396263f, 0.2617994f, 0.0f);
        (this.LThumbTip = new ModelRenderer((ModelBase) this, 422, 18)).addBox(-12.0f, 2.0f, -40.0f, 8, 8, 12);
        this.LThumbTip.setRotationPoint(115.0f, -100.0f, -99.0f);
        this.LThumbTip.setTextureSize(1024, 1024);
        this.LThumbTip.mirror = true;
        this.setRotation(this.LThumbTip, 0.0f, 0.1396263f, 0.0f);
        (this.L3rdFingerTip = new ModelRenderer((ModelBase) this, 422, 18)).addBox(9.0f, 2.0f, -42.0f, 8, 8, 12);
        this.L3rdFingerTip.setRotationPoint(115.0f, -100.0f, -99.0f);
        this.L3rdFingerTip.setTextureSize(1024, 1024);
        this.L3rdFingerTip.mirror = true;
        this.setRotation(this.L3rdFingerTip, 0.0349066f, -0.3316126f, 0.0f);
        (this.L3rdFingerBase = new ModelRenderer((ModelBase) this, 424, 57)).addBox(4.0f, -5.0f, -33.0f, 8, 8, 20);
        this.L3rdFingerBase.setRotationPoint(115.0f, -100.0f, -99.0f);
        this.L3rdFingerBase.setTextureSize(1024, 1024);
        this.L3rdFingerBase.mirror = true;
        this.setRotation(this.L3rdFingerBase, 0.2617994f, -0.4712389f, 0.0f);
        (this.Lspikes1 = new ModelRenderer((ModelBase) this, 500, 0)).addBox(0.0f, -10.0f, 0.0f, 0, 10, 11);
        this.Lspikes1.setRotationPoint(5.0f, -168.0f, -86.0f);
        this.Lspikes1.setTextureSize(1024, 1024);
        this.Lspikes1.mirror = true;
        this.setRotation(this.Lspikes1, -0.0872665f, 0.0f, -0.0174533f);
        (this.Rspikes1 = new ModelRenderer((ModelBase) this, 500, 0)).addBox(0.0f, -10.0f, 0.0f, 0, 10, 11);
        this.Rspikes1.setRotationPoint(-5.0f, -168.0f, -86.0f);
        this.Rspikes1.setTextureSize(1024, 1024);
        this.Rspikes1.mirror = true;
        this.setRotation(this.Rspikes1, -0.0872665f, 0.0f, -0.0174533f);
        (this.Lspike2 = new ModelRenderer((ModelBase) this, 500, 30)).addBox(0.0f, -25.0f, 0.0f, 0, 25, 21);
        this.Lspike2.setRotationPoint(10.0f, -162.0f, -63.0f);
        this.Lspike2.setTextureSize(1024, 1024);
        this.Lspike2.mirror = true;
        this.setRotation(this.Lspike2, -0.2617994f, 0.0f, -0.0174533f);
        (this.Rspike2 = new ModelRenderer((ModelBase) this, 500, 30)).addBox(0.0f, -25.0f, 0.0f, 0, 25, 21);
        this.Rspike2.setRotationPoint(-10.0f, -162.0f, -63.0f);
        this.Rspike2.setTextureSize(1024, 1024);
        this.Rspike2.mirror = true;
        this.setRotation(this.Rspike2, -0.2617994f, 0.0f, -0.0174533f);
        (this.Lspike3 = new ModelRenderer((ModelBase) this, 500, 80)).addBox(0.0f, -45.0f, 0.0f, 0, 45, 34);
        this.Lspike3.setRotationPoint(14.0f, -153.0f, -32.0f);
        this.Lspike3.setTextureSize(1024, 1024);
        this.Lspike3.mirror = true;
        this.setRotation(this.Lspike3, -0.4363323f, 0.0f, -0.0174533f);
        (this.Rspike3 = new ModelRenderer((ModelBase) this, 500, 80)).addBox(0.0f, -45.0f, 0.0f, 0, 45, 34);
        this.Rspike3.setRotationPoint(-14.0f, -153.0f, -32.0f);
        this.Rspike3.setTextureSize(1024, 1024);
        this.Rspike3.mirror = true;
        this.setRotation(this.Rspike3, -0.4363323f, 0.0f, -0.0174533f);
        (this.Lspike4 = new ModelRenderer((ModelBase) this, 500, 165)).addBox(0.0f, -50.0f, 0.0f, 0, 50, 36);
        this.Lspike4.setRotationPoint(18.0f, -131.0f, 13.0f);
        this.Lspike4.setTextureSize(1024, 1024);
        this.Lspike4.mirror = true;
        this.setRotation(this.Lspike4, -0.715585f, 0.0f, -0.0174533f);
        (this.Rspike4 = new ModelRenderer((ModelBase) this, 500, 165)).addBox(0.0f, -50.0f, 0.0f, 0, 50, 36);
        this.Rspike4.setRotationPoint(-18.0f, -131.0f, 13.0f);
        this.Rspike4.setTextureSize(1024, 1024);
        this.Rspike4.mirror = true;
        this.setRotation(this.Rspike4, -0.715585f, 0.0f, -0.0174533f);
        (this.Lspike5 = new ModelRenderer((ModelBase) this, 500, 255)).addBox(12.0f, -67.0f, 5.0f, 0, 39, 27);
        this.Lspike5.setRotationPoint(0.0f, -73.0f, 26.0f);
        this.Lspike5.setTextureSize(1024, 1024);
        this.Lspike5.mirror = true;
        this.setRotation(this.Lspike5, -0.7853982f, 0.0f, -0.0174533f);
        (this.Rspike5 = new ModelRenderer((ModelBase) this, 500, 255)).addBox(-12.0f, -67.0f, 5.0f, 0, 39, 27);
        this.Rspike5.setRotationPoint(0.0f, -73.0f, 26.0f);
        this.Rspike5.setTextureSize(1024, 1024);
        this.Rspike5.mirror = true;
        this.setRotation(this.Rspike5, -0.7853982f, 0.0f, -0.0174533f);
        (this.Spike6 = new ModelRenderer((ModelBase) this, 500, 325)).addBox(0.0f, -48.0f, 11.0f, 0, 25, 21);
        this.Spike6.setRotationPoint(0.0f, -48.0f, 48.0f);
        this.Spike6.setTextureSize(1024, 1024);
        this.Spike6.mirror = true;
        this.setRotation(this.Spike6, -0.8901179f, 0.0f, -0.0174533f);
        (this.Spikes7 = new ModelRenderer((ModelBase) this, 500, 376)).addBox(0.0f, -29.0f, 20.0f, 0, 10, 11);
        this.Spikes7.setRotationPoint(0.0f, -24.0f, 66.0f);
        this.Spikes7.setTextureSize(1024, 1024);
        this.Spikes7.mirror = true;
        this.setRotation(this.Spikes7, -0.7504916f, 0.0f, -0.0174533f);
    }

    public void render(final Entity entity, final float f, final float f1, final float f2, final float f3,
        final float f4, final float f5) {
        final Godzilla e = (Godzilla) entity;
        RenderInfo r = null;
        float newangle = 0.0f;
        float newangle2 = 0.0f;
        final float pscale = 1.0f;
        final float pi4 = 0.7853982f;
        final float clawZ = 6.0f;
        final float clawY = 16.0f;
        final float clawZamp = 35.0f * pscale;
        final float clawYamp = 18.0f * pscale;
        final float spikeamp = 1.0f;
        final float spikefreq = 1.0f;
        super.render(entity, f, f1, f2, f3, f4, f5);
        this.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        r = e.getRenderInfo();
        float t1 = 0.0f;
        float t2 = 0.0f;
        if (f1 > 0.001) {
            newangle = MathHelper.cos(f2 * 0.75f * this.wingspeed / pscale);
            newangle2 = MathHelper.cos(f2 * 0.75f * this.wingspeed / pscale + pi4);
            t1 = MathHelper.sin(f2 * 0.75f * this.wingspeed / pscale);
        } else {
            newangle2 = (newangle = 0.0f);
            t1 = 0.0f;
            t2 = 0.0f;
        }
        if (t1 > 0.0f) {
            t2 = t1 * clawYamp * f1;
            this.LToe1.rotationPointY = clawY - t2;
        } else {
            this.LToe1.rotationPointY = clawY;
        }
        this.LToe1.rotationPointZ = clawZ + clawZamp * newangle * f1;
        final ModelRenderer lToe2 = this.LToe2;
        final ModelRenderer lToe3 = this.LToe3;
        final ModelRenderer lToe4 = this.LToe4;
        final ModelRenderer lToe5 = this.LToe5;
        final ModelRenderer lToe6 = this.LToe6;
        final ModelRenderer lToe7 = this.LToe7;
        final ModelRenderer lToe8 = this.LToe8;
        final ModelRenderer lToe9 = this.LToe9;
        final float rotationPointZ = this.LToe1.rotationPointZ;
        lToe9.rotationPointZ = rotationPointZ;
        lToe8.rotationPointZ = rotationPointZ;
        lToe7.rotationPointZ = rotationPointZ;
        lToe6.rotationPointZ = rotationPointZ;
        lToe5.rotationPointZ = rotationPointZ;
        lToe4.rotationPointZ = rotationPointZ;
        lToe3.rotationPointZ = rotationPointZ;
        lToe2.rotationPointZ = rotationPointZ;
        final ModelRenderer lToe10 = this.LToe2;
        final ModelRenderer lToe11 = this.LToe3;
        final ModelRenderer lToe12 = this.LToe4;
        final ModelRenderer lToe13 = this.LToe5;
        final ModelRenderer lToe14 = this.LToe6;
        final ModelRenderer lToe15 = this.LToe7;
        final ModelRenderer lToe16 = this.LToe8;
        final ModelRenderer lToe17 = this.LToe9;
        final float rotationPointY = this.LToe1.rotationPointY;
        lToe17.rotationPointY = rotationPointY;
        lToe16.rotationPointY = rotationPointY;
        lToe15.rotationPointY = rotationPointY;
        lToe14.rotationPointY = rotationPointY;
        lToe13.rotationPointY = rotationPointY;
        lToe12.rotationPointY = rotationPointY;
        lToe11.rotationPointY = rotationPointY;
        lToe10.rotationPointY = rotationPointY;
        this.LLowerLeg.rotationPointZ = this.LToe1.rotationPointZ;
        this.LLowerLeg.rotationPointY = this.LToe1.rotationPointY;
        this.LLowerLeg.rotateAngleX = 0.22f + newangle * 3.1415927f * 0.09f * f1;
        this.LUpperLeg.rotateAngleX = -0.17f + newangle2 * 3.1415927f * 0.15f * f1;
        this.LUpperLeg.rotationPointY = this.LLowerLeg.rotationPointY
            - (float) Math.cos(this.LLowerLeg.rotateAngleX) * 55.0f;
        this.LUpperLeg.rotationPointZ = this.LLowerLeg.rotationPointZ
            - (float) Math.sin(this.LLowerLeg.rotateAngleX) * 55.0f;
        this.LThigh.rotateAngleX = -0.558f + newangle2 * 3.1415927f * 0.1f * f1;
        this.LThigh.rotationPointZ = 2.0f + clawZamp * newangle * f1 / 4.0f;
        t1 = 0.0f;
        t2 = 0.0f;
        if (f1 > 0.001) {
            newangle = MathHelper.cos(f2 * 0.75f * this.wingspeed / pscale + pi4 * 4.0f);
            newangle2 = MathHelper.cos(f2 * 0.75f * this.wingspeed / pscale + pi4 * 5.0f);
            t1 = MathHelper.sin(f2 * 0.75f * this.wingspeed / pscale + pi4 * 4.0f);
        } else {
            newangle = 0.0f;
            t1 = 0.0f;
            t2 = 0.0f;
        }
        if (t1 > 0.0f) {
            t2 = t1 * clawYamp * f1;
            this.RToe1.rotationPointY = clawY - t2;
        } else {
            this.RToe1.rotationPointY = clawY;
        }
        this.RToe1.rotationPointZ = clawZ + clawZamp * newangle * f1;
        final ModelRenderer rToe2 = this.RToe2;
        final ModelRenderer rToe3 = this.RToe3;
        final ModelRenderer rToe4 = this.RToe4;
        final ModelRenderer rToe5 = this.RToe5;
        final ModelRenderer rToe6 = this.RToe6;
        final ModelRenderer rToe7 = this.RToe7;
        final ModelRenderer rToe8 = this.RToe8;
        final ModelRenderer rToe9 = this.RToe9;
        final float rotationPointZ2 = this.RToe1.rotationPointZ;
        rToe9.rotationPointZ = rotationPointZ2;
        rToe8.rotationPointZ = rotationPointZ2;
        rToe7.rotationPointZ = rotationPointZ2;
        rToe6.rotationPointZ = rotationPointZ2;
        rToe5.rotationPointZ = rotationPointZ2;
        rToe4.rotationPointZ = rotationPointZ2;
        rToe3.rotationPointZ = rotationPointZ2;
        rToe2.rotationPointZ = rotationPointZ2;
        final ModelRenderer rToe10 = this.RToe2;
        final ModelRenderer rToe11 = this.RToe3;
        final ModelRenderer rToe12 = this.RToe4;
        final ModelRenderer rToe13 = this.RToe5;
        final ModelRenderer rToe14 = this.RToe6;
        final ModelRenderer rToe15 = this.RToe7;
        final ModelRenderer rToe16 = this.RToe8;
        final ModelRenderer rToe17 = this.RToe9;
        final float rotationPointY2 = this.RToe1.rotationPointY;
        rToe17.rotationPointY = rotationPointY2;
        rToe16.rotationPointY = rotationPointY2;
        rToe15.rotationPointY = rotationPointY2;
        rToe14.rotationPointY = rotationPointY2;
        rToe13.rotationPointY = rotationPointY2;
        rToe12.rotationPointY = rotationPointY2;
        rToe11.rotationPointY = rotationPointY2;
        rToe10.rotationPointY = rotationPointY2;
        this.RLegLower.rotationPointZ = this.RToe1.rotationPointZ;
        this.RLegLower.rotationPointY = this.RToe1.rotationPointY;
        this.RLegLower.rotateAngleX = 0.22f + newangle * 3.1415927f * 0.09f * f1;
        this.RLegUpper.rotateAngleX = -0.17f + newangle2 * 3.1415927f * 0.15f * f1;
        this.RLegUpper.rotationPointY = this.RLegLower.rotationPointY
            - (float) Math.cos(this.RLegLower.rotateAngleX) * 55.0f;
        this.RLegUpper.rotationPointZ = this.RLegLower.rotationPointZ
            - (float) Math.sin(this.RLegLower.rotateAngleX) * 55.0f;
        this.RThigh.rotateAngleX = -0.558f + newangle2 * 3.1415927f * 0.1f * f1;
        this.RThigh.rotationPointZ = 2.0f + clawZamp * newangle * f1 / 4.0f;
        final ModelRenderer lToe18 = this.LToe2;
        final ModelRenderer lToe19 = this.LToe3;
        final ModelRenderer lToe20 = this.LToe4;
        final ModelRenderer lToe21 = this.LToe5;
        final ModelRenderer lToe22 = this.LToe6;
        final ModelRenderer lToe23 = this.LToe7;
        final ModelRenderer lToe24 = this.LToe8;
        final ModelRenderer lToe25 = this.LToe9;
        final ModelRenderer lToe26 = this.LToe1;
        final float rotateAngleX = 0.0f;
        lToe26.rotateAngleX = rotateAngleX;
        lToe25.rotateAngleX = rotateAngleX;
        lToe24.rotateAngleX = rotateAngleX;
        lToe23.rotateAngleX = rotateAngleX;
        lToe22.rotateAngleX = rotateAngleX;
        lToe21.rotateAngleX = rotateAngleX;
        lToe20.rotateAngleX = rotateAngleX;
        lToe19.rotateAngleX = rotateAngleX;
        lToe18.rotateAngleX = rotateAngleX;
        final ModelRenderer rToe18 = this.RToe2;
        final ModelRenderer rToe19 = this.RToe3;
        final ModelRenderer rToe20 = this.RToe4;
        final ModelRenderer rToe21 = this.RToe5;
        final ModelRenderer rToe22 = this.RToe6;
        final ModelRenderer rToe23 = this.RToe7;
        final ModelRenderer rToe24 = this.RToe8;
        final ModelRenderer rToe25 = this.RToe9;
        final ModelRenderer rToe26 = this.RToe1;
        final float rotateAngleX2 = 0.0f;
        rToe26.rotateAngleX = rotateAngleX2;
        rToe25.rotateAngleX = rotateAngleX2;
        rToe24.rotateAngleX = rotateAngleX2;
        rToe23.rotateAngleX = rotateAngleX2;
        rToe22.rotateAngleX = rotateAngleX2;
        rToe21.rotateAngleX = rotateAngleX2;
        rToe20.rotateAngleX = rotateAngleX2;
        rToe19.rotateAngleX = rotateAngleX2;
        rToe18.rotateAngleX = rotateAngleX2;
        if (e.getAttacking() != 0) {
            newangle = MathHelper.cos(f2 * this.wingspeed * 1.75f) * 3.1415927f * 0.2f;
        } else {
            newangle = MathHelper.cos(f2 * this.wingspeed * 0.75f) * 3.1415927f * 0.05f;
        }
        this.doTail(newangle);
        newangle = (float) Math.toRadians(f3) * 0.55f;
        this.Head.rotateAngleY = newangle;
        this.TopJaw.rotateAngleY = newangle;
        this.LowerJaw.rotateAngleY = newangle;
        this.LowerJaw.rotationPointZ = this.Head.rotationPointZ - (float) Math.cos(this.Head.rotateAngleY) * 11.0f;
        this.LowerJaw.rotationPointX = this.Head.rotationPointX - (float) Math.sin(this.Head.rotateAngleY) * 11.0f;
        final ModelRenderer topJaw = this.TopJaw;
        final ModelRenderer head = this.Head;
        final float n = (float) Math.toRadians(f4);
        head.rotateAngleX = n;
        topJaw.rotateAngleX = n;
        newangle = MathHelper.cos(f2 * this.wingspeed * 1.5f) * 3.1415927f * 0.12f;
        float newrf1 = f2 * 1.5f * this.wingspeed % 6.2831855f;
        newrf1 = Math.abs(newrf1);
        if (newrf1 < r.rf2) {
            r.ri2 = 0;
            if (e.getAttacking() == 0) {
                if (e.worldObj.rand.nextInt(20) == 1) {
                    final RenderInfo renderInfo = r;
                    renderInfo.ri2 |= 0x1;
                }
            } else if (e.worldObj.rand.nextInt(2) == 1) {
                final RenderInfo renderInfo2 = r;
                renderInfo2.ri2 |= 0x1;
            }
        }
        r.rf2 = newrf1;
        if ((r.ri2 & 0x1) == 0x0) {
            newangle = 0.0f;
        }
        this.LowerJaw.rotateAngleX = 0.52f + newangle + this.TopJaw.rotateAngleX;
        newangle2 = (newangle = MathHelper.sin(f2 * this.wingspeed * 1.75f) * 3.1415927f * 0.16f);
        newrf1 = f2 * 1.75f * this.wingspeed % 6.2831855f;
        newrf1 = Math.abs(newrf1);
        if (newrf1 < r.rf1) {
            r.ri1 = 0;
            if (e.getAttacking() == 0) {
                if (e.worldObj.rand.nextInt(20) == 1) {
                    final RenderInfo renderInfo3 = r;
                    renderInfo3.ri1 |= 0x1;
                }
                if (e.worldObj.rand.nextInt(20) == 1) {
                    final RenderInfo renderInfo4 = r;
                    renderInfo4.ri1 |= 0x2;
                }
            } else {
                if (e.worldObj.rand.nextInt(2) == 1) {
                    final RenderInfo renderInfo5 = r;
                    renderInfo5.ri1 |= 0x1;
                }
                if (e.worldObj.rand.nextInt(2) == 1) {
                    final RenderInfo renderInfo6 = r;
                    renderInfo6.ri1 |= 0x2;
                }
            }
        }
        r.rf1 = newrf1;
        if ((r.ri1 & 0x1) == 0x0) {
            newangle = 0.0f;
        }
        if ((r.ri1 & 0x2) == 0x0) {
            newangle2 = 0.0f;
        }
        this.LUpperArm.rotateAngleY = 0.65f + newangle;
        this.LLowerArm.rotateAngleY = 0.78f + newangle * 3.0f / 2.0f;
        this.LLowerArm.rotationPointZ = this.LUpperArm.rotationPointZ
            - (float) Math.sin(this.LUpperArm.rotateAngleY) * 50.0f;
        this.LLowerArm.rotationPointX = this.LUpperArm.rotationPointX
            + (float) Math.cos(this.LUpperArm.rotateAngleY) * 50.0f;
        this.LLowerArm.rotationPointY = this.LUpperArm.rotationPointY
            - (float) Math.sin(this.LUpperArm.rotateAngleY) * 10.0f
            + 18.0f;
        this.LHand.rotationPointZ = this.LLowerArm.rotationPointZ
            - (float) Math.sin(this.LLowerArm.rotateAngleY) * 45.0f;
        this.LHand.rotationPointX = this.LLowerArm.rotationPointX
            + (float) Math.cos(this.LLowerArm.rotateAngleY) * 45.0f;
        this.LHand.rotationPointY = this.LLowerArm.rotationPointY
            - (float) Math.sin(this.LLowerArm.rotateAngleY) * 10.0f
            + 15.0f;
        final ModelRenderer lIndexBase = this.LIndexBase;
        final ModelRenderer lThumbBase = this.LThumbBase;
        final ModelRenderer l3rdFingerBase = this.L3rdFingerBase;
        final float rotationPointZ3 = this.LHand.rotationPointZ;
        l3rdFingerBase.rotationPointZ = rotationPointZ3;
        lThumbBase.rotationPointZ = rotationPointZ3;
        lIndexBase.rotationPointZ = rotationPointZ3;
        final ModelRenderer lIndexTip = this.LIndexTip;
        final ModelRenderer lThumbTip = this.LThumbTip;
        final ModelRenderer l3rdFingerTip = this.L3rdFingerTip;
        final float rotationPointZ4 = this.LHand.rotationPointZ;
        l3rdFingerTip.rotationPointZ = rotationPointZ4;
        lThumbTip.rotationPointZ = rotationPointZ4;
        lIndexTip.rotationPointZ = rotationPointZ4;
        final ModelRenderer lIndexBase2 = this.LIndexBase;
        final ModelRenderer lThumbBase2 = this.LThumbBase;
        final ModelRenderer l3rdFingerBase2 = this.L3rdFingerBase;
        final float rotationPointY3 = this.LHand.rotationPointY;
        l3rdFingerBase2.rotationPointY = rotationPointY3;
        lThumbBase2.rotationPointY = rotationPointY3;
        lIndexBase2.rotationPointY = rotationPointY3;
        final ModelRenderer lIndexTip2 = this.LIndexTip;
        final ModelRenderer lThumbTip2 = this.LThumbTip;
        final ModelRenderer l3rdFingerTip2 = this.L3rdFingerTip;
        final float rotationPointY4 = this.LHand.rotationPointY;
        l3rdFingerTip2.rotationPointY = rotationPointY4;
        lThumbTip2.rotationPointY = rotationPointY4;
        lIndexTip2.rotationPointY = rotationPointY4;
        final ModelRenderer lIndexBase3 = this.LIndexBase;
        final ModelRenderer lThumbBase3 = this.LThumbBase;
        final ModelRenderer l3rdFingerBase3 = this.L3rdFingerBase;
        final float rotationPointX = this.LHand.rotationPointX;
        l3rdFingerBase3.rotationPointX = rotationPointX;
        lThumbBase3.rotationPointX = rotationPointX;
        lIndexBase3.rotationPointX = rotationPointX;
        final ModelRenderer lIndexTip3 = this.LIndexTip;
        final ModelRenderer lThumbTip3 = this.LThumbTip;
        final ModelRenderer l3rdFingerTip3 = this.L3rdFingerTip;
        final float rotationPointX2 = this.LHand.rotationPointX;
        l3rdFingerTip3.rotationPointX = rotationPointX2;
        lThumbTip3.rotationPointX = rotationPointX2;
        lIndexTip3.rotationPointX = rotationPointX2;
        this.LHand.rotateAngleY = 1.308f + newangle * 2.0f;
        this.LIndexBase.rotateAngleY = -0.139f + newangle * 2.0f;
        this.LIndexTip.rotateAngleY = -0.034f + newangle * 2.0f;
        this.LThumbBase.rotateAngleY = 0.261f + newangle;
        this.LThumbTip.rotateAngleY = 0.139f + newangle;
        this.L3rdFingerBase.rotateAngleY = -0.471f + newangle * 3.0f;
        this.L3rdFingerTip.rotateAngleY = -0.331f + newangle * 3.0f;
        this.RUpperArm.rotateAngleY = -0.65f - newangle2;
        this.RLowerArm.rotateAngleY = -0.78f - newangle2 * 3.0f / 2.0f;
        this.RLowerArm.rotationPointZ = this.RUpperArm.rotationPointZ
            + (float) Math.sin(this.RUpperArm.rotateAngleY) * 50.0f;
        this.RLowerArm.rotationPointX = this.RUpperArm.rotationPointX
            - (float) Math.cos(this.RUpperArm.rotateAngleY) * 50.0f;
        this.RLowerArm.rotationPointY = this.RUpperArm.rotationPointY
            + (float) Math.sin(this.RUpperArm.rotateAngleY) * 10.0f
            + 18.0f;
        this.RHand.rotationPointZ = this.RLowerArm.rotationPointZ
            + (float) Math.sin(this.RLowerArm.rotateAngleY) * 45.0f;
        this.RHand.rotationPointX = this.RLowerArm.rotationPointX
            - (float) Math.cos(this.RLowerArm.rotateAngleY) * 45.0f;
        this.RHand.rotationPointY = this.RLowerArm.rotationPointY
            + (float) Math.sin(this.RLowerArm.rotateAngleY) * 10.0f
            + 15.0f;
        final ModelRenderer rIndexBase = this.RIndexBase;
        final ModelRenderer rThumbBase = this.RThumbBase;
        final ModelRenderer r3rdFingerBase = this.R3rdFingerBase;
        final float rotationPointZ5 = this.RHand.rotationPointZ;
        r3rdFingerBase.rotationPointZ = rotationPointZ5;
        rThumbBase.rotationPointZ = rotationPointZ5;
        rIndexBase.rotationPointZ = rotationPointZ5;
        final ModelRenderer rIndexTip = this.RIndexTip;
        final ModelRenderer rThumbTip = this.RThumbTip;
        final ModelRenderer r3rdFingerTip = this.R3rdFingerTip;
        final float rotationPointZ6 = this.RHand.rotationPointZ;
        r3rdFingerTip.rotationPointZ = rotationPointZ6;
        rThumbTip.rotationPointZ = rotationPointZ6;
        rIndexTip.rotationPointZ = rotationPointZ6;
        final ModelRenderer rIndexBase2 = this.RIndexBase;
        final ModelRenderer rThumbBase2 = this.RThumbBase;
        final ModelRenderer r3rdFingerBase2 = this.R3rdFingerBase;
        final float rotationPointY5 = this.RHand.rotationPointY;
        r3rdFingerBase2.rotationPointY = rotationPointY5;
        rThumbBase2.rotationPointY = rotationPointY5;
        rIndexBase2.rotationPointY = rotationPointY5;
        final ModelRenderer rIndexTip2 = this.RIndexTip;
        final ModelRenderer rThumbTip2 = this.RThumbTip;
        final ModelRenderer r3rdFingerTip2 = this.R3rdFingerTip;
        final float rotationPointY6 = this.RHand.rotationPointY;
        r3rdFingerTip2.rotationPointY = rotationPointY6;
        rThumbTip2.rotationPointY = rotationPointY6;
        rIndexTip2.rotationPointY = rotationPointY6;
        final ModelRenderer rIndexBase3 = this.RIndexBase;
        final ModelRenderer rThumbBase3 = this.RThumbBase;
        final ModelRenderer r3rdFingerBase3 = this.R3rdFingerBase;
        final float rotationPointX3 = this.RHand.rotationPointX;
        r3rdFingerBase3.rotationPointX = rotationPointX3;
        rThumbBase3.rotationPointX = rotationPointX3;
        rIndexBase3.rotationPointX = rotationPointX3;
        final ModelRenderer rIndexTip3 = this.RIndexTip;
        final ModelRenderer rThumbTip3 = this.RThumbTip;
        final ModelRenderer r3rdFingerTip3 = this.R3rdFingerTip;
        final float rotationPointX4 = this.RHand.rotationPointX;
        r3rdFingerTip3.rotationPointX = rotationPointX4;
        rThumbTip3.rotationPointX = rotationPointX4;
        rIndexTip3.rotationPointX = rotationPointX4;
        this.RHand.rotateAngleY = -2.0f - newangle2 * 2.0f;
        this.RIndexBase.rotateAngleY = 0.157f - newangle2 * 2.0f;
        this.RIndexTip.rotateAngleY = 0.174f - newangle2 * 2.0f;
        this.RThumbBase.rotateAngleY = -0.104f - newangle2;
        this.RThumbTip.rotateAngleY = 0.001f - newangle2;
        this.R3rdFingerTip.rotateAngleY = 0.68f - newangle2 * 3.0f;
        this.R3rdFingerBase.rotateAngleY = 0.645f - newangle2 * 3.0f;
        e.setRenderInfo(r);
        this.LToe1.render(f5);
        this.LToe3.render(f5);
        this.LToe2.render(f5);
        this.LToe9.render(f5);
        this.LToe8.render(f5);
        this.LToe7.render(f5);
        this.LToe6.render(f5);
        this.LToe5.render(f5);
        this.LToe4.render(f5);
        this.RToe9.render(f5);
        this.RToe6.render(f5);
        this.RToe5.render(f5);
        this.RToe2.render(f5);
        this.RToe1.render(f5);
        this.RToe4.render(f5);
        this.RToe7.render(f5);
        this.RToe8.render(f5);
        this.RToe3.render(f5);
        this.LThigh.render(f5);
        this.LLowerLeg.render(f5);
        this.LUpperLeg.render(f5);
        this.TailTip.render(f5);
        this.RLegLower.render(f5);
        this.RLegUpper.render(f5);
        this.RThigh.render(f5);
        this.LowerJaw.render(f5);
        this.TailBase.render(f5);
        this.Tail2.render(f5);
        this.Tail3.render(f5);
        this.Tail4.render(f5);
        this.Tail5.render(f5);
        this.Tail6.render(f5);
        this.Tail7.render(f5);
        this.BodyBottom.render(f5);
        this.RLowerArm.render(f5);
        this.BodyCenter.render(f5);
        this.Neck.render(f5);
        this.TopJaw.render(f5);
        this.Head.render(f5);
        this.BodyTop.render(f5);
        this.RShoulder.render(f5);
        this.RThumbTip.render(f5);
        this.RUpperArm.render(f5);
        this.RHand.render(f5);
        this.RThumbBase.render(f5);
        this.R3rdFingerTip.render(f5);
        this.R3rdFingerBase.render(f5);
        this.RIndexTip.render(f5);
        this.RIndexBase.render(f5);
        this.LShoulder.render(f5);
        this.LUpperArm.render(f5);
        this.LLowerArm.render(f5);
        this.LIndexBase.render(f5);
        this.LIndexTip.render(f5);
        this.LHand.render(f5);
        this.LThumbBase.render(f5);
        this.LThumbTip.render(f5);
        this.L3rdFingerTip.render(f5);
        this.L3rdFingerBase.render(f5);
        this.Lspikes1.render(f5);
        this.Rspikes1.render(f5);
        this.Lspike2.render(f5);
        this.Rspike2.render(f5);
        this.Lspike3.render(f5);
        this.Rspike3.render(f5);
        this.Lspike4.render(f5);
        this.Rspike4.render(f5);
        this.Lspike5.render(f5);
        this.Rspike5.render(f5);
        this.Spike6.render(f5);
        this.Spikes7.render(f5);
    }

    private void setRotation(final ModelRenderer model, final float x, final float y, final float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(final float par1, final float par2, final float par3, final float par4,
        final float par5, final float par6, final Entity par7Entity) {
        super.setRotationAngles(par1, par2, par3, par4, par5, par6, par7Entity);
    }

    private void doTail(final float angle) {
        this.TailBase.rotateAngleY = angle * 0.25f;
        final ModelRenderer lspike5 = this.Lspike5;
        final ModelRenderer rspike5 = this.Rspike5;
        final float rotateAngleY = this.TailBase.rotateAngleY;
        rspike5.rotateAngleY = rotateAngleY;
        lspike5.rotateAngleY = rotateAngleY;
        this.Tail2.rotateAngleY = angle * 0.5f;
        this.Tail2.rotationPointZ = this.TailBase.rotationPointZ + (float) Math.cos(this.TailBase.rotateAngleY) * 25.0f;
        this.Tail2.rotationPointX = this.TailBase.rotationPointX + (float) Math.sin(this.TailBase.rotateAngleY) * 25.0f;
        this.Spike6.rotateAngleY = this.Tail2.rotateAngleY;
        this.Spike6.rotationPointZ = this.Tail2.rotationPointZ;
        this.Spike6.rotationPointX = this.Tail2.rotationPointX;
        this.Tail3.rotateAngleY = angle * 0.75f;
        this.Tail3.rotationPointZ = this.Tail2.rotationPointZ + (float) Math.cos(this.Tail2.rotateAngleY) * 20.0f;
        this.Tail3.rotationPointX = this.Tail2.rotationPointX + (float) Math.sin(this.Tail2.rotateAngleY) * 20.0f;
        this.Spikes7.rotateAngleY = this.Tail3.rotateAngleY;
        this.Spikes7.rotationPointZ = this.Tail3.rotationPointZ;
        this.Spikes7.rotationPointX = this.Tail3.rotationPointX;
        this.Tail4.rotateAngleY = angle * 1.25f;
        this.Tail4.rotationPointZ = this.Tail3.rotationPointZ + (float) Math.cos(this.Tail3.rotateAngleY) * 20.0f;
        this.Tail4.rotationPointX = this.Tail3.rotationPointX + (float) Math.sin(this.Tail3.rotateAngleY) * 20.0f;
        this.Tail5.rotateAngleY = angle * 1.5f;
        this.Tail5.rotationPointZ = this.Tail4.rotationPointZ + (float) Math.cos(this.Tail4.rotateAngleY) * 25.0f;
        this.Tail5.rotationPointX = this.Tail4.rotationPointX + (float) Math.sin(this.Tail4.rotateAngleY) * 25.0f;
        this.Tail6.rotateAngleY = angle * 1.75f;
        this.Tail6.rotationPointZ = this.Tail5.rotationPointZ + (float) Math.cos(this.Tail5.rotateAngleY) * 27.0f;
        this.Tail6.rotationPointX = this.Tail5.rotationPointX + (float) Math.sin(this.Tail5.rotateAngleY) * 27.0f;
        this.Tail7.rotateAngleY = angle * 2.0f;
        this.Tail7.rotationPointZ = this.Tail6.rotationPointZ + (float) Math.cos(this.Tail6.rotateAngleY) * 28.0f;
        this.Tail7.rotationPointX = this.Tail6.rotationPointX + (float) Math.sin(this.Tail6.rotateAngleY) * 28.0f;
        this.TailTip.rotateAngleY = angle * 2.25f;
        this.TailTip.rotationPointZ = this.Tail7.rotationPointZ + (float) Math.cos(this.Tail7.rotateAngleY) * 18.0f;
        this.TailTip.rotationPointX = this.Tail7.rotationPointX + (float) Math.sin(this.Tail7.rotateAngleY) * 18.0f;
    }
}
