
package fr.iamacat.dangerzone_iamacatfr.entities.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;

public class RPGModel extends ModelBase {

    ModelRenderer BarrelB;
    ModelRenderer BarrelM;
    ModelRenderer RearEnd;
    ModelRenderer RearEnd2;
    ModelRenderer Ring;
    ModelRenderer Tube;
    ModelRenderer BarrelF;
    ModelRenderer StickF;
    ModelRenderer Rocket1;
    ModelRenderer Rocket2;
    ModelRenderer Held;
    ModelRenderer Lever1;
    ModelRenderer Lever3;
    ModelRenderer Lever4;
    ModelRenderer Lever2;
    ModelRenderer Lever5;
    ModelRenderer Thing2;
    ModelRenderer Thing1;
    ModelRenderer Thing4;
    ModelRenderer Thing3;
    ModelRenderer Bar;
    ModelRenderer BarrelM2;

    public RPGModel() {
        this.textureWidth = 128;
        this.textureHeight = 128;
        (this.BarrelB = new ModelRenderer((ModelBase) this, 0, 36)).addBox(0.0f, 0.0f, 0.0f, 2, 2, 8);
        this.BarrelB.setRotationPoint(0.0f, 0.0f, 16.0f);
        this.BarrelB.setTextureSize(128, 128);
        this.BarrelB.mirror = true;
        this.setRotation(this.BarrelB, 0.0f, 0.0f, 0.0f);
        (this.BarrelM = new ModelRenderer((ModelBase) this, 0, 16)).addBox(-0.5f, -0.5f, 0.0f, 3, 3, 16);
        this.BarrelM.setRotationPoint(0.0f, 0.0f, 1.0f);
        this.BarrelM.setTextureSize(128, 128);
        this.BarrelM.mirror = true;
        this.setRotation(this.BarrelM, 0.0f, 0.0f, 0.0f);
        (this.RearEnd = new ModelRenderer((ModelBase) this, 30, 0)).addBox(-0.5f, -0.5f, 0.0f, 3, 3, 2);
        this.RearEnd.setRotationPoint(0.0f, 0.0f, 23.0f);
        this.RearEnd.setTextureSize(128, 128);
        this.RearEnd.mirror = true;
        this.setRotation(this.RearEnd, 0.0f, 0.0f, 0.0f);
        (this.RearEnd2 = new ModelRenderer((ModelBase) this, 42, 0)).addBox(-1.0f, -1.0f, 0.0f, 4, 4, 2);
        this.RearEnd2.setRotationPoint(0.0f, 0.0f, 25.0f);
        this.RearEnd2.setTextureSize(128, 128);
        this.RearEnd2.mirror = true;
        this.setRotation(this.RearEnd2, 0.0f, 0.0f, 0.0f);
        (this.Ring = new ModelRenderer((ModelBase) this, 56, 0)).addBox(-1.0f, -1.0f, 0.0f, 4, 4, 1);
        this.Ring.setRotationPoint(0.0f, 0.0f, 7.0f);
        this.Ring.setTextureSize(128, 128);
        this.Ring.mirror = true;
        this.setRotation(this.Ring, 0.0f, 0.0f, 0.0f);
        (this.Tube = new ModelRenderer((ModelBase) this, 70, 0)).addBox(-1.0f, -1.0f, 0.0f, 4, 4, 6);
        this.Tube.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.Tube.setTextureSize(128, 128);
        this.Tube.mirror = true;
        this.setRotation(this.Tube, 0.0f, 0.0f, 0.0f);
        (this.BarrelF = new ModelRenderer((ModelBase) this, 40, 16)).addBox(0.0f, 0.0f, 0.0f, 2, 2, 12);
        this.BarrelF.setRotationPoint(0.0f, 0.0f, -11.0f);
        this.BarrelF.setTextureSize(128, 128);
        this.BarrelF.mirror = true;
        this.setRotation(this.BarrelF, 0.0f, 0.0f, 0.0f);
        (this.StickF = new ModelRenderer((ModelBase) this, 0, 47)).addBox(0.5f, 0.5f, -1.0f, 1, 1, 10);
        this.StickF.setRotationPoint(0.0f, 0.0f, -18.0f);
        this.StickF.setTextureSize(128, 128);
        this.StickF.mirror = true;
        this.setRotation(this.StickF, 0.0f, 0.0f, 0.0f);
        (this.Rocket1 = new ModelRenderer((ModelBase) this, 0, 8)).addBox(0.0f, 0.0f, -7.0f, 2, 2, 6);
        this.Rocket1.setRotationPoint(0.0f, 0.0f, -11.0f);
        this.Rocket1.setTextureSize(128, 128);
        this.Rocket1.mirror = true;
        this.setRotation(this.Rocket1, 0.0f, 0.0f, 0.0f);
        (this.Rocket2 = new ModelRenderer((ModelBase) this, 0, 0)).addBox(-0.5f, -0.5f, -7.0f, 3, 3, 4);
        this.Rocket2.setRotationPoint(0.0f, 0.0f, -10.0f);
        this.Rocket2.setTextureSize(128, 128);
        this.Rocket2.mirror = true;
        this.setRotation(this.Rocket2, 0.0f, 0.0f, 0.0f);
        (this.Held = new ModelRenderer((ModelBase) this, 0, 80)).addBox(0.5f, 3.0f, 3.0f, 1, 4, 2);
        this.Held.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.Held.setTextureSize(128, 128);
        this.Held.mirror = true;
        this.setRotation(this.Held, 0.0f, 0.0f, 0.0f);
        (this.Lever1 = new ModelRenderer((ModelBase) this, 42, 8)).addBox(0.5f, 2.0f, -5.0f, 1, 3, 2);
        this.Lever1.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.Lever1.setTextureSize(128, 128);
        this.Lever1.mirror = true;
        this.setRotation(this.Lever1, 0.0f, 0.0f, 0.0f);
        (this.Lever3 = new ModelRenderer((ModelBase) this, 54, 9)).addBox(-1.0f, 0.0f, 0.0f, 1, 3, 1);
        this.Lever3.setRotationPoint(1.0f, 2.0f, -4.5f);
        this.Lever3.setTextureSize(128, 128);
        this.Lever3.mirror = true;
        this.setRotation(this.Lever3, 0.0f, 0.7853982f, 0.0f);
        (this.Lever4 = new ModelRenderer((ModelBase) this, 59, 9)).addBox(-1.0f, 0.0f, 0.0f, 1, 3, 1);
        this.Lever4.setRotationPoint(1.0f, 2.0f, -5.0f);
        this.Lever4.setTextureSize(128, 128);
        this.Lever4.mirror = true;
        this.setRotation(this.Lever4, 0.0f, 0.7853982f, 0.0f);
        (this.Lever2 = new ModelRenderer((ModelBase) this, 49, 9)).addBox(-1.0f, 0.0f, 0.0f, 1, 3, 1);
        this.Lever2.setRotationPoint(1.0f, 2.0f, -4.0f);
        this.Lever2.setTextureSize(128, 128);
        this.Lever2.mirror = true;
        this.setRotation(this.Lever2, 0.0f, 0.7853982f, 0.0f);
        (this.Lever5 = new ModelRenderer((ModelBase) this, 64, 9)).addBox(-1.0f, 0.0f, 0.0f, 1, 3, 1);
        this.Lever5.setRotationPoint(1.0f, 2.0f, -5.5f);
        this.Lever5.setTextureSize(128, 128);
        this.Lever5.mirror = true;
        this.setRotation(this.Lever5, 0.0f, 0.7853982f, 0.0f);
        (this.Thing2 = new ModelRenderer((ModelBase) this, 0, 60)).addBox(0.5f, -4.0f, 2.0f, 1, 4, 2);
        this.Thing2.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.Thing2.setTextureSize(128, 128);
        this.Thing2.mirror = true;
        this.setRotation(this.Thing2, 0.0f, 0.0f, 0.0f);
        (this.Thing1 = new ModelRenderer((ModelBase) this, 18, 7)).addBox(0.0f, 0.0f, 2.0f, 2, 4, 3);
        this.Thing1.setRotationPoint(0.0f, -2.0f, 0.0f);
        this.Thing1.setTextureSize(128, 128);
        this.Thing1.mirror = true;
        this.setRotation(this.Thing1, 0.0f, 0.0f, 0.0f);
        (this.Thing4 = new ModelRenderer((ModelBase) this, 0, 68)).addBox(0.5f, -4.0f, 4.5f, 1, 4, 1);
        this.Thing4.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.Thing4.setTextureSize(128, 128);
        this.Thing4.mirror = true;
        this.setRotation(this.Thing4, 0.7853982f, 0.0f, 0.0f);
        (this.Thing3 = new ModelRenderer((ModelBase) this, 0, 75)).addBox(0.5f, -4.0f, 4.0f, 1, 1, 2);
        this.Thing3.setRotationPoint(0.0f, 1.0f, 0.0f);
        this.Thing3.setTextureSize(128, 128);
        this.Thing3.mirror = true;
        this.setRotation(this.Thing3, 0.0f, 0.0f, 0.0f);
        (this.Bar = new ModelRenderer((ModelBase) this, 23, 0)).addBox(0.5f, -1.0f, 3.0f, 1, 2, 2);
        this.Bar.setRotationPoint(0.0f, 0.0f, -13.0f);
        this.Bar.setTextureSize(128, 128);
        this.Bar.mirror = true;
        this.setRotation(this.Bar, 0.0f, 0.0f, 0.0f);
        (this.BarrelM2 = new ModelRenderer((ModelBase) this, 30, 8)).addBox(-0.5f, -0.5f, 0.0f, 3, 3, 2);
        this.BarrelM2.setRotationPoint(0.0f, 0.0f, -1.0f);
        this.BarrelM2.setTextureSize(128, 128);
        this.BarrelM2.mirror = true;
        this.setRotation(this.BarrelM2, 0.0f, 0.0f, 0.0f);
    }

    public void render() {
        final float f5 = 1.0f;
        this.BarrelB.render(f5);
        this.BarrelM.render(f5);
        this.RearEnd.render(f5);
        this.RearEnd2.render(f5);
        this.Ring.render(f5);
        this.Tube.render(f5);
        this.BarrelF.render(f5);
        this.StickF.render(f5);
        this.Rocket1.render(f5);
        this.Rocket2.render(f5);
        this.Held.render(f5);
        this.Lever1.render(f5);
        this.Lever3.render(f5);
        this.Lever4.render(f5);
        this.Lever2.render(f5);
        this.Lever5.render(f5);
        this.Thing2.render(f5);
        this.Thing1.render(f5);
        this.Thing4.render(f5);
        this.Thing3.render(f5);
        this.Bar.render(f5);
        this.BarrelM2.render(f5);
    }

    private void setRotation(final ModelRenderer model, final float x, final float y, final float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }
}
