
package fr.iamacat.dangerzone_iamacatfr.entities.model;

import fr.iamacat.dangerzone_iamacatfr.entities.entity.TwilicornInstance;
import fr.iamacat.dangerzone_iamacatfr.entities.render.InfoRenderer;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class TwilicornModel extends ModelBase {

    private float wingspeed;
    ModelRenderer TwilicornWingR1;
    ModelRenderer TwilicornWingR4;
    ModelRenderer TwilicornWingR5;
    ModelRenderer TwilicornWingR2;
    ModelRenderer TwilicornWingR6;
    ModelRenderer TwilicornWingR7;
    ModelRenderer TwilicornWingR8;
    ModelRenderer TwilicornWingR9;
    ModelRenderer TwilicornWingR3;
    ModelRenderer TwilicornWingL1;
    ModelRenderer TwilicornWingL2;
    ModelRenderer TwilicornWingL4;
    ModelRenderer TwilicornWingL5;
    ModelRenderer LegBR1;
    ModelRenderer TwilicornWingL6;
    ModelRenderer TwilicornBody;
    ModelRenderer MareHead;
    ModelRenderer TwilicornWingL7;
    ModelRenderer TwilicornNeck;
    ModelRenderer TwilicornHorn;
    ModelRenderer TwilicornWingL8;
    ModelRenderer LegBL1;
    ModelRenderer LegR1;
    ModelRenderer LegL1;
    ModelRenderer Tail1;
    ModelRenderer LegBL2;
    ModelRenderer Mane;
    ModelRenderer LegL3;
    ModelRenderer LegR2;
    ModelRenderer LegR3;
    ModelRenderer LegL2;
    ModelRenderer Tail2;
    ModelRenderer Tail3;
    ModelRenderer Tail4;
    ModelRenderer Tail5;
    ModelRenderer LegBR2;
    ModelRenderer TwilicornWingL9;
    ModelRenderer TwilicornWingL3;

    public TwilicornModel(final float f1) {
        this.wingspeed = 0.7f;
        this.textureWidth = 256;
        this.textureHeight = 256;
        (this.TwilicornWingR1 = new ModelRenderer((ModelBase) this, 0, 155)).addBox(-8.0f, 0.0f, 0.0f, 8, 1, 2);
        this.TwilicornWingR1.setRotationPoint(-4.0f, 7.0f, -3.0f);
        this.TwilicornWingR1.setTextureSize(256, 256);
        this.TwilicornWingR1.mirror = true;
        this.setRotation(this.TwilicornWingR1, 0.0f, -0.1858931f, 0.0f);
        (this.TwilicornWingR4 = new ModelRenderer((ModelBase) this, 0, 155)).addBox(-11.5f, 0.0f, -7.5f, 8, 1, 2);
        this.TwilicornWingR4.setRotationPoint(-4.0f, 7.0f, -3.0f);
        this.TwilicornWingR4.setTextureSize(256, 256);
        this.TwilicornWingR4.mirror = true;
        this.setRotation(this.TwilicornWingR4, 0.0f, 0.9666439f, 0.0f);
        (this.TwilicornWingR5 = new ModelRenderer((ModelBase) this, 0, 111)).addBox(-14.0f, 0.0f, -4.5f, 9, 1, 2);
        this.TwilicornWingR5.setRotationPoint(-4.0f, 7.0f, -3.0f);
        this.TwilicornWingR5.setTextureSize(256, 256);
        this.TwilicornWingR5.mirror = true;
        this.setRotation(this.TwilicornWingR5, 0.0f, 0.7086656f, 0.0f);
        (this.TwilicornWingR2 = new ModelRenderer((ModelBase) this, 0, 111)).addBox(-8.0f, 0.0f, 0.0f, 9, 1, 5);
        this.TwilicornWingR2.setRotationPoint(-4.0f, 7.0f, -3.0f);
        this.TwilicornWingR2.setTextureSize(256, 256);
        this.TwilicornWingR2.mirror = true;
        this.setRotation(this.TwilicornWingR2, 0.0f, 0.0f, 0.0f);
        (this.TwilicornWingR6 = new ModelRenderer((ModelBase) this, 0, 111)).addBox(-12.0f, 0.0f, -5.0f, 8, 1, 2);
        this.TwilicornWingR6.setRotationPoint(-4.0f, 7.0f, -3.0f);
        this.TwilicornWingR6.setTextureSize(256, 256);
        this.TwilicornWingR6.mirror = true;
        this.setRotation(this.TwilicornWingR6, 0.0f, 0.9666439f, 0.0f);
        (this.TwilicornWingR7 = new ModelRenderer((ModelBase) this, 0, 111)).addBox(-10.0f, 0.0f, -5.6f, 8, 1, 2);
        this.TwilicornWingR7.setRotationPoint(-4.0f, 7.0f, -3.0f);
        this.TwilicornWingR7.setTextureSize(256, 256);
        this.TwilicornWingR7.mirror = true;
        this.setRotation(this.TwilicornWingR7, 0.0f, 1.301251f, 0.0f);
        (this.TwilicornWingR8 = new ModelRenderer((ModelBase) this, 0, 111)).addBox(-9.0f, 0.0f, -4.0f, 8, 1, 2);
        this.TwilicornWingR8.setRotationPoint(-4.0f, 7.0f, -3.0f);
        this.TwilicornWingR8.setTextureSize(256, 256);
        this.TwilicornWingR8.mirror = true;
        this.setRotation(this.TwilicornWingR8, 0.0f, 1.405971f, 0.0f);
        (this.TwilicornWingR9 = new ModelRenderer((ModelBase) this, 0, 111)).addBox(-8.0f, 0.0f, -2.2f, 7, 1, 2);
        this.TwilicornWingR9.setRotationPoint(-4.0f, 7.0f, -3.0f);
        this.TwilicornWingR9.setTextureSize(256, 256);
        this.TwilicornWingR9.mirror = true;
        this.setRotation(this.TwilicornWingR9, 0.0f, 1.502326f, 0.0f);
        (this.TwilicornWingR3 = new ModelRenderer((ModelBase) this, 0, 111)).addBox(-8.0f, -0.5f, 1.0f, 7, 2, 3);
        this.TwilicornWingR3.setRotationPoint(-4.0f, 7.0f, -3.0f);
        this.TwilicornWingR3.setTextureSize(256, 256);
        this.TwilicornWingR3.mirror = true;
        this.setRotation(this.TwilicornWingR3, 0.0f, -0.1858931f, 0.0f);
        (this.TwilicornWingL1 = new ModelRenderer((ModelBase) this, 0, 155)).addBox(0.0f, 0.0f, 0.0f, 8, 1, 2);
        this.TwilicornWingL1.setRotationPoint(4.0f, 7.0f, -3.0f);
        this.TwilicornWingL1.setTextureSize(256, 256);
        this.TwilicornWingL1.mirror = true;
        this.setRotation(this.TwilicornWingL1, 0.0f, 0.185895f, 0.0f);
        (this.TwilicornWingL2 = new ModelRenderer((ModelBase) this, 0, 111)).addBox(0.0f, 0.0f, 0.0f, 9, 1, 5);
        this.TwilicornWingL2.setRotationPoint(4.0f, 7.0f, -3.0f);
        this.TwilicornWingL2.setTextureSize(256, 256);
        this.TwilicornWingL2.mirror = true;
        this.setRotation(this.TwilicornWingL2, 0.0f, 0.0f, 0.0f);
        (this.TwilicornWingL4 = new ModelRenderer((ModelBase) this, 0, 155)).addBox(3.5f, 0.0f, -7.5f, 8, 1, 2);
        this.TwilicornWingL4.setRotationPoint(4.0f, 7.0f, -3.0f);
        this.TwilicornWingL4.setTextureSize(256, 256);
        this.TwilicornWingL4.mirror = true;
        this.setRotation(this.TwilicornWingL4, 0.0f, -0.9666506f, 0.0f);
        (this.TwilicornWingL5 = new ModelRenderer((ModelBase) this, 0, 111)).addBox(5.0f, 0.0f, -4.5f, 9, 1, 2);
        this.TwilicornWingL5.setRotationPoint(4.0f, 7.0f, -3.0f);
        this.TwilicornWingL5.setTextureSize(256, 256);
        this.TwilicornWingL5.mirror = true;
        this.setRotation(this.TwilicornWingL5, 0.0f, -0.7086735f, 0.0f);
        (this.LegBR1 = new ModelRenderer((ModelBase) this, 0, 16)).addBox(0.0f, -1.0f, -2.0f, 3, 5, 3);
        this.LegBR1.setRotationPoint(-4.0f, 12.0f, 6.0f);
        this.LegBR1.setTextureSize(256, 256);
        this.LegBR1.mirror = true;
        this.setRotation(this.LegBR1, 0.0872665f, 0.0f, 0.0f);
        (this.TwilicornWingL6 = new ModelRenderer((ModelBase) this, 0, 111)).addBox(4.0f, 0.0f, -5.0f, 8, 1, 2);
        this.TwilicornWingL6.setRotationPoint(4.0f, 7.0f, -3.0f);
        this.TwilicornWingL6.setTextureSize(256, 256);
        this.TwilicornWingL6.mirror = true;
        this.setRotation(this.TwilicornWingL6, 0.0f, -0.9666506f, 0.0f);
        (this.TwilicornBody = new ModelRenderer((ModelBase) this, 21, 1)).addBox(-6.0f, -10.0f, -7.0f, 8, 15, 6);
        this.TwilicornBody.setRotationPoint(2.0f, 5.0f, 2.0f);
        this.TwilicornBody.setTextureSize(256, 256);
        this.TwilicornBody.mirror = true;
        this.setRotation(this.TwilicornBody, 1.570796f, 0.0f, 0.0f);
        (this.MareHead = new ModelRenderer((ModelBase) this, 54, 0)).addBox(-4.0f, -3.9f, -5.0f, 8, 8, 8);
        this.MareHead.setRotationPoint(0.0f, 0.0f, -8.0f);
        this.MareHead.setTextureSize(256, 256);
        this.MareHead.mirror = true;
        this.setRotation(this.MareHead, 0.0f, 0.0f, 0.0f);
        (this.TwilicornWingL7 = new ModelRenderer((ModelBase) this, 0, 111)).addBox(2.0f, 0.0f, -5.6f, 8, 1, 2);
        this.TwilicornWingL7.setRotationPoint(4.0f, 7.0f, -3.0f);
        this.TwilicornWingL7.setTextureSize(256, 256);
        this.TwilicornWingL7.mirror = true;
        this.setRotation(this.TwilicornWingL7, 0.0f, -1.301248f, 0.0f);
        (this.TwilicornNeck = new ModelRenderer((ModelBase) this, 0, 0)).addBox(0.0f, 0.0f, 0.5f, 4, 9, 4);
        this.TwilicornNeck.setRotationPoint(-2.0f, 2.0f, -11.0f);
        this.TwilicornNeck.setTextureSize(256, 256);
        this.TwilicornNeck.mirror = true;
        this.setRotation(this.TwilicornNeck, 0.2792527f, 0.0f, 0.0f);
        (this.TwilicornHorn = new ModelRenderer((ModelBase) this, 120, 15)).addBox(0.0f, 0.0f, 0.0f, 1, 5, 1);
        this.TwilicornHorn.setRotationPoint(0.0f, -6.0f, -26.0f);
        this.TwilicornHorn.setTextureSize(256, 256);
        this.TwilicornHorn.mirror = true;
        this.setRotation(this.TwilicornHorn, 0.6632251f, 0.0f, 0.0f);
        (this.TwilicornWingL8 = new ModelRenderer((ModelBase) this, 0, 111)).addBox(1.0f, 0.0f, -4.0f, 8, 1, 2);
        this.TwilicornWingL8.setRotationPoint(4.0f, 7.0f, -3.0f);
        this.TwilicornWingL8.setTextureSize(256, 256);
        this.TwilicornWingL8.mirror = true;
        this.setRotation(this.TwilicornWingL8, 0.0f, -1.405967f, 0.0f);
        (this.LegBL1 = new ModelRenderer((ModelBase) this, 0, 16)).addBox(0.0f, -1.0f, -2.0f, 3, 5, 3);
        this.LegBL1.setRotationPoint(1.0f, 12.0f, 6.0f);
        this.LegBL1.setTextureSize(256, 256);
        this.LegBL1.mirror = true;
        this.setRotation(this.LegBL1, 0.0872665f, 0.0f, 0.0f);
        (this.LegR1 = new ModelRenderer((ModelBase) this, 0, 16)).addBox(-2.0f, -1.0f, -3.0f, 3, 5, 3);
        this.LegR1.setRotationPoint(-1.5f, 12.0f, -4.0f);
        this.LegR1.setTextureSize(256, 256);
        this.LegR1.mirror = true;
        this.setRotation(this.LegR1, -0.0349066f, 0.0f, 0.0f);
        (this.LegL1 = new ModelRenderer((ModelBase) this, 0, 16)).addBox(-1.0f, -1.0f, -3.0f, 3, 5, 3);
        this.LegL1.setRotationPoint(1.5f, 12.0f, -4.0f);
        this.LegL1.setTextureSize(256, 256);
        this.LegL1.mirror = true;
        this.setRotation(this.LegL1, -0.0349066f, 0.0f, 0.0f);
        (this.Tail1 = new ModelRenderer((ModelBase) this, 92, 0)).addBox(-1.0f, -1.0f, -1.0f, 2, 3, 2);
        this.Tail1.setRotationPoint(0.0f, 8.0f, 7.0f);
        this.Tail1.setTextureSize(256, 256);
        this.Tail1.mirror = true;
        this.setRotation(this.Tail1, 2.119181f, 0.0f, 0.0f);
        (this.LegBL2 = new ModelRenderer((ModelBase) this, 0, 16)).addBox(0.0f, 4.0f, -1.5f, 3, 9, 3);
        this.LegBL2.setRotationPoint(1.0f, 12.0f, 6.0f);
        this.LegBL2.setTextureSize(256, 256);
        this.LegBL2.mirror = true;
        this.setRotation(this.LegBL2, 0.0698132f, 0.0f, 0.0f);
        (this.Mane = new ModelRenderer((ModelBase) this, 1, 46)).addBox(-4.0f, -4.0f, -5.0f, 9, 9, 9);
        this.Mane.setRotationPoint(-0.5f, 0.0f, -8.1f);
        this.Mane.setTextureSize(256, 256);
        this.Mane.mirror = true;
        this.setRotation(this.Mane, 0.0f, 0.0f, 0.0f);
        (this.LegL3 = new ModelRenderer((ModelBase) this, 0, 16)).addBox(-1.0f, 8.0f, -2.8f, 3, 4, 3);
        this.LegL3.setRotationPoint(1.5f, 12.0f, -4.0f);
        this.LegL3.setTextureSize(256, 256);
        this.LegL3.mirror = true;
        this.setRotation(this.LegL3, -0.0698132f, 0.0f, 0.0f);
        (this.LegR2 = new ModelRenderer((ModelBase) this, 0, 16)).addBox(-2.0f, 4.0f, -2.9f, 3, 4, 3);
        this.LegR2.setRotationPoint(-1.5f, 12.0f, -4.0f);
        this.LegR2.setTextureSize(256, 256);
        this.LegR2.mirror = true;
        this.setRotation(this.LegR2, -0.0523599f, 0.0f, 0.0f);
        (this.LegR3 = new ModelRenderer((ModelBase) this, 0, 16)).addBox(-2.0f, 8.0f, -2.8f, 3, 4, 3);
        this.LegR3.setRotationPoint(-1.5f, 12.0f, -4.0f);
        this.LegR3.setTextureSize(256, 256);
        this.LegR3.mirror = true;
        this.setRotation(this.LegR3, -0.0698132f, 0.0f, 0.0f);
        (this.LegL2 = new ModelRenderer((ModelBase) this, 0, 16)).addBox(-1.0f, 4.0f, -2.9f, 3, 4, 3);
        this.LegL2.setRotationPoint(1.5f, 12.0f, -4.0f);
        this.LegL2.setTextureSize(256, 256);
        this.LegL2.mirror = true;
        this.setRotation(this.LegL2, -0.0523599f, 0.0f, 0.0f);
        (this.Tail2 = new ModelRenderer((ModelBase) this, 102, 0)).addBox(-1.5f, 1.5f, -0.2f, 3, 3, 2);
        this.Tail2.setRotationPoint(0.0f, 8.0f, 7.0f);
        this.Tail2.setTextureSize(256, 256);
        this.Tail2.mirror = true;
        this.setRotation(this.Tail2, 1.710216f, 0.0f, 0.0f);
        (this.Tail3 = new ModelRenderer((ModelBase) this, 116, 0)).addBox(-2.0f, 4.0f, 0.6f, 4, 4, 2);
        this.Tail3.setRotationPoint(0.0f, 8.0f, 7.0f);
        this.Tail3.setTextureSize(256, 256);
        this.Tail3.mirror = true;
        this.setRotation(this.Tail3, 1.487144f, 0.0f, 0.0f);
        (this.Tail4 = new ModelRenderer((ModelBase) this, 130, 0)).addBox(-2.0f, 1.6f, 5.5f, 4, 6, 3);
        this.Tail4.setRotationPoint(0.0f, 8.0f, 7.0f);
        this.Tail4.setTextureSize(256, 256);
        this.Tail4.mirror = true;
        this.setRotation(this.Tail4, 0.4089647f, 0.0f, 0.0f);
        (this.Tail5 = new ModelRenderer((ModelBase) this, 150, 0)).addBox(-2.0f, 3.0f, 7.8f, 4, 10, 3);
        this.Tail5.setRotationPoint(0.0f, 8.0f, 7.0f);
        this.Tail5.setTextureSize(256, 256);
        this.Tail5.mirror = true;
        this.setRotation(this.Tail5, 0.0f, 0.0f, 0.0f);
        (this.LegBR2 = new ModelRenderer((ModelBase) this, 0, 16)).addBox(0.0f, 4.0f, -1.5f, 3, 9, 3);
        this.LegBR2.setRotationPoint(-4.0f, 12.0f, 6.0f);
        this.LegBR2.setTextureSize(256, 256);
        this.LegBR2.mirror = true;
        this.setRotation(this.LegBR2, 0.0698132f, 0.0f, 0.0f);
        (this.TwilicornWingL9 = new ModelRenderer((ModelBase) this, 0, 111)).addBox(1.0f, 0.0f, -2.2f, 7, 1, 2);
        this.TwilicornWingL9.setRotationPoint(4.0f, 7.0f, -3.0f);
        this.TwilicornWingL9.setTextureSize(256, 256);
        this.TwilicornWingL9.mirror = true;
        this.setRotation(this.TwilicornWingL9, 0.0f, -1.502327f, 0.0f);
        (this.TwilicornWingL3 = new ModelRenderer((ModelBase) this, 0, 111)).addBox(1.0f, -0.5f, 1.0f, 7, 2, 3);
        this.TwilicornWingL3.setRotationPoint(4.0f, 7.0f, -3.0f);
        this.TwilicornWingL3.setTextureSize(256, 256);
        this.TwilicornWingL3.mirror = true;
        this.setRotation(this.TwilicornWingL3, 0.0f, 0.185895f, 0.0f);
    }

    public void render(final Entity entity, final float f, final float f1, final float f2, final float f3,
        final float f4, final float f5) {
        final TwilicornInstance e = (TwilicornInstance) entity;
        float newangle = 0.0f;
        final float lspeed = 0.0f;
        final InfoRenderer r = null;
        final float tailspeed = 0.76f;
        final float tailamp = 0.45f;
        super.render(entity, f, f1, f2, f3, f4, f5);
        this.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        newangle = MathHelper.cos(f2 * 0.75f * this.wingspeed) * 3.141593f * 0.28f;
        this.MareHead.rotateAngleY = (float) Math.toRadians(f3);
        this.Mane.rotateAngleY = this.MareHead.rotateAngleY;
        this.TwilicornHorn.rotateAngleY = this.MareHead.rotateAngleY;
        this.TwilicornHorn.rotationPointZ = this.MareHead.rotationPointZ - 8.0f;
        this.TwilicornWingL1.rotateAngleZ = newangle * 3.0f / 2.0f;
        this.TwilicornWingL2.rotateAngleZ = newangle * 3.0f / 2.0f;
        this.TwilicornWingL2.rotationPointY = this.TwilicornWingL1.rotationPointY;
        this.TwilicornWingL2.rotationPointX = this.TwilicornWingL1.rotationPointX;
        this.TwilicornWingL3.rotateAngleZ = newangle * 3.0f / 2.0f;
        this.TwilicornWingL3.rotationPointY = this.TwilicornWingL1.rotationPointY;
        this.TwilicornWingL3.rotationPointX = this.TwilicornWingL1.rotationPointX;
        this.TwilicornWingL4.rotateAngleZ = newangle * 3.0f / 2.0f;
        this.TwilicornWingL4.rotationPointY = this.TwilicornWingL1.rotationPointY;
        this.TwilicornWingL4.rotationPointX = this.TwilicornWingL1.rotationPointX;
        this.TwilicornWingL5.rotateAngleZ = newangle * 3.0f / 2.0f;
        this.TwilicornWingL5.rotationPointY = this.TwilicornWingL1.rotationPointY;
        this.TwilicornWingL5.rotationPointX = this.TwilicornWingL1.rotationPointX;
        this.TwilicornWingL6.rotateAngleZ = newangle * 3.0f / 2.0f;
        this.TwilicornWingL6.rotationPointY = this.TwilicornWingL1.rotationPointY;
        this.TwilicornWingL6.rotationPointX = this.TwilicornWingL1.rotationPointX;
        this.TwilicornWingL7.rotateAngleZ = newangle * 3.0f / 2.0f;
        this.TwilicornWingL7.rotationPointY = this.TwilicornWingL1.rotationPointY;
        this.TwilicornWingL7.rotationPointX = this.TwilicornWingL1.rotationPointX;
        this.TwilicornWingL8.rotateAngleZ = newangle * 3.0f / 2.0f;
        this.TwilicornWingL8.rotationPointY = this.TwilicornWingL1.rotationPointY;
        this.TwilicornWingL8.rotationPointX = this.TwilicornWingL1.rotationPointX;
        this.TwilicornWingL9.rotateAngleZ = newangle * 3.0f / 2.0f;
        this.TwilicornWingL9.rotationPointY = this.TwilicornWingL1.rotationPointY;
        this.TwilicornWingL9.rotationPointX = this.TwilicornWingL1.rotationPointX;
        this.TwilicornWingR1.rotateAngleZ = -newangle * 3.0f / 2.0f;
        this.TwilicornWingR2.rotateAngleZ = -newangle * 3.0f / 2.0f;
        this.TwilicornWingR2.rotationPointY = this.TwilicornWingR1.rotationPointY;
        this.TwilicornWingR2.rotationPointX = this.TwilicornWingR1.rotationPointX;
        this.TwilicornWingR3.rotateAngleZ = -newangle * 3.0f / 2.0f;
        this.TwilicornWingR3.rotationPointY = this.TwilicornWingR1.rotationPointY;
        this.TwilicornWingR3.rotationPointX = this.TwilicornWingR1.rotationPointX;
        this.TwilicornWingR4.rotateAngleZ = -newangle * 3.0f / 2.0f;
        this.TwilicornWingR4.rotationPointY = this.TwilicornWingR1.rotationPointY;
        this.TwilicornWingR4.rotationPointX = this.TwilicornWingR1.rotationPointX;
        this.TwilicornWingR5.rotateAngleZ = -newangle * 3.0f / 2.0f;
        this.TwilicornWingR5.rotationPointY = this.TwilicornWingR1.rotationPointY;
        this.TwilicornWingR5.rotationPointX = this.TwilicornWingR1.rotationPointX;
        this.TwilicornWingR6.rotateAngleZ = -newangle * 3.0f / 2.0f;
        this.TwilicornWingR6.rotationPointY = this.TwilicornWingR1.rotationPointY;
        this.TwilicornWingR6.rotationPointX = this.TwilicornWingR1.rotationPointX;
        this.TwilicornWingR7.rotateAngleZ = -newangle * 3.0f / 2.0f;
        this.TwilicornWingR7.rotationPointY = this.TwilicornWingR1.rotationPointY;
        this.TwilicornWingR7.rotationPointX = this.TwilicornWingR1.rotationPointX;
        this.TwilicornWingR8.rotateAngleZ = -newangle * 3.0f / 2.0f;
        this.TwilicornWingR8.rotationPointY = this.TwilicornWingR1.rotationPointY;
        this.TwilicornWingR8.rotationPointX = this.TwilicornWingR1.rotationPointX;
        this.TwilicornWingR9.rotateAngleZ = -newangle * 3.0f / 2.0f;
        this.TwilicornWingR9.rotationPointY = this.TwilicornWingR1.rotationPointY;
        this.TwilicornWingR9.rotationPointX = this.TwilicornWingR1.rotationPointX;
        this.TwilicornWingR1.render(f5);
        this.TwilicornWingR4.render(f5);
        this.TwilicornWingR5.render(f5);
        this.TwilicornWingR2.render(f5);
        this.TwilicornWingR6.render(f5);
        this.TwilicornWingR7.render(f5);
        this.TwilicornWingR8.render(f5);
        this.TwilicornWingR9.render(f5);
        this.TwilicornWingR3.render(f5);
        this.TwilicornWingL1.render(f5);
        this.TwilicornWingL2.render(f5);
        this.TwilicornWingL4.render(f5);
        this.TwilicornWingL5.render(f5);
        this.LegBR1.render(f5);
        this.TwilicornWingL6.render(f5);
        this.TwilicornBody.render(f5);
        this.MareHead.render(f5);
        this.TwilicornWingL7.render(f5);
        this.TwilicornNeck.render(f5);
        this.TwilicornHorn.render(f5);
        this.TwilicornWingL8.render(f5);
        this.LegBL1.render(f5);
        this.LegR1.render(f5);
        this.LegL1.render(f5);
        this.Tail1.render(f5);
        this.LegBL2.render(f5);
        this.Mane.render(f5);
        this.LegL3.render(f5);
        this.LegR2.render(f5);
        this.LegR3.render(f5);
        this.LegL2.render(f5);
        this.Tail2.render(f5);
        this.Tail3.render(f5);
        this.Tail4.render(f5);
        this.Tail5.render(f5);
        this.LegBR2.render(f5);
        this.TwilicornWingL9.render(f5);
        this.TwilicornWingL3.render(f5);
    }

    private void setRotation(final ModelRenderer model, final float x, final float y, final float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(final float par1, final float par2, final float par3, final float par4,
        final float par5, final float par6, final Entity entity) {
        super.setRotationAngles(par1, par2, par3, par4, par5, par6, entity);
    }
}
