

package fr.iamacat.dangerzone_iamacatfr.api;

import com.google.common.base.Optional;
import net.minecraft.item.Item;

public enum ItemList
{
    instance;

    public static Optional<? extends Item> ankh;
    public static Optional<? extends Item> scaleItem;
    public static Optional<? extends Item> furPelt;
    public static Optional<? extends Item> aloeVeraSeeds;
    public static Optional<? extends Item> waterDroplets;
    public static Optional<? extends Item> coconutItem;
    public static Optional<? extends Item> coconutSeed;
    public static Optional<? extends Item> coconutShell;
    public static Optional<? extends Item> coconutShellFuel;
    public static Optional<? extends Item> coconutMilkFragment;
    public static Optional<? extends Item> genericCraftingItems;
    public static Optional<? extends Item> scrapMeat;
    public static Optional<? extends Item> muttonRaw;
    public static Optional<? extends Item> muttonCooked;
    public static Optional<? extends Item> structurePlacer;
    public static Optional<? extends Item> potionIngredients;
    public static Optional<? extends Item> customPotions;
    public static Optional<? extends Item> vanillaPotions;
    public static Optional<? extends Item> duckEgg;
    public static Optional<? extends Item> ostrichEgg;
    public static Optional<? extends Item> hammerTool;
    public static Optional<? extends Item> hammerToolIron;
    public static Optional<? extends Item> hammerToolWood;
    public static Optional<? extends Item> hammerToolStone;
    public static Optional<? extends Item> hammerToolNether;
    public static Optional<? extends Item> hammerToolDiamond;
    public static Optional<? extends Item> hammerToolGold;
    public static Optional<? extends Item> xpGem;
    public static Optional<? extends Item> throwingRock;
    public static Optional<? extends Item> woodenBucket;
    public static Optional<? extends Item> woodenBucketWater;
    public static Optional<? extends Item> woodenBucketMilk;
    public static Optional<? extends Item> waterSkinEmpty;
    public static Optional<? extends Item> waterSkinWater;
    public static Optional<? extends Item> waterSkinMilk;
    public static Optional<? extends Item> scaleArmorHead;
    public static Optional<? extends Item> scaleArmorChest;
    public static Optional<? extends Item> scaleArmorLeg;
    public static Optional<? extends Item> scaleArmorBoots;
    public static Optional<? extends Item> goldScaleArmorHead;
    public static Optional<? extends Item> goldScaleArmorChest;
    public static Optional<? extends Item> goldScaleArmorLeg;
    public static Optional<? extends Item> goldScaleArmorBoots;
    public static Optional<? extends Item> ironScaleArmorHead;
    public static Optional<? extends Item> ironScaleArmorChest;
    public static Optional<? extends Item> ironScaleArmorLeg;
    public static Optional<? extends Item> ironScaleArmorBoots;
    public static Optional<? extends Item> diamondScaleArmorHead;
    public static Optional<? extends Item> diamondScaleArmorChest;
    public static Optional<? extends Item> diamondScaleArmorLeg;
    public static Optional<? extends Item> diamondScaleArmorBoots;
    public static Optional<? extends Item> whiteClothHead;
    public static Optional<? extends Item> whiteClothChest;
    public static Optional<? extends Item> whiteClothLeg;
    public static Optional<? extends Item> whiteClothBoots;
    public static Optional<? extends Item> redClothHead;
    public static Optional<? extends Item> redClothChest;
    public static Optional<? extends Item> redClothLeg;
    public static Optional<? extends Item> redClothBoots;
    public static Optional<? extends Item> greenClothHead;
    public static Optional<? extends Item> greenClothChest;
    public static Optional<? extends Item> greenClothLeg;
    public static Optional<? extends Item> greenClothBoots;
    public static Optional<? extends Item> blueClothHead;
    public static Optional<? extends Item> blueClothChest;
    public static Optional<? extends Item> blueClothLeg;
    public static Optional<? extends Item> blueClothBoots;
    public static Optional<? extends Item> cactusArmorHead;
    public static Optional<? extends Item> cactusArmorChest;
    public static Optional<? extends Item> cactusArmorLeg;
    public static Optional<? extends Item> cactusArmorBoots;
    public static Optional<? extends Item> furArmorHead;
    public static Optional<? extends Item> furArmorChest;
    public static Optional<? extends Item> furArmorLeg;
    public static Optional<? extends Item> furArmorBoots;

    static {
        ItemList.ankh = Optional.absent();
        ItemList.scaleItem = Optional.absent();
        ItemList.furPelt = Optional.absent();
        ItemList.aloeVeraSeeds = Optional.absent();
        ItemList.waterDroplets = Optional.absent();
        ItemList.coconutItem = Optional.absent();
        ItemList.coconutSeed = Optional.absent();
        ItemList.coconutShell = Optional.absent();
        ItemList.coconutShellFuel = Optional.absent();
        ItemList.coconutMilkFragment = Optional.absent();
        ItemList.genericCraftingItems = Optional.absent();
        ItemList.scrapMeat = Optional.absent();
        ItemList.muttonRaw = Optional.absent();
        ItemList.muttonCooked = Optional.absent();
        ItemList.structurePlacer = Optional.absent();
        ItemList.potionIngredients = Optional.absent();
        ItemList.customPotions = Optional.absent();
        ItemList.vanillaPotions = Optional.absent();
        ItemList.duckEgg = Optional.absent();
        ItemList.ostrichEgg = Optional.absent();
        ItemList.hammerTool = Optional.absent();
        ItemList.hammerToolIron = Optional.absent();
        ItemList.hammerToolWood = Optional.absent();
        ItemList.hammerToolStone = Optional.absent();
        ItemList.hammerToolNether = Optional.absent();
        ItemList.hammerToolDiamond = Optional.absent();
        ItemList.hammerToolGold = Optional.absent();
        ItemList.xpGem = Optional.absent();
        ItemList.throwingRock = Optional.absent();
        ItemList.woodenBucket = Optional.absent();
        ItemList.woodenBucketWater = Optional.absent();
        ItemList.woodenBucketMilk = Optional.absent();
        ItemList.waterSkinEmpty = Optional.absent();
        ItemList.waterSkinWater = Optional.absent();
        ItemList.waterSkinMilk = Optional.absent();
        ItemList.scaleArmorHead = Optional.absent();
        ItemList.scaleArmorChest = Optional.absent();
        ItemList.scaleArmorLeg = Optional.absent();
        ItemList.scaleArmorBoots = Optional.absent();
        ItemList.goldScaleArmorHead = Optional.absent();
        ItemList.goldScaleArmorChest = Optional.absent();
        ItemList.goldScaleArmorLeg = Optional.absent();
        ItemList.goldScaleArmorBoots = Optional.absent();
        ItemList.ironScaleArmorHead = Optional.absent();
        ItemList.ironScaleArmorChest = Optional.absent();
        ItemList.ironScaleArmorLeg = Optional.absent();
        ItemList.ironScaleArmorBoots = Optional.absent();
        ItemList.diamondScaleArmorHead = Optional.absent();
        ItemList.diamondScaleArmorChest = Optional.absent();
        ItemList.diamondScaleArmorLeg = Optional.absent();
        ItemList.diamondScaleArmorBoots = Optional.absent();
        ItemList.whiteClothHead = Optional.absent();
        ItemList.whiteClothChest = Optional.absent();
        ItemList.whiteClothLeg = Optional.absent();
        ItemList.whiteClothBoots = Optional.absent();
        ItemList.redClothHead = Optional.absent();
        ItemList.redClothChest = Optional.absent();
        ItemList.redClothLeg = Optional.absent();
        ItemList.redClothBoots = Optional.absent();
        ItemList.greenClothHead = Optional.absent();
        ItemList.greenClothChest = Optional.absent();
        ItemList.greenClothLeg = Optional.absent();
        ItemList.greenClothBoots = Optional.absent();
        ItemList.blueClothHead = Optional.absent();
        ItemList.blueClothChest = Optional.absent();
        ItemList.blueClothLeg = Optional.absent();
        ItemList.blueClothBoots = Optional.absent();
        ItemList.cactusArmorHead = Optional.absent();
        ItemList.cactusArmorChest = Optional.absent();
        ItemList.cactusArmorLeg = Optional.absent();
        ItemList.cactusArmorBoots = Optional.absent();
        ItemList.furArmorHead = Optional.absent();
        ItemList.furArmorChest = Optional.absent();
        ItemList.furArmorLeg = Optional.absent();
        ItemList.furArmorBoots = Optional.absent();
    }
}
